### ISSUE TITLE
.skin文件如何制作？此框架支持网络下载皮肤进行换肤吗？

### ISSUE THREAD

**Issue by scrylove** [ximsfei/Android-skin-support#1]
.skin文件如何制作的？用来做什么？这个步骤没有交代呀？

**Comment by ximsfei** [comment]
https://github.com/ximsfei/Android-skin-support#制作皮肤插件
参考demo 中red.skin的实现: https://github.com/ximsfei/Android-skin-support/tree/master/skin-night
将打包生成的apk文件改名为.skin文件即可
支持网络下载皮肤, 下载下来放倒对应目录即可。
具体查看: https://github.com/ximsfei/Android-skin-support/blob/master/skin-support/src/main/java/skin/support/utils/SkinFileUtils.java中getSkinDir方法

**Comment by linhaosheng** [comment]
你好，运行你的最佳换肤实践的APP后报错： java.lang.NoSuchMethodError: No static method setBackground(Landroid/view/View;Landroid/graphics/drawable/Drawable;)V in class Landroid/support/v4/view/ViewCompat; or its super classes (declaration of 'android.support.v4.view.ViewCompat' appears in /data/app/com.ximsfei.skindemo-1/base.apk)

定位到的错误是SkinCompatBackgroundHelper 中的applySkin()方法里的
ColorStateList colorStateList =SkinCompatResources.getInstance().getColorStateList(mBackgroundResId);
                Drawable drawable = mView.getBackground();
                DrawableCompat.setTintList(drawable, colorStateList);
                ViewCompat.setBackground(mView, drawable);
中的  ViewCompat.setBackground(mView, drawable);报错的 我的手机是android 5.1的  使用的是
compile 'com.android.support:appcompat-v7:24.2.1' 请问这是什么原因

**Comment by ximsfei** [comment]
@linhaosheng 
这个问题应该是Android appcompat-v7包升级引起的, 我用的是compile 'com.android.support:appcompat-v7:25.1.0' 可能是该版本中新加的, 升级你的appcompat-v7即可解决.
