### ISSUE TITLE
动态设置TextView的textColor无法换肤

### ISSUE THREAD

**Issue by pkuoliver** [ximsfei/Android-skin-support#100]
问题描述：
我在默认皮肤里面定义了TextView两个状态的color，代码里面根据情况调用textView.setTextColor()方法换文字颜色；
在另外一个皮肤里面定义了另外一套色彩方案，无法更换文字颜色；

**Comment by ximsfei** [comment]
同#48

**Comment by pkuoliver** [comment]
我看了那个问题，我是为了能换肤，但是TextView.setTextColor()这个方法只能传入具体颜色值，而不能传入颜色资源。例如TextView.setTextColor(R.color.red);这种调用通不过编译。

**Comment by ximsfei** [comment]
`TextView.setTextColor(R.color.red);`这种调用通不过编译。是因为framework根本没有这个方法
可以使用`TextView.setTextAppearanche(R.style.RedTextAppearance);`来实现换肤

**Comment by pkuoliver** [comment]
试了一下setTextAppearanche需要apiLevel 23的，我的需要支持到14。
没能完美解决

**Comment by pkuoliver** [comment]
TextView.setTextAppearanche(R.style.RedTextAppearance);换肤也不生效

**Comment by ximsfei** [comment]
这个是有效的，可以看一下demo，demo里有例子

**Comment by pkuoliver** [comment]
感谢，生效了。之前不生效的原因是我的TextView是new出来的。
不过遇到另外一个疑惑的问题，还请楼主解惑。
当设置一个TextView的Background的时候，xml里面android:background="@drawable/btn_share_selector"，那么在res-night的drawable目录里面必须有btn_share_selector_night.xml，同时里面的图片都指定为night的图片；但是对于android:style这个属性，却不需要在res-night目录下新建一个styles.xml，只需要有相应的color定义即可，这样是不是就不统一了呢？其实我希望在res-night目录下面，那些***_selector.xml也不需要写，只要有相应的图片就可以了。
能否这样实现呢

**Comment by ximsfei** [comment]
我也想到了这个问题。理论上是可以实现的，开发的时候评估了一下，最终没有这么去做。
1. 类似`btn_share_selector_night.xml`这样的`drawable`，有各种各样的类型`ColorDrawable`，`BitmapDrawable`等等。如果每个xml都去解析，增加了框架复杂度，运行效率不高，容易产生bug，随着Android版本的升级，越来越多的`drawable`加入，那么框架都得跟着去做适配？框架适配没跟上的话，接入框架的应用岂不是遇到了坑，没法第一时间适配Android 9.0、 10.0 等等？
2. 关于style，也是当前这种方式较为妥当，利用`TypedArray`解析出需要换肤的属性`textColor`，`background`等去换肤，不像解析xml那样存在效率问题。如果style属性也不解析(新建styles.xml的方式)，假如有一个style的parent是一个support包里的style，那插件式的皮肤包是不是需要引入这个support包，增加了皮肤包的体积？当前实现只需要把对应的资源放到皮肤包里即可。

关于不统一的问题，用到这个框架遇到问题，看看[FAQ](https://github.com/ximsfei/Android-skin-support/blob/master/docs/FAQ.md)，翻翻issues，实在不行提个issues也就知道了。

**Comment by pkuoliver** [comment]
了解了，那我就把这个问题Close了。

**Comment by arronvera** [comment]
> 感谢，生效了。之前不生效的原因是我的TextView是new出来的。
> 不过遇到另外一个疑惑的问题，还请楼主解惑。
> 当设置一个TextView的Background的时候，xml里面android:background="@drawable/btn_share_selector"，那么在res-night的drawable目录里面必须有btn_share_selector_night.xml，同时里面的图片都指定为night的图片；但是对于android:style这个属性，却不需要在res-night目录下新建一个styles.xml，只需要有相应的color定义即可，这样是不是就不统一了呢？其实我希望在res-night目录下面，那些***_selector.xml也不需要写，只要有相应的图片就可以了。
> 能否这样实现呢

请问你new出来的textview怎么改变background呢
