### ISSUE TITLE
这个 支持 databinding 吗？

### ISSUE THREAD

**Issue by finddreams** [ximsfei/Android-skin-support#101]

**Comment by ximsfei** [comment]
暂时还没试过。我看看

**Comment by finddreams** [comment]
比如说这种 databinding 情况下的换肤 ：
android:textColor="@{item.check?@color/common_label_blue_color:@color/common_tv_hint_color}"

**Comment by ximsfei** [comment]
你可以先试一下，看样子是不支持的，看一下databinding生成的代码是什么样子的，我还没试过，刚觉应该会是`check ？ setTextColor(getColor(R.color. common_label_blue_color)) : setTextColor(getColor(R.color. common_tv_hint_color))`

可以试试`android:textAppearance="@{item.check?@style/common_label_blue_color:@style/common_tv_hint_color}`
