### ISSUE TITLE
提几个关于增加可用性的建议

### ISSUE THREAD

**Issue by pkuoliver** [ximsfei/Android-skin-support#102]
本换肤库功能确实比较强大。不过有些地方不能支持有些遗憾，虽然知道原因，但是如果能提供一些更方便的途径帮助调用者实现功能，也是极好的。例如
1. 不支持new出来的view换肤。可以提供一些接口，比如让调用者获取相应的颜色值/图片等，然后自己设置。
2. 某些使用第三方框架或者库，不能也不希望改动库内代码的时候，希望提供一个接口来禁用控件或者控件属性换肤。例如在使用xxx-Image-Loader的时候，进入一个页面，再次返回的时候，Image-Loader的图片就变成了默认的原始图片，而不是从网络加载的图片，这个原因是知道的，因为Image-Loader使用了setImageResource的方法，这时候就需要一个禁用控件换肤的功能。

个人建议，如果合适，希望能够采纳。

**Comment by ximsfei** [comment]
1. 框架是有接口可以使用的，例如`SkinCompatResources.getInstance().getColor(resId)`
2. 这一点当时想着不想换肤的话，直接用`setImageDrawable(drawable)`类似的方法即可，确实没想到第三方库加载，又不想换肤的情况，不知道有什么好的建议。

**Comment by pkuoliver** [comment]
第一个找到了，已经用上；
第二个问题，可以来一些这样的接口：
SkinCompatXXX.getInstance().registerIgnoreSkinView(view)
SkinCompatXXX.getInstance().registerIgnoreSkinView(view,"background","textColor”)

具体的实现，我不太了解内部代码结构，不过实在不行，可以来个黑名单，白名单之类的。虽然不优雅，但是能解决问题。

**Comment by ximsfei** [comment]
2. 第三方库加载，又不想换肤的情况，可以创建一个空的自定义View，继承自原先的View，布局文件中使用该View即可
