### ISSUE TITLE
自定义view使用应用内换肤貌似有点小问题

### ISSUE THREAD

**Issue by And009** [ximsfei/Android-skin-support#103]
颜色什么的设置都没问题，但是图片的设置貌似不可以，都是使用加后缀的方式

**Comment by ximsfei** [comment]
应该是自定义View实现存在问题。
框架实现的原生控件换肤，相当于也是自定义View，但是暂时还没发现问题，提问中好像也只是自定义View存在问题。所以对比一下框架的实现，好好排查一下，是不是哪里写的有问题。
