### ISSUE TITLE
版本2.2.2里面的SkinCompatBackgroundHelper方法好像没有实现最新的功能

### ISSUE THREAD

**Issue by yeyueduxing** [ximsfei/Android-skin-support#111]
这个版本里面背景设置使用color无效，然后看最新源码有对color,drawable,mipmap做处理，什么时候能更新版本呢？

**Comment by ximsfei** [comment]
能够再详细些吗？
依赖了哪些皮肤相关的lib。背景设置color无效的xml等？

**Comment by yeyueduxing** [comment]
依赖了
 compile 'skin.support:skin-support:2.2.2'                   // skin-support 基础控件支持
    compile 'skin.support:skin-support-design:2.2.2'            // skin-support-design material design 控件支持[可选]
    compile 'skin.support:skin-support-cardview:2.2.2'          // skin-support-cardview CardView 控件支持[可选]
    compile 'skin.support:skin-support-constraint-layout:2.2.2' // skin-support-constraint-layout ConstraintLayout 控件支持[可选]
这些版本，然后基本的视图都是可以换肤的，然后Toolbar使用background设置了color颜色，这个背景没有替换

**Comment by yeyueduxing** [comment]
在DENO中，在gradle中依赖改为
compile 'skin.support:skin-support:2.2.2' // skin-support 基础控件支持
compile 'skin.support:skin-support-design:2.2.2' // skin-support-design material design 控件支持[可选]
compile 'skin.support:skin-support-cardview:2.2.2' // skin-support-cardview CardView 控件支持[可选]
compile 'skin.support:skin-support-constraint-layout:2.2.2' // skin-support-constraint-layout ConstraintLayout 控件支持[可选]
然后在activity_material_design.xml修改
<android.support.design.widget.BottomNavigationView
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:layout_alignParentBottom="true"
                app:itemBackground="@color/background"
                app:itemIconTint="@color/navigation_item_tint"
                app:itemTextColor="@color/navigation_item_tint"
                app:menu="@menu/bottom_navigation_view_menu" />
添加app:itemBackground="@color/background"这个背景颜色，会发现BottomNavigationView背景没有修改

**Comment by yeyueduxing** [comment]
我去，@color这些怎么看不见啊

**Comment by ximsfei** [comment]
看一下[更新日志](https://github.com/ximsfei/Android-skin-support/blob/master/docs/ChangeLog_before_v2.2.2.md)，框架还没有对`BottomNavigationView`的`app:itemBackground`做默认支持，如果急用的话可以参照自定义View换肤去扩展。

**Comment by yeyueduxing** [comment]
嗯，不好意思啊，我在自己项目上Toolbar使用color无法换肤成功，然后在Demo中依赖2.2.2发现可以换肤成功，应该是我自己设置问题。这个可以关了，谢谢啊

**Comment by yeyueduxing** [comment]
发现一个问题哦，例如颜色的话 <color name="ye_color_Navigation_Base">#ffffff</color>
直接使用颜色值，换肤没问题。
但是原本颜色引用其他色值<color name="ye_color_Navigation_Base">@color/white</color>
然后换肤里面<color name="ye_color_Navigation_Base">#adadad</color>
换肤失败。
就是换肤的颜色值不能引用其他色值，引用了换肤会失败，要用固定颜色值。

**Comment by ximsfei** [comment]
是的，如果你引用了其他颜色值，那框架获取到的资源id是其他颜色值的资源id

**Comment by yeyueduxing** [comment]
嗯，好像，谢谢啊
