### ISSUE TITLE
ViewStub

### ISSUE THREAD

**Issue by zhangyingcheng** [ximsfei/Android-skin-support#112]
viewStub.setLayoutResource(R.layout.include_mapview_gaode);
 viewStub.inflate();
 SupportMapFragment supportMapFragment = (SupportMapFragment) 
 fragmentManager.findFragmentById(R.id.gao_de_map);
最后得到的 supportMapFragment 为null
可以确定问题是在 application 初始化 SkinCompatManager 产生的

**Comment by ximsfei** [comment]
`include_mapview_gaode.xml`这个布局文件内容是啥

**Comment by zhangyingcheng** [comment]
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <fragment
        android:id="@+id/gao_de_map"
        class="com.amap.api.maps.SupportMapFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</FrameLayout>

**Comment by zhangyingcheng** [comment]
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <fragment
        android:id="@+id/gao_de_map"
        class="com.amap.api.maps.SupportMapFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</FrameLayout>

**Comment by zhangyingcheng** [comment]
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <fragment
        android:id="@+id/gao_de_map"
        class="com.amap.api.maps.SupportMapFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</FrameLayout>

**Comment by ximsfei** [comment]
看一下[最新提交的代码](https://github.com/ximsfei/Android-skin-support/commit/8108ea5c52e146fb21197d5452e9021e06f5a66b)，跑一下demo。感觉没有问题。
