### ISSUE TITLE
启动页Launcher的主题windowBackground属性不能换肤

### ISSUE THREAD

**Issue by win-xp** [ximsfei/Android-skin-support#113]
[启动页短暂LOGO曝光功能](http://wuxiaolong.me/2017/03/13/appStart/)
这是我的主页面
```
<activity
    android:name=".MainActivity"
    android:label="@string/app_name"
    android:theme="@style/AppTheme.Launcher">
    <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
    </intent-filter>
</activity>
```
下面是我的style定义：
```
<style name="AppTheme.Launcher">
    <item name="android:windowBackground">@drawable/bg_launcher</item>
</style>
```
bg_launcher是一张需要换肤的图片，需要动态改变，我是以后缀的形式换肤，但是试了很久不行。其他Activity是没问题的，帮忙指点下 谢谢！

**Comment by ximsfei** [comment]
这样的配置，demo中SplashActivity是可以换windowBackground。希望可以给出可复现demo

**Comment by win-xp** [comment]
https://github.com/win-xp/SkinChangeDemo  我写了个demo帮忙看下

**Comment by ximsfei** [comment]
你写的demo，windowBackground不是可以换吗？

**Comment by win-xp** [comment]
第一步：闪屏的windowBackground没换成功，activity的换成功了，我在application写了个3秒延时，点击app启动时的背景颜色一直没变

**Comment by ximsfei** [comment]
那是因为，那个背景只受到主题控制，没发在java代码中更新。换肤框架只能换可以通过java代码设置的资源。

**Comment by win-xp** [comment]
好的，那就换不了了😑

**Comment by win-xp** [comment]
我研究下
