### ISSUE TITLE
TabLayout的字体颜色没有改变,checkbox也有些没有加上

### ISSUE THREAD

**Issue by weimingjue** [ximsfei/Android-skin-support#115]
最近更新到了最新版,TabLayout的横线虽然变了,但是字体颜色没有变化.
checkbox是textview的子类,而换肤里面的checkbox只做了setButtonDrawable的切换,这个方法一直以来就是个鸡肋,希望能增加textview相关的功能

**Comment by ximsfei** [comment]
TabLayout的字体颜色是可以切换的，可以参考一下demo里的使用。
checkbox可以扩展textview相关的换肤

**Comment by weimingjue** [comment]
TabLayout搞错了,写到代码里了.
checkbox只能代码动态设置了吗?
