### ISSUE TITLE
最近有个崩溃的bug

### ISSUE THREAD

**Issue by weimingjue** [ximsfei/Android-skin-support#116]
崩溃前提:没用到自定义控件,首页大约百十个需要换肤控件,当前皮肤已经切换到com.skin.mmm.skin
具体代码:在mainActivity的第四个frag的onViewCreated的最后调用了loadSkin("com.skin.mmm.skin",listener, SkinCompatManager.SKIN_LOADER_STRATEGY_ASSETS)
application的代码
        SkinCompatManager.withoutActivity(this).addInflater(new SkinMaterialViewInflater()).loadSkin();
复现步骤:切换到指定皮肤,杀死app,再打开必崩溃
崩溃日志:系统级崩溃,只有一行Fatal signal 7 (SIGBUS), code 2, fault addr 0xd91403e8 in tid 4954
调试结果:指向SkinAssetsLoader.copySkinFromAssets方法
猜测:可能由于子线程和主线程并发读写同一文件导致

**Comment by ximsfei** [comment]
项目是否有多进程？

**Comment by weimingjue** [comment]
没有多进程(集成的第三方有,但是没有涉及到ui界面),并且mainActivity除了请求网络其他都是在主线程中执行的

**Comment by ximsfei** [comment]
判断一下进程，只在主进程里初始化框架就好了。

**Comment by weimingjue** [comment]
刚刚单独测了一上午,原来布局中有ViewStub引起的,具体如下:
Activity的布局:
<android.support.v4.view.ViewPager
    android:id="@+id/vp_skintest_vp"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

</android.support.v4.view.ViewPager>
Activity代码:
        SkinCompatManager.getInstance().loadSkin("com.skin.ssss.skin",
                new SkinCompatManager.SkinLoaderListener() {
                    @Override
                    public void onStart() {
                        // Utils.toast("开始换肤");
                    }

                    @Override
                    public void onSuccess() {
                        Utils.toast("成功换肤");
                    }

                    @Override
                    public void onFailed(String errMsg) {
                        Utils.toast("换肤失败!");
                    }
                }, SkinCompatManager.SKIN_LOADER_STRATEGY_ASSETS);
        mVp.setAdapter(new BaseAdapterVPFrag(getSupportFragmentManager(),new SkinTestFrag2()));

fragment的布局:
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

  
    <ViewStub
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout="@layout/test_layout"/>

    <View
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:background="@color/换肤的颜色"
        />
</LinearLayout>
fragment没有任何代码
ViewStub的test_layout就一个RelativeLayout没有任何东西


运行第一次正常,杀死app再打开必崩溃
顺便吐槽一下上一个人写的代码:各种Scrollview套listview再套gridview,还在用ViewStub搞效率,真坑爹啊,整个首页都没有注释,10行代码都能写成100行

**Comment by weimingjue** [comment]
这个也不算大bug,皮肤再application就已经加载完成了,他们又在fragment里面又来了一遍,唉.

**Comment by MelodySir** [comment]
我也遇到了这个问题，在application中初始化的皮肤，登录页面正常，皮肤加载也正常，登录成功后打开复杂度高一些的主页activity导致闪退（不定时），这个最终有没有好的解决方案

**Comment by ximsfei** [comment]
多个进程都初始化了框架？

**Comment by MelodySir** [comment]
只在application中初始化了，但是主页会出现多个异步网络请求

**Comment by ximsfei** [comment]
每个进程都会走application的方法的

**Comment by MelodySir** [comment]
在加载皮肤的时候也进行了判断，如果当前加载的皮肤的名称与将要加载的皮肤的名称相同，则不加载皮肤

**Comment by ximsfei** [comment]
判断进程呢？只在需要换肤的进程加载皮肤

**Comment by arronvera** [comment]
我这边也偶现启动页闪退，指向换肤三方控件，初始化的时候判断了进程，还是会闪退

**Comment by jarkeet** [comment]
> 我这边也偶现启动页闪退，指向换肤三方控件，初始化的时候判断了进程，还是会闪退

大兄弟  我这边也遇到了，请问怎么解决了？

**Comment by p-jet** [comment]
来信已收到

**Comment by KAImportad** [comment]
> 来信已收到

该问题已经修复了吗？请问如何解决？

**Comment by p-jet** [comment]
来信已收到

**Comment by 1976222027** [comment]
String  processName = Application.getProcessName();
        if (processName != context.getPackageName()) { // 进程名不同
            return;
}
xxxxx.loadSkin();

**Comment by p-jet** [comment]
来信已收到
