### ISSUE TITLE
一些使用后的建议

### ISSUE THREAD

**Issue by YummyLau** [ximsfei/Android-skin-support#117]
感谢作者的开源，学习了。
在使用该库进行组件化开发的过程中，由于状态栏是独立处理的，并且需要兼容使用原生且兼容国产部分机型，所以并没有打开 #setSkinStatusBarColorEnable 方法处理。
看了源码的实现，是通过独立的资源包和原需要替换的id进行搜索替换。是否能过暴露一个api，是通过特定的资源，比如R.color.colorPrimary ,通过api能返回另一个ColorInt的方法。暴露的这个方法可供作者您未适配到的地方（可能不是view）或者用户独立处理的地方使用。

**Comment by ximsfei** [comment]
现在就已经有类似的api了，可以参考[`SkinCompatResources.getColor()`](https://github.com/ximsfei/Android-skin-support/blob/master/android-support/skin-support/src/main/java/skin/support/content/res/SkinCompatResources.java)

**Comment by YummyLau** [comment]
十分感谢。解决了我的问题。
