### ISSUE TITLE
状态栏如何换肤

### ISSUE THREAD

**Issue by huqusmile** [ximsfei/Android-skin-support#121]
状态栏如何换肤？

**Comment by ximsfei** [comment]
可以参考[demo中的actionbar换肤](https://github.com/ximsfei/Android-skin-support/blob/master/demo/skin-app/src/main/java/com/ximsfei/skindemo/actionbar/ActionbarTestActivity.java)，在applySkin方法中实现状态栏换肤。

**Comment by huqusmile** [comment]
demo:skin-app里面的状态栏换肤是colorPrimaryDark常规的通过后缀_night来实现的啊，5.0以下的怎么办

**Comment by ximsfei** [comment]
5.0以下自己在applyskin中实现

**Comment by huqusmile** [comment]
BaseActivity实现SkinCompatSupportable，然后在回调方法applySkin里面重新去设置状态栏颜色？

**Comment by ximsfei** [comment]
是的

**Comment by Fantasy-Van** [comment]
BaseActivity实现SkinCompatSupportable，然后在回调方法applySkin里面重新去设置状态栏颜色后，报错找不到资源ID，知道怎么回事吗？

**Comment by ximsfei** [comment]
@Fantasy-Van 看一下applyskin方法怎么实现的

**Comment by ximsfei** [comment]
没有要求，你再排查一下，哪里出问题了

**Comment by Fantasy-Van** [comment]
调试了下，大体找到了未生效的原因，BaseAct中applySkin方法中实现状态栏变色，ACT1和ACT2同时继承BaseAct，ACT1换肤成功后startActivity启动ACT2，这时ACT2的状态栏未生效，好像是跳转ACT后失效，这种有好的解决方法没，谢谢？

**Comment by Fantasy-Van** [comment]
除了在BaseAct加个是否需要换肤标志位，支持的话执行SkinCompatManager.getInstance().loadSkin("night.skin", SkinCompatManager.SKIN_LOADER_STRATEGY_ASSETS);还有其他方法吗？

**Comment by ximsfei** [comment]
发一下，BaseAct的applySkin方法是怎么实现的？
还有，再applySkin中执行loadSkin是错误的用法。

**Comment by Fantasy-Van** [comment]
没在applySkin中执行loadSkin，在onCreate判断执行的，但是出了些问题。
pplySkin代码如下，麻烦看下，谢谢
 @Override
    public void applySkin() {
        //5.0以上
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            Window window = this.getWindow();
            window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
            window.setStatusBarColor(SkinCompatResources.getInstance().getColor(R.color.status_bar_color));
        }
    }

**Comment by ximsfei** [comment]
在oncreate方法里调用loadskin方法也是错误的

**Comment by Fantasy-Van** [comment]
大神，我的applyskin有问题吗？状态栏变色

**Comment by ximsfei** [comment]
1. 我觉得有可能是oncreate方法中的loadskin引起的
2. applyskin方法有问题，没有兼容国产ROM
