### ISSUE TITLE
divider如何换肤

### ISSUE THREAD

**Issue by CodeZsx** [ximsfei/Android-skin-support#122]
`<LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:divider="@drawable/line_gray"
                        android:showDividers="middle"
                        android:dividerPadding="@dimen/fab_margin"
                        android:orientation="vertical">`
通过设置divider添加的间隔线，如何去实现换肤呢

**Comment by CodeZsx** [comment]
line_gray.xml
`
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <size
        android:width="1px"
        android:height="1px"/>
    <solid
        android:color="@color/colorPatingLine"/>
</shape>
`

**Comment by CodeZsx** [comment]
我试过添加line_gray_night.xml,没有效果

**Comment by ximsfei** [comment]
可以参照自定义View换肤来扩展
