### ISSUE TITLE
是否能兼容下这个下拉刷新库 SmartRefreshLayout

### ISSUE THREAD

**Issue by gogogo1111** [ximsfei/Android-skin-support#124]
https://github.com/scwang90/SmartRefreshLayout

**Comment by lanshifu** [comment]
估计你是没有看作者自定义控件换肤那一段，或者看了没消化，给你参考一下吧
这个主要是Header  和  Footer 的兼容，以 ClassicsHeader 为例

/**
 * 支持换肤的header
 */
public class SkinCompactClassicsHeader extends ClassicsHeader implements SkinCompatSupportable {

    private int mAccentColor = 0;
    private int mPrimaryColor = 0;

    public SkinCompactClassicsHeader(Context context) {
        this(context, null);
    }

    public SkinCompactClassicsHeader(Context context, AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public SkinCompactClassicsHeader(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        mAccentColor = SkinCompatResources.getInstance().getColor(R.color.refresh_header_textcolor);
        mPrimaryColor = SkinCompatResources.getInstance().getColor(R.color.refresh_header_bg);
       //手动设置颜色
        applyColor();
    }

    //这个方法是设置header里面字体颜色
    @Override
    public ClassicsHeader setAccentColor(int accentColor) {
        return super.setAccentColor(accentColor);
    }

    //header背景，以此类推
    @Override
    public ClassicsHeader setPrimaryColor(int primaryColor) {
        return super.setPrimaryColor(primaryColor);
    }

    private void applyColor() {
        setAccentColor(mAccentColor);
        setPrimaryColor(mPrimaryColor);
    }

    @Override
    public void applySkin() {
        applyColor();
    }
}

如果还有哪个颜色需要换肤，查看源码中设置颜色的方法，重写，以此类推即可。

**Comment by gogogo1111** [comment]
感谢作者的回复，后来仔细看了自定义控件，已经实现了，再次感谢谢的demo。
