### ISSUE TITLE
drawableleft。。。。

### ISSUE THREAD

**Issue by yumengyang** [ximsfei/Android-skin-support#125]
是否支持drawableft这种图片更换，我看到例子中都是imageview设置图片的

**Comment by ximsfei** [comment]
可以的，看以下[这里](https://github.com/ximsfei/Android-skin-support/blob/master/demo/skin-app/src/main/java/com/ximsfei/skindemo/tab/fragment/LastFragment.java)

**Comment by yumengyang** [comment]
我记得上次用的是1.2.8版本的，结果换肤之后发现有些图片没有换掉，具体是不是drawableleft之类的忘记了，能不能说下不支持的还有哪些，或者已经支持的有哪些，麻烦作者了

**Comment by ximsfei** [comment]
默认支持的可以看[更新日志](https://github.com/ximsfei/Android-skin-support/blob/master/docs/ChangeLog.md)
