### ISSUE TITLE
无法在我的项目中添加依赖

### ISSUE THREAD

**Issue by yanerly** [ximsfei/Android-skin-support#126]
我在我的项目里面添加compile 'skin.support:skin-support:2.2.3'                   // skin-support basic widget
之后一直出现包冲突（主要是v7包，因为我的项目里面用到了ListViewCompat，这个只在v7:23.xxx有），无法依赖，请问是怎么回事？

**Comment by ximsfei** [comment]
最低支持到25.1.1
