### ISSUE TITLE
TextView.setText(@ResId int resId)  扩展的话无法重写,也无法获取到这个resId 怎么办?

### ISSUE THREAD

**Issue by bxhuhu** [ximsfei/Android-skin-support#127]
我想要实现替换文字的效果,xml的资源能拿到,但是在代码里面调用setText之后就获取不到,这个需要怎么解决?? 麻烦了哈.

**Comment by ximsfei** [comment]
如果是自定义View可以试试加个setTextResource(int resId)

**Comment by bxhuhu** [comment]
嗯  感谢作者的回复.  就是想以不侵入的方式去实现...  目前看来只有这个办法了,但是在kotlin的帮助下可以更好的使用扩展达到无侵入的去实现这个功能...虽然还是要调用扩展的方法
