### ISSUE TITLE
drawable目录下的文件无法更改颜色，用代码设置的控件无法更改颜色。。

### ISSUE THREAD

**Issue by zhhr1122** [ximsfei/Android-skin-support#130]
在drawable目录下，用shape绘制了一些图形，里面用了某些颜色，如

<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <corners android:radius="3dp"/>
    <stroke android:color="@color/colorBottom" android:width="0.5dp"/>
    <size android:height="40dp" />
    <size android:width="40dp" />
    <solid android:color="@color/colorBg" />
</shape>

绘制了圆角矩形，这样的地方用@color/colorBg无法更改主题颜色，其他写在layout中的布局都可以更改颜色。

还有，不知道是不是我集成的问题，我代码中去设置颜色的地方也无法更改颜色，只有XML中的颜色可以变

 textView.setTextColor(ContextCompat.getColor(context,R.color.colorPrimary));

这样设置，也不生效，希望作者看到回复下

**Comment by ximsfei** [comment]
需要把drawable下的xml文件也放到皮肤包里，
第二个问题可以看一下FAQ

**Comment by zhhr1122** [comment]
不是在皮肤包里哦，是以colors_night这样的形式加后缀，作为夜晚模式的应用内皮肤切换。也要和color一样给drawable下的shape加后缀么？

第二个问题已经解决，谢谢

**Comment by zhhr1122** [comment]
谢谢，问题已经解决了
