### ISSUE TITLE
ProgressBar使用progressDrawable属性自定义样式，报错

### ISSUE THREAD

**Issue by yy4556028** [ximsfei/Android-skin-support#131]
ProgressBar使用progressDrawable属性自定义样式，报错：
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/graphics/drawable/DrawableWrapper;

**Comment by ximsfei** [comment]
你用的appcompat库版本号是多少。

**Comment by howshea** [comment]
同样的问题，com.android.support:support-v4:27.1.0里没有android.support.v4.graphics.drawable.DrawableWrapper这个接口

**Comment by yaochangliang159** [comment]
这不就是我早上遇到的问题吗，，我的ProgressBar也使用了progressDrawable自定义样式。也是报错。。不过我把库的依赖版本由3.0降为2.2,3就好了
