### ISSUE TITLE
WindowManager 添加的view不能换肤吗

### ISSUE THREAD

**Issue by xiaolong125** [ximsfei/Android-skin-support#135]
大神你好，我在service里通过WindowManager添加的view不能更换资源？请问是什么原因呢？有什么办法解决吗

**Comment by ximsfei** [comment]
能换肤的，demo里有[例子](https://github.com/ximsfei/Android-skin-support/tree/master/demo/skin-app/src/main/java/com/ximsfei/skindemo/window)可以参考一下

**Comment by xiaolong125** [comment]
能留个QQ吗？我在WindowManager 里添加了一个listview，itemview的颜色不能替换
