### ISSUE TITLE
com.android.support:appcompat-v7 升级后一些属性被移除

### ISSUE THREAD

**Issue by AndyLuming** [ximsfei/Android-skin-support#136]
升级到 27 版本遇到一些问题
- R.color.abc_tint_switch_thumb not found
- android.support.v4.graphics.drawable.DrawableWrapper 类移到了 v7 包里
- Toolbar 颜色和  accentColor 颜色没有被替换

**Comment by ximsfei** [comment]
@AndyLuming 
Android studio 3.1.1 & sdk version 27已经适配完了。使用了最新的support library 27.1.1。
版本号已经升级到[3.0.0](https://github.com/ximsfei/Android-skin-support/blob/master/docs/ChangeLog.md#skin-support)了
* R.color.abc_tint_switch_thumb not found : [fixed](https://github.com/ximsfei/Android-skin-support/commit/c9f4d6d54f581745fa23415c1310ef17d4c5af44).
* android.support.v4.graphics.drawable.DrawableWrapper : [fixed](https://github.com/ximsfei/Android-skin-support/commit/c9f4d6d54f581745fa23415c1310ef17d4c5af44).
  android.support.v4.graphics.drawable.DrawableWrapper 这个类没有移到v7包中，v7包里以前就有DrawableWrapper。v4包里的这个类，改成WrappedDrawable了。


* Toolbar 颜色和 accentColor 颜色没有被替换 : 能否描述详细些。

**Comment by yumi0629** [comment]
Toolbar里边加自定义的布局，作者的框架是无法实现换肤的，需要自定义

**Comment by ximsfei** [comment]
emmm.能具体些嘛

**Comment by xingstarx** [comment]
代码设置toolbar.setTitleTextColor(ContextCompat.getColor(this, R.color.white));应用内换肤没有生效额，我有配置white_night的颜色值
