### ISSUE TITLE
为什么我使用你文件中的night.skin，监听里面也对应执行了成功的回调，但仍然没有任何效果

### ISSUE THREAD

**Issue by Serpit** [ximsfei/Android-skin-support#139]
为什么我使用你文件中的night.skin，监听里面也对应执行了成功的回调，但仍然没有任何效果

**Comment by ximsfei** [comment]
请使用自己的night.skin

**Comment by Serpit** [comment]
为什么会有所不同，是因为grale的原因吗？

**Comment by ximsfei** [comment]
每个人项目里用的资源是不一样的，所以夜间模式的资源也不一样

**Comment by Serpit** [comment]
所以是不是需要将一套原来项目同名的资源文件打包成一个.skin？或者说是要保证两套主题的资源文件要相同名字？

**Comment by ximsfei** [comment]
可以先研究下demo。
