### ISSUE TITLE
换肤框架性能优化

### ISSUE THREAD

**Issue by cgt1994** [ximsfei/Android-skin-support#141]
目前是把所有view替换成skincompatview之类的view 然后添加到集合mSkinHelpers中，换肤的时候，会遍历这个集合里的所有view，在大项目里 这样会不会比较耗性能，能不能控制添加到这个集合里的功能

**Comment by ximsfei** [comment]
emmm.
比较好性能表现在换肤的时候，执行时间比较久？

**Comment by cgt1994** [comment]
嗯 如果只有少数的view要换肤，但是目前是把所有集合里的view都重新applyskin一遍，这样会增加绘制时间吧，弄个属性作为开关会不会好一点

**Comment by ximsfei** [comment]
这样会增加接入的成本，对代码的侵入性比较的。
如果是这样，那么框架这边可以做个优化，换肤的时候只刷新当前页面皮肤，然后每返回一个页面，发现有换肤就刷新皮肤，没有换肤就什么都不做，这样能解决吗？

**Comment by cgt1994** [comment]
我也是在其他换肤框架里看到有这个开关，侵入性是无法避免的，但对单个view进行xml属性的设置还是比较方便的，当前页面刷新的逻辑也是可行的，大神做主吧，但我觉得对于大的项目，这个开关应该是有必要的，减少不必要的绘制。

**Comment by ximsfei** [comment]
对代码的侵入性降到最低，是框架设计最初的目标，我要坚持下去。不然就没必要新造个轮子了。。
只刷新一个页面的话，就相当于把大型项目，切割成一个个小项目了，应该可行，我把这点优化加到TODO离去吧。

**Comment by cgt1994** [comment]
好的~加油!
