### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cgt1994** [ximsfei/Android-skin-support#145]
当用这个框架初始化后，项目中原声的edittext不能在获得点击事件 不能弹出键盘

**Comment by ximsfei** [comment]
看一下[FAQ](https://github.com/ximsfei/Android-skin-support/blob/master/docs/FAQ.md#%E7%94%A8%E4%BA%86%E6%8D%A2%E8%82%A4%E6%A1%86%E6%9E%B6%E5%90%8E%E4%B8%BA%E4%BB%80%E4%B9%88%E9%A1%B9%E7%9B%AE%E9%87%8C%E7%9A%84buttoncheckbox%E7%AD%89%E7%AD%89%E9%83%BD%E6%97%A0%E6%B3%95%E7%82%B9%E5%87%BB%E4%BA%86%E5%BE%88%E5%A4%9Aui%E6%98%BE%E7%A4%BA%E4%B8%8D%E6%AD%A3%E5%B8%B8%E4%BA%86)

**Comment by realicing** [comment]
我也遇到这种问题，
但是主题没有问题：
    <style name="AppActionTheme" parent="Theme.AppCompat.Light.DarkActionBar">
通过
LayoutInflater.from(context).inflate(R.layout.include_input_comment, bottom);
方式添加EditText所在布局就会出现输入框无法获取焦点的问题，
而把R.layout.include_input_comment这个布局直接通过include的方式添加就没有问题

**Comment by Elaine666** [comment]
我也遇到同样问题，主题改了，但是EditText捕获不到事件
