### ISSUE TITLE
多支持一些控件的换肤功能~~~

### ISSUE THREAD

**Issue by hht10333** [ximsfei/Android-skin-support#15]
今天测试了一下radiobutton,发现style换肤和drawabletop等属性的换肤功能不支持,能不能添加一下,大神~~~嘿嘿

**Comment by ximsfei** [comment]
@hht10333 
https://github.com/ximsfei/Android-skin-support/blob/master/skin-app/src/main/res/layout/fragment_first.xml
关于style换肤, 这个布局文件里的TextView有实现例子, 可以参考一下。

关于drawableLeft drawableTop drawableRight drawableBottom这几个属性的换肤，已经在1.2.0版本上支持啦
:)
