### ISSUE TITLE
怎样动态设置Textview的颜色值？

### ISSUE THREAD

**Issue by guanxionghuai** [ximsfei/Android-skin-support#154]
怎样动态设置Textview的颜色值？
setCompoundDrawablesWithIntrinsicBounds这种方式设置drawleft无效

**Comment by ximsfei** [comment]
看README，看DEMO。

**Comment by guanxionghuai** [comment]
mText1.setCompoundDrawablesWithIntrinsicBounds(getResources().getDrawable(R.drawable.drawable_left_selector),
                getResources().getDrawable(R.drawable.drawable_top_selector),
                getResources().getDrawable(R.drawable.drawable_right_selector),
                getResources().getDrawable(R.drawable.drawable_bottom_selector));
你demo里面的这段也是无效的，无论是白天还是夜间 drawtop，left展示的都是黑色图片

**Comment by ximsfei** [comment]
https://github.com/ximsfei/Android-skin-support/blob/master/demo/skin-app/src/main/java/com/ximsfei/skindemo/tab/fragment/LastFragment.java

这个例子是用来表明这样是无法换肤的，你就没看到上面还有两个方法？
