### ISSUE TITLE
能否增加FlycoTabLayout该库的更换皮肤功能。

### ISSUE THREAD

**Issue by woitaylor** [ximsfei/Android-skin-support#16]
FlycoTabLayout的开源地址：https://github.com/H07000223/FlycoTabLayout
希望换肤的时候能够修改该库的选中状态和未选中状态下的字体颜色，背景颜色，以及指示条的颜色。
万分感谢。

**Comment by ximsfei** [comment]
@woitaylor 
FlycoTabLayout换肤支持包已经可以用啦, 不需要修改FlycoTabLayout的使用方式
只需要初始化一下[skin.support:flycotablayout](https://github.com/ximsfei/Android-skin-support/blob/master/ThirdPartSupport.md#h07000223flycotablayout)就可以实现换肤了。
如果使用过程用发现bug，希望能够及时反馈哈. : )

**Comment by Bleach1** [comment]
还需要什么设置吗 按照文档写的不好用，使用的这个com.flyco.tablayout.SegmentTabLayout

**Comment by Bleach1** [comment]
换肤成功后再次进入 又变回来了
