### ISSUE TITLE
InflateException

### ISSUE THREAD

**Issue by qinf1996** [ximsfei/Android-skin-support#160]
kkoui/com.mimikko.servant.activity.MyServantActivity}: android.view.InflateException: Binary XML file line #106: Binary XML file line #106: Error inflating class ProgressBar
--
506-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2855)
606-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2930)
706-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.app.ActivityThread.-wrap11(Unknown Source:0)
806-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1619)
906-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:105)
1006-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.os.Looper.loop(Looper.java:171)
1106-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6684)
1206-07 20:15:54.254 18725 18725 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
1306-07 20:15:54.254 18725 18725 E AndroidRuntime: at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
1406-07 20:15:54.254 18725 18725 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
1506-07 20:15:54.254 18725 18725 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #106: Binary XML file line #106: Error inflating class ProgressBar
1606-07 20:15:54.254 18725 18725 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #106: Error inflating class ProgressBar
1706-07 20:15:54.254 18725 18725 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable com.mimikko.mimikkoui:drawable/ui_servant_love_progress_custom with resource ID #0x7f08029a
1806-07 20:15:54.254 18725 18725 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ui_servant_love_progress_custom.xml from drawable resource ID #0x7f08029a
1906-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:805)
2006-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:619)
2106-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:305)
2206-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.content.res.Resources.getDrawableForDensity(Resources.java:890)
2306-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.content.res.Resources.getDrawable(Resources.java:832)
2406-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.content.res.Resources.getDrawable(Resources.java:807)
2506-07 20:15:54.254 18725 18725 E AndroidRuntime: at com.mimikko.common.kb.a.D(SkinCompatResources.java:143)
2606-07 20:15:54.254 18725 18725 E AndroidRuntime: at com.mimikko.common.kb.a.E(SkinCompatResources.java:160)
2706-07 20:15:54.254 18725 18725 E AndroidRuntime: at com.mimikko.common.kb.a.G(SkinCompatResources.java:198)
2806-07 20:15:54.254 18725 18725 E AndroidRuntime: at skin.support.widget.g.applySkin(SkinCompatProgressBarHelper.java:143)
2906-07 20:15:54.254 18725 18725 E AndroidRuntime: at skin.support.widget.g.loadFromAttributes(SkinCompatProgressBarHelper.java:53)
3006-07 20:15:54.254 18725 18725 E AndroidRuntime: at skin.support.widget.SkinCompatProgressBar.<init>(SkinCompatProgressBar.java:25)
3106-07 20:15:54.254 18725 18725 E AndroidRuntime: at skin.support.widget.SkinCompatProgressBar.<init>(SkinCompatProgressBar.java:19)
3206-07 20:15:54.254 18725 18725 E AndroidRuntime: at skin.support.app.SkinCompatViewInflater.createViewFromFV(SkinCompatViewInflater.java:188)
3306-07 20:15:54.254 18725 18725 E AndroidRuntime: at skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:91)
3406-07 20:15:54.254 18725 18725 E AndroidRuntime: at skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:58)
3506-07 20:15:54.254 18725 18725 E AndroidRuntime: at skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:35)
3606-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
3706-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
3806-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
3906-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
4006-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
4106-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
4206-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
4306-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
4406-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
4506-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
4606-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
4706-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
4806-07 20:15:54.254 18725 18725 E AndroidRuntime: at com.mimikko.mimikkoui.ui_toolkit_library.view.base.BaseSkinActivity.setContentView(BaseSkinActivity.java:71)
4906-07 20:15:54.254 18725 18725 E AndroidRuntime: at com.mimikko.mimikkoui.ui_toolkit_library.view.base.BaseSkinActivity.onCreate(BaseSkinActivity.java:49)
5006-07 20:15:54.254 18725 18725 E AndroidRuntime: at com.mimikko.mimikkoui.ui_toolkit_library.view.base.MvpActivity.onCreate(MvpActivity.java:19)
5106-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:7057)
5206-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
5306-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2808)
5406-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2930)
5506-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.app.ActivityThread.-wrap11(Unknown Source:0)
5606-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1619)
5706-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:105)
5806-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.os.Looper.loop(Looper.java:171)
5906-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6684)
6006-07 20:15:54.254 18725 18725 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
6106-07 20:15:54.254 18725 18725 E AndroidRuntime: at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
6206-07 20:15:54.254 18725 18725 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
6306-07 20:15:54.254 18725 18725 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
6406-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.util.ContainerHelpers.binarySearch(ContainerHelpers.java:28)
6506-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.util.SparseArray.get(SparseArray.java:113)
6606-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.util.SparseArray.get(SparseArray.java:104)
6706-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.content.res.MiuiResourcesImpl.loadOverlayDrawable(MiuiResourcesImpl.java:169)
6806-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.content.res.MiuiResources.loadOverlayDrawable(MiuiResources.java:166)
6906-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.content.res.ResourcesImpl.createFromXmlForDensity(ResourcesImpl.java:1412)
7006-07 20:15:54.254 18725 18725 E AndroidRuntime: at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:790)
7106-07 20:15:54.254 18725 18725 E AndroidRuntime: ... 43 more

**Comment by zksyp** [comment]
遇到同样的问题=-=想知道题主解决了吗。。。
