### ISSUE TITLE
自定义tablayout 修改tabbackground 无效

### ISSUE THREAD

**Issue by MoMask** [ximsfei/Android-skin-support#162]
public class SkinTablayout extends TabLayout implements SkinCompatSupportable {
    private int skinTabBackGround = INVALID_ID;
    private SkinCompatBackgroundHelper mBackgroundTintHelper;

    public SkinTablayout(Context context) {
        this(context, null);
    }

    public SkinTablayout(Context context, AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public SkinTablayout(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        obtainAttributes(context, attrs);
        mBackgroundTintHelper = new SkinCompatBackgroundHelper(this);
        mBackgroundTintHelper.loadFromAttributes(attrs, defStyleAttr);

    }

    private void obtainAttributes(Context context, AttributeSet attrs) {
        TypedArray ta = context.obtainStyledAttributes(attrs, R.styleable.TabLayout);
        skinTabBackGround = ta.getResourceId(R.styleable.TabLayout_tabBackground, SkinCompatHelper.INVALID_ID);
        skinTabBackGround = SkinCompatHelper.checkResourceId(skinTabBackGround);
        ta.recycle();
        applySegmentTabLayoutResources();
    }

    private void applySegmentTabLayoutResources() {
        if (skinTabBackGround != SkinCompatHelper.INVALID_ID) {
            setTabBackGround(skinTabBackGround);
        }
    }

    @Override
    public void setBackgroundResource(@DrawableRes int resId) {
        super.setBackgroundResource(resId);
        if (mBackgroundTintHelper != null) {
            mBackgroundTintHelper.onSetBackgroundResource(resId);
        }
    }

    @Override
    public void applySkin() {
        applySegmentTabLayoutResources();
        if (mBackgroundTintHelper != null) {
            mBackgroundTintHelper.applySkin();
        }
    }

    private void setTabBackGround(int color) {
        try {
            Field barColor = SegmentTabLayout.class.getDeclaredField("mTabBackgroundResId");
            barColor.setAccessible(true);
            barColor.set(this, color);
            invalidate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by ximsfei** [comment]
```java
private void applySegmentTabLayoutResources() {
    if (skinTabBackGround != SkinCompatHelper.INVALID_ID) {
        setTabBackGround(skinTabBackGround);
    }
}
```
这段代码不对

**Comment by lovelyYakir** [comment]
@ximsfei mTabBackgroundResId 这个属性在tablayout是一个int 值，我在xml中传入的是一个drawable。和color对不上。
