### ISSUE TITLE
通过SpannableString处理字符串无法进行换肤。

### ISSUE THREAD

**Issue by MoMask** [ximsfei/Android-skin-support#163]
`SpannableString colorSpan = new SpannableString("点击联系在线客服");
        colorSpan.setSpan(new ClickableSpan() {
            @RequiresApi(api = Build.VERSION_CODES.M)
            @Override
            public void updateDrawState(TextPaint ds) {
                super.updateDrawState(ds);
                ds.setColor(getColor(R.color.colorPrimary));
                ds.setUnderlineText(false);
                ds.clearShadowLayer();
            }

            @Override
            public void onClick(View widget) {
                ActivityUtil.gotoCustomerService();
            }
        }, 0, colorSpan.length(), Spanned.SPAN_INCLUSIVE_EXCLUSIVE);`

**Comment by ximsfei** [comment]
可以在applySkin方法中自行实现
