### ISSUE TITLE
没有提供API判断当前是否已经换肤了

### ISSUE THREAD

**Issue by tomUp** [ximsfei/Android-skin-support#165]
hello，ximsfei。

**疑问**：
查找了下贵框架的demo，是通过SwitchPreference记录。
没有找到相关API可以判断是否已经换肤，还有当前是哪种换肤？

**背景**：
我第一次换肤完成之后，再次打开APP，
不能知道我是否已经换肤了，而且是哪种换肤？
是不是要自己去做这个缓存记录？

**Comment by ximsfei** [comment]
不需要自己缓存，loadSkin方法会默认使用上次的皮肤。SkinPreference中有api。

**Comment by tomUp** [comment]
@ximsfei 

以下代码可以？

	    // 获取换肤方式
	    int skinStrategy = SkinPreference.getInstance().getSkinStrategy();
        switch (skinStrategy) {
            case SkinCompatManager.SKIN_LOADER_STRATEGY_NONE:
                // 未换肤
                break;
            case SkinCompatManager.SKIN_LOADER_STRATEGY_ASSETS:
            case SkinCompatManager.SKIN_LOADER_STRATEGY_BUILD_IN:
            case SkinCompatManager.SKIN_LOADER_STRATEGY_PREFIX_BUILD_IN:
                // 换肤
                break;
        }

**Comment by ximsfei** [comment]
不可以

**Comment by tomUp** [comment]
所以后续可以有一个API提供去判断？

**Comment by tomUp** [comment]
@ximsfei 

那后续可以考虑增加一个API来准确判断？毕竟这种场景还是很常见的。

**Comment by ximsfei** [comment]
还有一个方法，可以返回当前的皮肤名

**Comment by tomUp** [comment]
@ximsfei 

通过getSkinName()和getSkinStrategy()一起判断？

**Comment by ximsfei** [comment]
是的

**Comment by minorlai** [comment]
应用内换肤这么判断是否已经换肤呢？getSkinName()是为空的

**Comment by minorlai** [comment]
经过研究，点击换肤，getSkinName()是空的，下一次启动才有值
