### ISSUE TITLE
不支持设置底部导航栏的颜色（navigationBarColor）

### ISSUE THREAD

**Issue by JasonLian2020** [ximsfei/Android-skin-support#166]
@ximsfei 

一、style里面设置

    <item name="android:navigationBarColor">@color/navigationBarColor</item>

二、color里面

    // res里面values文件夹下colors.xml
    <color name="navigationBarColor">#FF4081</color>

    // res-night里面values文件夹下colors.xml
    <color name="navigationBarColor_night">#000000</color>

三、通过应用内换肤

    SkinCompatManager.getInstance().loadSkin("night", null, SkinCompatManager.SKIN_LOADER_STRATEGY_BUILD_IN);

希望可以支持。

**Comment by ximsfei** [comment]
可以在applySkin方法中自行扩展
