### ISSUE TITLE
application 中初始化   installLayoutFactory(application) 的问题

### ISSUE THREAD

**Issue by 7280423** [ximsfei/Android-skin-support#167]
在application中 初始化的时候会调用installLayoutFactory(application);  这样如果有插件且插件里面也要用到 LayoutInflaterCompat.setFactory(layoutInflater, getSkinDelegate(context)); 因为这个方法内部有标志位，会导致失败（因为context的原因），看是否可以考虑在application中不需要installLayoutFactory(application) 是否会有影响？
如果真的没有影响，还麻烦大神更新下依赖库喽。。谢谢了，辛苦大牛！

 private SkinActivityLifecycle(Application application) {
        application.registerActivityLifecycleCallbacks(this);
        installLayoutFactory(application);
        SkinCompatManager.getInstance().addObserver(getObserver(application));
    }

**Comment by ximsfei** [comment]
有影响，去掉之后，通过application context创建的view，就不支持换肤了。
插件中可以新建一个LayoutInflater：LayoutInflater.from(context).cloneInContext();
