### ISSUE TITLE
版本v2.2.3 可能存在Activity内存泄漏问题

### ISSUE THREAD

**Issue by jarlen** [ximsfei/Android-skin-support#168]
SkinActivityLifecycle：
private SkinObserver getObserver(final Context context) {
......................
 if (observer == null) {
            observer = new WeakSkinObserver(context, this);//解决可能存在的内存泄漏问题
 }
...........................
}

`/**
 * 解决内存泄漏问题
 * Created by jarlen on 2018/6/20.
 */

public class WeakSkinObserver implements SkinObserver {

    private WeakReference<Context> contextWeakReference;
    private SkinActivityLifecycle lifecycle;

    public WeakSkinObserver(Context context, SkinActivityLifecycle lifecycle) {
        contextWeakReference = new WeakReference<>(context);
        this.lifecycle = lifecycle;}

    @Override
    public void updateSkin(SkinObservable observable, Object o) {
        Context context = contextWeakReference.get();
        if (context == null || (context instanceof Activity && ((Activity) context).isFinishing())) {
            return;
        }

        if (context instanceof Activity && lifecycle.isContextSkinEnable(context)) {
            lifecycle.updateStatusBarColor((Activity) context);
            lifecycle.updateWindowBackground((Activity) context);
        }
        lifecycle.getSkinDelegate(context).applySkin();if (context instanceof SkinCompatSupportable) {
            ((SkinCompatSupportable) context).applySkin();
        }
    }
}`

**Comment by pudao2010** [comment]
focus
