### ISSUE TITLE
android.content.res.Resources$NotFoundException是否跟Android-skin-support相关呢

### ISSUE THREAD

**Issue by uncleleonfan** [ximsfei/Android-skin-support#169]
main}android.view.InflateException: Binary XML file line #17: Error inflating class ImageView at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713) at android.view.LayoutInflater.inflate(LayoutInflater.java:469) at android.view.LayoutInflater.inflate(LayoutInflater.java:397) at android.support.v7.widget.ActionBarContextView.initForMode(ActionBarContextView.java:162) at android.support.v7.app.AppCompatDelegateImplV9.startSupportActionModeFromWindow(AppCompatDelegateImplV9.java:831) at android.support.v7.app.AppCompatDelegateImplV9.startSupportActionMode(AppCompatDelegateImplV9.java:712) at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.startAsSupportActionMode(AppCompatDelegateImplV14.java:291) at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.onWindowStartingActionMode(AppCompatDelegateImplV14.java:274) at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionMode(PhoneWindow.java:2378) at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionModeForChild(PhoneWindow.java:2365) at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665) at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665) at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665) at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665) at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665) at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665) at android.view.View.startActionMode(View.java:4536) at android.widget.Editor.startSelectionActionMode(Editor.java:1551) at android.widget.Editor.performLongClick(Editor.java:859) at android.widget.TextView.performLongClick(TextView.java:8479) at android.view.View$CheckForLongPress.run(View.java:18410) at android.os.Handler.handleCallback(Handler.java:733) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:149) at android.app.ActivityThread.main(ActivityThread.java:5061) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:515) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610) at dalvik.system.NativeStart.main(Native Method) Caused by: android.content.res.Resources$NotFoundException: File r/g/p.xml from drawable resource ID #0x7f020013 at android.content.res.Resources.loadDrawable(Resources.java:2097) at android.content.res.Resources.getDrawable(Resources.java:700) at android.support.v7.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:128) at android.support.v7.widget.TintResources.getDrawable(TintResources.java:45) at skin.support.content.res.c.i(SkinCompatResources.java:180) at skin.support.content.res.c.j(SkinCompatResources.java:214) at skin.support.content.res.c.d(SkinCompatResources.java:252) at skin.support.widget.d.a(SkinCompatImageHelper.java:46) at skin.support.widget.d.a(SkinCompatImageHelper.java:35) at skin.support.widget.SkinCompatImageView.<init>(SkinCompatImageView.java:30) at skin.support.widget.SkinCompatImageView.<init>(SkinCompatImageView.java:21) at skin.support.app.c.c(SkinCompatViewInflater.java:149) at skin.support.app.c.a(SkinCompatViewInflater.java:91) at skin.support.app.b.a(SkinCompatDelegate.java:58) at skin.support.app.b.onCreateView(SkinCompatDelegate.java:35) at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47) at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:169) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684) ... 29 more Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933) at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877) at android.content.res.Resources.loadDrawable(Resources.java:2093) ... 46 more

**Comment by uncleleonfan** [comment]
主要是资源没找到
Caused by: android.content.res.Resources$NotFoundException: File r/g/p.xml from drawable resource ID #0x7f020013 at android.content.res.Resources.loadDrawable(Resources.java:2097) at

**Comment by zksyp** [comment]
遇到同样的问题。。想知道题主解决了吗。。。

**Comment by chrissen0814** [comment]
混淆了，我昨天测试的时候，如果只是把混淆打开是没有问题的，但是如果把shrinkResources 和 zipAlignEnabled打开的话就会闪退。

**Comment by ximsfei** [comment]
@chrissen0814 那就对了，资源不能混淆。shrinkResources会删除没有被引用到的资源内容，而皮肤资源正常情况下打包时是不会被引用到的，换肤的时候才会用到，所以换肤的时候就崩溃了

**Comment by chrissen0814** [comment]
测试的时候我也是这样想的，但是奇怪的地方在于：由于我是使用了组件化来开发，总共分为module-user, module-other两个module，对于other模块里面是没有问题的，但是如果跳转到user里面部分的页面就会出问题。我自己测试时发现，只有当进入到某一个特定的页面才会报错，其他的情况没有发现问题。不知道是什么问题。

**Comment by uncleleonfan** [comment]
我的确实是资源混淆的原因，后面指定部分资源不进行混淆就好了
