### ISSUE TITLE
自定义AppCompatCheckBox继承SkinCompatCheckBox的时候，设置setTextAppearance时setTextSize不起效果

### ISSUE THREAD

**Issue by guanxionghuai** [ximsfei/Android-skin-support#172]
自定义AppCompatCheckBox（AppCompatRadioButton）继承SkinCompatCheckBox（SkinCompatRadioButton）的时候，设置setTextAppearance时setTextSize不起效果

**Comment by ximsfei** [comment]
可以在setTextAppearance中设置text size.
