### ISSUE TITLE
shape相关

### ISSUE THREAD

**Issue by xfhy** [ximsfei/Android-skin-support#173]
大佬,请教一个问题,我现在皮肤颜色值是从网络加载的,需要动态修改本地的颜色值,但是shape好像不支持..
我是在代码中动态修改colorAccent颜色的
SkinCompatUserThemeManager.get().addColorState(R.color.colorAccent, "#40FF6D")
```
<shape xmlns:android="http://schemas.android.com/apk/res/android"
       android:shape="rectangle">

    <corners android:radius="2dp"/>

    <solid android:color="@color/colorAccent"/>
</shape>
```

**Comment by ximsfei** [comment]
SkinCompatUserThemeManager.get().addColorState(R.color.colorAccent, "#40FF6D")
这个接口是针对<selector />类型的哈。

**Comment by xfhy** [comment]
对,我改了R.color.colorAccent之后,shape里面用到R.color.colorAccent还是没有变色,,,大佬,有何妙招吗?洗耳恭听

**Comment by wsygwg** [comment]
这个问题在api 'skin.support:skin-support:3.1.0-beta1'也存在...我的圆角背景都悲剧了...

**Comment by githubxiaoou** [comment]
@xfhy 楼主的问题最后怎么解决的，我也遇到同样的需求

**Comment by xfhy** [comment]
> @xfhy 楼主的问题最后怎么解决的，我也遇到同样的需求

几年了,有点记不清了,好像是这样的: 获取该View的Background,一般是shape类型的,然后动态设置这个shape的颜色
