### ISSUE TITLE
可以替换文本吗？

### ISSUE THREAD

**Issue by shenbengit** [ximsfei/Android-skin-support#175]
![image](https://user-images.githubusercontent.com/24364422/42754825-9807540c-8928-11e8-9507-162b89e66a0d.png)
可以通过打包生成xx.skin文件方式，替换strings.xml文件吗？通过此框架，还有别的方式可以达到替换的目的吗？

**Comment by ximsfei** [comment]
可以。不过需要自己扩展

**Comment by shenbengit** [comment]
能说说思路吗？打包的xx.skin文件里没有strings.xml文件。

**Comment by ximsfei** [comment]
参照自定义view换肤实现

**Comment by MyLifeMyTravel** [comment]
@shenbengit 参考 SkinCompatResources.java 扩展
