### ISSUE TITLE
可以在library创建夜间资源，让app或者其他Library引用吗？

### ISSUE THREAD

**Issue by ZhangKuixun** [ximsfei/Android-skin-support#182]
这是专放置资源文件的library：

> public_res：
> > res
> > > drawable
> > > values

> > res-night
> > > drawable
> > > mipmap-xxhdpi
> > > values

可以在app包下面的build.gradle（implementation project(':public_res')）引用使用吗？

**Comment by ximsfei** [comment]
可以。

**Comment by ZhangKuixun** [comment]
引用不到啊。我测试了一下失败，然后又把res-night放回app/res下面去了

**Comment by ximsfei** [comment]
放在lib里，和放在app里，打包成apk是一样的

**Comment by ZhangKuixun** [comment]
我用你的dome测试，失败

**Comment by ZhangKuixun** [comment]
创建个分支你看一下？

**Comment by ximsfei** [comment]
可以

**Comment by ZhangKuixun** [comment]
推不上去，给个权限吧

**Comment by ximsfei** [comment]
可以fork一个仓库

**Comment by ZhangKuixun** [comment]
是不行哈？
