### ISSUE TITLE
是否增加 autolayout 的三个布局控件的兼容 急~!~

### ISSUE THREAD

**Issue by MinchinWang** [ximsfei/Android-skin-support#19]
1.AutoLinearLayout
2.AutoRelativeLayout
3.AutoFrameLayout
开源库地址:https://github.com/hongyangAndroid/AndroidAutoLayout
谢谢~~

**Comment by ximsfei** [comment]
AndroidAutoLayout换肤支持包已经可以用啦, 不需要修改AndroidAutoLayout的使用方式
只需要初始化一下[skin.support:androidautolayout](https://github.com/ximsfei/Android-skin-support/blob/master/ThirdPartSupport.md#hongyangandroidandroidautolayout)就可以实现换肤了。:)
