### ISSUE TITLE
关于color引用的疑惑。

### ISSUE THREAD

**Issue by YummyLau** [ximsfei/Android-skin-support#190]
你好，看了下demo，想请教下。
一个shape引用一个color，在皮肤包中单独修改该color引用的值，为何不生效呢？ 
是否需要该shape也复制一份，那原来shape引用的color就没有意义哈。

**Comment by ximsfei** [comment]
是的，需要一份shape，框架是根据资源名解析的，不会解析xml文件内容

**Comment by YummyLau** [comment]
嗯嗯。感谢。
