### ISSUE TITLE
请问一下，是否在代码里动态调用的话就无法换肤？

### ISSUE THREAD

**Issue by jingzz1** [ximsfei/Android-skin-support#191]
比如 ContextCompat.getColor(this, R.id.colorAccent); 这种调用颜色的方法，换肤后获取到的依然是colorAccent的颜色？

**Comment by ximsfei** [comment]
看一下faq，翻一下issues

**Comment by YummyLau** [comment]
@jingzz1 SkinCompatResources.getColor(context, color);
