### ISSUE TITLE
自定义属性的eg访问不了了，demo中有什么可以参考的？

### ISSUE THREAD

**Issue by Fantasy-Van** [ximsfei/Android-skin-support#194]
需要换肤自定义属性

// 需要换肤AutoCompleteTextView的R.attr.popupBackground属性

eg: SkinCompatAutoCompleteTextView

**Comment by ximsfei** [comment]
自定义属性的eg访问不了了?没太理解什么意思

**Comment by Fantasy-Van** [comment]
自定义属性SkinCompatAutoCompleteTextView的这个例子链接404访问不了了，有其他可以参考的吗？

原文：
需要换肤自定义属性
// 需要换肤AutoCompleteTextView的R.attr.popupBackground属性
eg: SkinCompatAutoCompleteTextView

**Comment by ximsfei** [comment]
嗯，skin开头的类，都在该库的源码中可以找到，我更新一下readme文件

**Comment by Fantasy-Van** [comment]
看到了，感谢，如今这样的大佬已经不多了。

**Comment by ximsfei** [comment]
哈哈，这个项目从17年1月开始做了一年半了，再忙都会坚持下去，感谢支持。

**Comment by Fantasy-Van** [comment]
真正热爱技术的人，做项目并这么多人在用肯定是一种极大的乐趣，像大佬学习。
