### ISSUE TITLE
加载的优先级问题

### ISSUE THREAD

**Issue by yurenmatou** [ximsfei/Android-skin-support#195]
资源加载优先级: 用户自定义颜色值-加载策略中的资源-皮肤包资源-应用资源。
如何理解这句话的优先级，可否给出案例。
比如
1、《自定义的颜色值》，参考ColorPickerActivity
2、《加载策略类》似CustomSDCardLoader，然后  SkinCompatManager.getInstance().loadSkin("night.skin", null, CustomSDCardLoader.SKIN_LOADER_STRATEGY_SDCARD);这样调用；
3、《皮肤包资源》就是通过自定义生成的apk包:
4、《应用资源》很好理解，应用本身的皮肤包；

问题1：这几个的优先级是从高到低吗？
问题2：加载策略中的是外置卡的吗？
问题3：皮肤包资源，是不是指assets/skins/下面的？

问题4：类似网易云更换背景，然后字体颜色更改；
假如之前已经设置了夜间模式，
这个时候我需要清除一次吗？
然后结合自定义颜色+更换背景，这样对吗？

**Comment by ximsfei** [comment]
1. 是的，从高到低
2. 无所谓内置还是外置，只要有值返回
3. 皮肤包资源是指应用内换肤或者插件式换肤，无所谓哪个目录
4. 不知道这个问题我有没有理解错，如果要保留夜间模式，那就继续修改背景，继续修改字体颜色。如果不需要保留夜间模式则清除，再结合自定义颜色+背景

**Comment by yurenmatou** [comment]
@ximsfei ok，明白。我想再深入一段时间，可以玩得更好了。
