### ISSUE TITLE
是否有boolean标记当前页面是否应用了skin

### ISSUE THREAD

**Issue by CharlesLCY** [ximsfei/Android-skin-support#196]
请问大佬，loadSkin()以后，怎么判断当前app是否已经切换主题了，比如白天黑夜的toggle切换，是否有boolean标记？

**Comment by ximsfei** [comment]
有的，sp里存了皮肤名，皮肤策略

**Comment by CharlesLCY** [comment]
demo里面有sp相关的示例在哪个文件呀
