### ISSUE TITLE
colors.xml文件中定义颜色引用导致的问题

### ISSUE THREAD

**Issue by lzhAndroid** [ximsfei/Android-skin-support#197]
在项目colors.xml中定义

```
<color name="b1">#e6252a</color>
<color name="b2">@color/b1</color>
```
在皮肤colors.xml中定义

```
<color name="b3">#e26542</color>
<color name="b2">@color/b3</color>
```

项目目录下b2使用的是颜色的引用的时候，皮肤目录中设置的b2色值不生效。
怀疑是项目目录下拿到的引用地址，在皮肤目录中不存在，导致返回0

**Comment by lzhAndroid** [comment]
通过SkinCompatResources.getColorStateList直接获取@color/b2能拿到正确的颜色，但是写在TextView的xml里android:textColor就没有效果。debug了一下SkinCompatTextHelper，暂时没找到问题出在哪里

**Comment by ximsfei** [comment]
@lzhAndroid color值不能引用，在xml中使用@color/b2，框架在解析出来的颜色值名称为b1，所以换肤的时候，就没效果。

**Comment by lzhAndroid** [comment]
恩，是这样的，通过DOCTYPE的定义解决了这个需求，谢谢了。

**Comment by zcm-hu** [comment]
楼主怎么解决的

**Comment by zhuangzhitu** [comment]
所以color值不能引用其他值吗？那么工程存在色板的问题如何解决呀？
