### ISSUE TITLE
fragment 间进行切换时，之前被换肤了的fragment又恢复到初始的皮肤

### ISSUE THREAD

**Issue by 1214658495** [ximsfei/Android-skin-support#198]
大神您好，请教一下。我在fragment里使用的是radio button自定义控件。当在fragment界面时，radio button可以实现实时切换皮肤，但如果fragment间做了切换，fragment里的radio button自定义控件在又加载了初始化的皮肤。感觉是不是在oncreat里还是在加载初始皮肤。不知道大神有遇到过吗？非常感谢

**Comment by ximsfei** [comment]
不能在oncreate里加载皮肤

**Comment by 1214658495** [comment]
谢谢大神的回复。1、我这边的代码确实是在on create view 里加载的。2、如果只需要加载一次，但我的fragment 做切换时 还是会重新 on create view 。3、还有个奇怪的地方：fragment 做切换时，皮肤被初始化了，但在屏幕做旋转时又是可以正常换肤的。

如下为我的fragment换肤
   @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup
            container, @Nullable Bundle savedInstanceState) {
        Log.e(TAG, "onCreateView: ");
        View view = inflater.inflate(R.layout.fragment_playback, container, false);
        listLoadingView = view.findViewById(R.id.listLoadingView);
        unbinder = ButterKnife.bind(this, view);
        int bydTheme = getResources().getConfiguration().byd_theme;
        changeSkin(bydTheme); 此处换肤

**Comment by ximsfei** [comment]
皮肤只需要加载一次，不要在onCreateView中调用
