### ISSUE TITLE
关于应用在生产环境中的一些疑问

### ISSUE THREAD

**Issue by zongyao2** [ximsfei/Android-skin-support#2]
如果线上版本，已集成该库，用户也下载了其它颜色进行换肤。在接下的新版本中，默认主题颜色，增加了一个新的 color 值，那线上版本的用户下载的其它颜色皮肤，怎样同步新版本中的新 color 值？只能让线上用户重新下载那些皮肤吗？

**Comment by ximsfei** [comment]
@zongyao2 
1. 首先确定这个新增的color值是否需要换肤,  有些值如果默认主题和其他皮肤中是一样的那就不需要管了, 在皮肤中不存在会使用默认值.
2. 可以为你的皮肤配置一套版本规则, 例如设置versionCode等. 在应用启动的时候去判断一下当前皮肤是否需要更新.
3. 如果你的应用只增加了一个color值，是否需要重新发一个新版本. 我有一些建议, 如果你的皮肤中有新的color, 你可以选择增量更新[bsdiff](http://www.daemonology.net/bsdiff/), 也可以自己去扩展换肤框架适配你们自己的需求, 增加颜色值下发功能, 通过java代码去设置等. 也可以在wifi环境下自动下载皮肤.

**Comment by zongyao2** [comment]
@ximsfei 

谢谢你的解答和建议。
versionCode、增量更新，这些都是比较不错的方式，最主要还是看具体需求再定好对应的一套规则。不过到时候，可能会有个担心，就是每次新增颜色值，心里应该都会咯噔一下，哈哈~
抛开上面，这个库还是很赞的，希望继续维护优化。

**Comment by ximsfei** [comment]
@zongyao2 
感谢你的支持
一般应用开发过程中，UI都会给出[一套规范](http://www.25xt.com/appdesign/12385.html)，例如整个应用中有多少种不同的字体颜色，有多少种不同的背景颜色，什么场景下用哪个色值等。在这个基础上，结合合理的命名规范。不会经常去增加color值的。

**Comment by zongyao2** [comment]
@ximsfei 

这个规范，之前看过，确实详细规范。但很多时候，大部分公司并不会这么做的，有时只能自己去设计稿取色 -_-
