### ISSUE TITLE
关于zip方式换肤的疑惑

### ISSUE THREAD

**Issue by KarlLargerFeld** [ximsfei/Android-skin-support#200]
通过zip方式下载并解析文件后，如何替换selector、shape、vector等xml文件呢？

**Comment by ximsfei** [comment]
无法替换xml文件

**Comment by KarlLargerFeld** [comment]
那 selector，shape 如何实现换肤呢？ 用zip的方式。(试过替换颜色代码，但没有效果)

**Comment by ximsfei** [comment]
暂时还不支持

**Comment by ximsfei** [comment]
可以试试直接创建对应的Drawable

**Comment by ximsfei** [comment]
或者结合应用内换肤

**Comment by KarlLargerFeld** [comment]
嗯，感谢您的回复，这边通过获取服务器端配置的json文件，在自定义策略的getDrawable方法中，解析对应json，创建对应的drawable子类并返回，目前已实现selector的换肤。

**Comment by lhholylight** [comment]
> 嗯，感谢您的回复，这边通过获取服务器端配置的json文件，在自定义策略的getDrawable方法中，解析对应json，创建对应的drawable子类并返回，目前已实现selector的换肤。



> 嗯，感谢您的回复，这边通过获取服务器端配置的json文件，在自定义策略的getDrawable方法中，解析对应json，创建对应的drawable子类并返回，目前已实现selector的换肤。

你好，能具体说下你们的方案吗
