### ISSUE TITLE
自定义View设置Paint Corlor

### ISSUE THREAD

**Issue by chrissen0814** [ximsfei/Android-skin-support#203]
自定义View需要通过Paint来设置颜色，如何让它支持换肤

**Comment by ximsfei** [comment]
在applySkin方法中更新color值，刷新UI

**Comment by ximsfei** [comment]
在applySkin方法中更新color值，刷新UI

**Comment by chrissen0814** [comment]
测试了一下是可以的。
不过现在又有一个问题，就是再加载的时候它的颜色又会变成初始化的样子。
我想问您：有没有什么办法能够获取到当前换肤的颜色值（比如我改变了colorPrimary的色值，我想在初始化和applySkin中直接设置更换的颜色值）。不知道有没有相关的api

**Comment by ximsfei** [comment]
SkinCompatResources.java看看这个类
