### ISSUE TITLE
初始化完成后，原项目中按钮字体英文下变粗变大写。

### ISSUE THREAD

**Issue by Fantasy-Van** [ximsfei/Android-skin-support#204]
大神，换肤框架初始化完成，切换为compat主题后，原项目中按钮字体英文下变粗变大写，这块有没有统一控制的地方，我想还原回去，请问知道哪里的问题吗？谢谢。

**Comment by ximsfei** [comment]
很大的原因是主题的问题。
可以贴一下项目里使用的主题。
