### ISSUE TITLE
ManiApplication中loadSkin会导致崩溃的问题

### ISSUE THREAD

**Issue by Jenan5** [ximsfei/Android-skin-support#206]
上周发的app里面，部分机型loadSkin的时候卡顿，发现是 在主进程中，loadSkin的，然后就一出来，放在MainApplication 的 onCreate()里面，今天有同事代码合并后，换肤崩溃了，但是他并没有修改换肤的逻辑，loadSkin 再次放到 主进程中，又可以了，请问针对这个问题，能给出一些合理的建议吗，谢谢了

**Comment by ximsfei** [comment]
具体的崩溃日志有吗？还有只在UI进程中初始化换肤就可以了。
