### ISSUE TITLE
切换到黑色皮肤，有些控件View没有给他设置背景颜色的也变黑了

### ISSUE THREAD

**Issue by finddreams** [ximsfei/Android-skin-support#21]
比如说ViewPager，PagerSlidingTabStrip也变黑了。是自定义的View有这样的问题，自定义ViewPager，自定义的ScrollGridView这些。

**Comment by ximsfei** [comment]
@finddreams 
如果可以的话，希望能够描述的详细一点 :)
从现在的描述中看，首先ViewPager, PagerSlidingTabStrip这些暂时不会换肤，除非 父View参与了换肤  :)

**Comment by finddreams** [comment]
public class ScrollGridView extends GridView  和public class PagingViewPager extends ViewPager 这两个自定义的内容，本没有设置黑色皮肤的，但在红米3 6.0的系统上，在切换成黑色皮肤后，偶尔会成黑色。在android4.4和5.1上没有发现这个问题，不知道是不是缓存的原因，还要在看看。
