### ISSUE TITLE
Android P 无法使用@hide Api

### ISSUE THREAD

**Issue by yumi0629** [ximsfei/Android-skin-support#214]
您好，最新的Google开发者大会中，Google提到Android P 将无法使用@hide Api。
而您的这套框架中，举个例子，SkinCompatManager中的getSkinResources()方法中，就通过反射调用了addAssetPath()方法，而addAssetPath()方法是一个@hide api。
所以想请问下，如果Android P 推出后，作者您会解决这个问题，继续维护这个框架吗？

**Comment by ximsfei** [comment]
@yumi0629 可以修复的，会继续维护这个框架

**Comment by ximsfei** [comment]
@yumi0629 可以使用`getResourcesForApplication`这个方法

**Comment by yumi0629** [comment]
@ximsfei 感谢您的回复🙏
