### ISSUE TITLE
插件式换肤的问题

### ISSUE THREAD

**Issue by dason007** [ximsfei/Android-skin-support#215]
你好作者，我才用了  .skin的方式 进行换肤， 在xml中替换的部分是生效的，但是在代码中采用setBackgroundResource的部分  未生效。 代码如下
  if (!holder.showPic) {
                            holder.itemView.setBackgroundResource(R.drawable.n_lst_item_img_bg);
                        } else {
                            Glide.with(mContext).load(holder.staticPic).into(holder.menuPic);
                        }

**Comment by ximsfei** [comment]
itemView是什么类型的？
