### ISSUE TITLE
shape变更颜色无效，以前的issues相似问题的连接也404了。

### ISSUE THREAD

**Issue by Ayanokouji-Kenn** [ximsfei/Android-skin-support#217]
这样设置后，xml里直接找colorPrimary的有效果，shape里引用到的无效
```
 SkinCompatUserThemeManager.get().addColorState(R.color.colorPrimary,"#FF0000")
SkinCompatUserThemeManager.get().addColorState(R.color.colorPrimaryDark,"#FFFF00")
```
之前可能变动过文件路径，issues里连接失效，我找到相同的`bg_bar.xml`里是直接写死的颜色，不是引用的、 那shape怎么处理？ 没有用皮肤包，只是简单的替换颜色。

**Comment by GlimmerYang** [comment]
我发现在资源文件中引用的color在修改之后都不会生效～只有直接引用才会生效，所以我现在遇到了问题 在layer-list里面引用的color修改之后也无法生效，style中引用的color也不会生效，求作者大神解答下～～
