### ISSUE TITLE
第一步集成很是不懂 尝试多种组合无法完成第一步

### ISSUE THREAD

**Issue by dvlp-org** [ximsfei/Android-skin-support#218]
⚠️导入:
如果项目中使用了AndroidX, 添加以下依赖

implementation 'skin.support:skin-support:4.0.1'                   // skin-support
implementation 'skin.support:skin-support-appcompat:4.0.1'         // skin-support 基础控件支持
implementation 'skin.support:skin-support-design:4.0.1'            // skin-support-design material design 控件支持[可选]
implementation 'skin.support:skin-support-cardview:4.0.1'          // skin-support-cardview CardView 控件支持[可选]
implementation 'skin.support:skin-support-constraint-layout:4.0.1' // skin-support-constraint-layout ConstraintLayout 控件支持[可选]
⚠️ 从3.x.x迁移至4.0.1+, 解耦了换肤库对appcompat包的依赖，需要新增以下代码

implementation 'skin.support:skin-support-appcompat:4.0.1'         // skin-support 基础控件支持
SkinCompatManager.withoutActivity(this).addInflater(new SkinAppCompatViewInflater()); // 基础控件换肤初始化
如果项目中还在使用support库，添加以下依赖

implementation 'skin.support:skin-support:3.1.0-beta1'                   // skin-support 基础控件支持
implementation 'skin.support:skin-support-design:3.1.0-beta1'            // skin-support-design material design 控件支持[可选]
implementation 'skin.support:skin-support-cardview:3.1.0-beta1'          // skin-support-cardview CardView 控件支持[可选]
implementation 'skin.support:skin-support-constraint-layout:3.1.0-beta1' // skin-support-constraint-layout ConstraintLayout 

首先 ：项目中没有使用Androidx 怎么用？
 带着摸索使用了 4.0以下的
结果初始化 SkinAppCompatViewInflater 找不到？

于是使用解耦的
mplementation 'skin.support:skin-support-appcompat:4.0.1'         // skin-support 基础控件支持
+4.0以下的引用 于是资源又冲突了

删除3.1基础控件支持，ok 不知冲突，但是SkinCompatManager找不到了

好吧,那全用4.0的 但是编译中有报错 无法找到涉及Androidx的内容

现在很无奈。。。。。。。。。。。。。。。

**Comment by ximsfei** [comment]
@dvlp-org 文档已更新
