### ISSUE TITLE
原生TabLayout反射改变底线长度报null

### ISSUE THREAD

**Issue by zt80hou** [ximsfei/Android-skin-support#221]
我自己的项目中修改了tablayout宽度，使用换肤后下面mTabStrip 为null了  能在3.1.1上适配一下吗
 Class<?> tabLayout = tabs.getClass();
        Field tabStrip = null;
        try {
            tabStrip = tabLayout.getDeclaredField("mTabStrip"); 
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        }

**Comment by ximsfei** [comment]
tabLayout.getSuperclass

**Comment by zt80hou** [comment]
多谢！解决了
