### ISSUE TITLE
不支持FragmentTabHost

### ISSUE THREAD

**Issue by beanu** [ximsfei/Android-skin-support#224]
如题，目前不支持FragmentTabhost的
background属性。有什么解决办法？

**Comment by beanu** [comment]
解决方案：

创建一个新类继承FragmentTabHost 并实现SkinCompatSupportable方法。

`public class FragmentTabHost extends android.support.v4.app.FragmentTabHost implements SkinCompatSupportable {

    private SkinCompatBackgroundHelper mBackgroundTintHelper;

    public FragmentTabHost(Context context) {
        super(context);
    }

    public FragmentTabHost(Context context, AttributeSet attrs) {
        super(context, attrs);

        mBackgroundTintHelper = new SkinCompatBackgroundHelper(this);
        mBackgroundTintHelper.loadFromAttributes(attrs, 0);

    }

    @Override
    public void setBackgroundResource(int resId) {
        getTabWidget().setBackgroundColor(getResources().getColor(resId));
        if (mBackgroundTintHelper != null) {
            mBackgroundTintHelper.onSetBackgroundResource(resId);
        }
    }

    @Override
    public void applySkin() {
        if (mBackgroundTintHelper != null) {
            mBackgroundTintHelper.applySkin();
        }
    }
}`

**Comment by ximsfei** [comment]
研究一下自定义View换肤
