### ISSUE TITLE
setTextColor 修改皮肤主题后 不会跟着变色

### ISSUE THREAD

**Issue by 494928699** [ximsfei/Android-skin-support#225]
.setTextColor(SkinCompatResources.getColor(this,colorRes));
修改皮肤主题之前的，这个不会跟着变色，之后的可以跟着变色，没问题！这个怎么半？

**Comment by ximsfei** [comment]
查faq，issues

**Comment by 494928699** [comment]
setTextAppearance 要api23以上！这个不适合！昨天就测试过了！
后面找到办法了！使用TextViewCompat.setTextAppearance() 就方法可以了！完美兼容

**Comment by ximsfei** [comment]
setTextAppearance有两个方法:
public void setTextAppearance(@StyleRes int resId)
public void setTextAppearance(Context context, @StyleRes int resId)]
