### ISSUE TITLE
皮肤插件，自定义shape文件无法更新颜色

### ISSUE THREAD

**Issue by yan-lixin** [ximsfei/Android-skin-support#227]
我用的皮肤插件night.skin，然后把app下面的需要更换颜色的drawable下的shape文件复制到skin的drawable文件下，然后生成night.skin导入到assets目录下，可是颜色没有改变。

**Comment by ZhaoyangzhouOther** [comment]
> 我用的皮肤插件night.skin，然后把app下面的需要更换颜色的drawable下的shape文件复制到skin的drawable文件下，然后生成night.skin导入到assets目录下，可是颜色没有改变。

请问你是如何解决的，我也是同样的情况

**Comment by ximsfei** [comment]
@ZhaoyangzhouOther #130
