### ISSUE TITLE
XML Layout預覽畫面無法正確顯示 (3.1.1)

### ISSUE THREAD

**Issue by protoss1010** [ximsfei/Android-skin-support#228]
![2018-11-02 6 43 48](https://user-images.githubusercontent.com/8141632/47911137-a43f2b80-decf-11e8-83d0-429074499a8f.png)

實作Layout如下
`
public class SkinDrawerLayout extends DrawerLayout implements SkinCompatSupportable {

    private static final String TAG = SkinListView.class.getSimpleName();

    private SkinCompatBackgroundHelper mBackgroundTintHelper;

    public SkinDrawerLayout(Context context) {
        this(context, null);
    }

    public SkinDrawerLayout(Context context, @Nullable AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public SkinDrawerLayout(Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        mBackgroundTintHelper = new SkinCompatBackgroundHelper(this);
        mBackgroundTintHelper.loadFromAttributes(attrs, defStyleAttr);
    }

    @Override
    public void setBackgroundResource(int resId) {
        super.setBackgroundResource(resId);
        if (mBackgroundTintHelper != null) {
            mBackgroundTintHelper.onSetBackgroundResource(resId);
        }
    }

    @Override
    public void applySkin() {
        if (mBackgroundTintHelper != null) {
            mBackgroundTintHelper.applySkin();
        }
    }

}
`

**Comment by ximsfei** [comment]
已修复
