### ISSUE TITLE
如何在代码中设置EditText左边的图片啊？

### ISSUE THREAD

**Issue by junwen0814** [ximsfei/Android-skin-support#23]
我的EditText是一个自定义View，继承你的SkinCompatEditText，然后代码中以下设置
```
Drawable username_nav_left = getResources().getDrawable(R.drawable.bg_login_user);
 username_nav_left.setBounds(0, 0, username_nav_left.getMinimumWidth() - 25, username_nav_left.getMinimumHeight() - 25);
 binding.activityLoginUsername.setCompoundDrawables(username_nav_left, null, null, null);
```
上面设置了R.drawable.bg_login_user图片，希望在载入其他skin的时候替换成其他的图片，但是最终的效果没有替换成功,我的手机的Nexus6p , 7.1的系统，并且在使用的时候有遇到载入皮肤后崩溃的问题，但是别人低版本的手机不会出现这个问题。
再问一个问题哈：库里支持修改text属性吗？不同skin有不同的标题.

**Comment by ximsfei** [comment]
@junwen0814 
1. 如何在代码中设置EditText的drawable left right top bottom.
可以参考demo 中的[示例](https://github.com/ximsfei/Android-skin-support/blob/master/skin-
app/src/main/java/com/ximsfei/skindemo/tab/LastFragment.java)
选择系统的下面两个方法之一来设置
setCompoundDrawablesRelativeWithIntrinsicBounds
setCompoundDrawablesWithIntrinsicBounds

2. 关于载入皮肤崩溃的问题.
崩溃可以有很多原因引起，有可能是框架bug，有可能是使用问题，也有可能是业务层代码问题，如果可以的话请描述的详细一点

3. 关于修改text属性的问题.
答案是可行的
如你的描述中所说，既然已经知道了，可以自定义View，并且继承自SkinCompatEditText，那么我想这对你来说已经不是什么难的问题了
详细可以参考README文件中[自定义View换肤 之 只定义属性换肤](https://github.com/ximsfei/Android-skin-support#自定义view换肤)
:)

**Comment by junwen0814** [comment]
1  关于第三点，你说的应该是自定义属性吧，我这边想要是的：
我的View控件在代码中需要动态的修改控件的背景图，而设置这个背景图是控件本身的setBackground()方法，这个我试了下好像没有效果。我其实就是想问下，在代码设置进去的资源文件（R.drawable.pic01），能否有效的替换？

2 不止setBackGround方法，其他的一些能够设置资源文件进入的能否有办法替换对应的图片，就像你回答的第一点那种直接set一个资源文件进入的样子。
 不止setBackGround方法，其他的一些能够设置资源文件进入的能否有办法替换对应的图片，就像你回答的第一点那种直接set一个资源文件进入的样子。

**Comment by ximsfei** [comment]
1. 在代码中可以通过setBackgroundResource(R.drawable.pic01)进行换肤。
因为框架默认做了background，textColor等皮肤相关的切换支持。没有做文本内容切换的支持，你想切换text属性内容，所以我让你参考自定义属性换肤的实现。
2. 可以参考[更新日志](https://github.com/ximsfei/Android-skin-support/blob/master/ChangeLog.md)
这里支持的属性，基本上都可以通过代码设置setxxx(R.xxx.yyy)
:)

**Comment by junwen0814** [comment]
更新日志里支持的属性应该都是在XML里有效吧？我想在代码里设置setBackground这样的...

**Comment by ximsfei** [comment]
@junwen0814 
代码里设置background，可以使用setBackgroundResources(R.drawable.background);
这样也是支持换肤的

**Comment by junwen0814** [comment]
嗯嗯，试了下可以的,如果代码设置资源不在activity下面,是不是就没有效果了?

**Comment by ximsfei** [comment]
看的不是很明白。设置资源不在activity下面？
