### ISSUE TITLE
集成后AndroidAutoLayout失效了

### ISSUE THREAD

**Issue by xiaobaidian** [ximsfei/Android-skin-support#230]
集成后，张鸿洋大神的AndroidAutoLayout框架失效了。

**Comment by ximsfei** [comment]
## hongyangAndroid/AndroidAutoLayout

[项目原地址](https://github.com/hongyangAndroid/AndroidAutoLayout)

[![v1.4.5](https://img.shields.io/badge/androidautolayout-v1.4.5-green.svg)](http://jcenter.bintray.com/skin/support/androidautolayout/1.4.5/)

```xml
implementation 'com.zhy:autolayout:1.4.5'
implementation 'skin.support:androidautolayout:1.4.5.2'
```

### 使用方法

* application onCreate中初始化

```java
SkinCompatManager.init(this)
        .addHookInflater(new SkinHookAutoLayoutViewInflater()) // hongyangAndroid/AndroidAutoLayout
        .loadSkin();
```
或者
```java
SkinHookAutoLayoutManager.init(this);
```

**Comment by windfone** [comment]
3.1.1 版本里面 没有SkinHookAutoLayoutManager 和 SkinHookAutoLayoutViewInflater类了，用别的方法替换了么 @ximsfei

**Comment by ximsfei** [comment]
需要添加上面的依赖
