### ISSUE TITLE
自製 ZipSDCardLoader 的問題

### ISSUE THREAD

**Issue by CaviarWang** [ximsfei/Android-skin-support#234]
參照了Demo中的 class: ZipSDCardLoader extends SkinSDCardLoader 來進行自定義的zip包換膚，
目前使用自定義 zip 實現換膚功能是可行的，但是有個小問題不知是否是我理解有誤。

為了達成自製的unzip strategy，
不會(也不能)呼叫 SkinCompatResources.getInstance().setupSkin(...)涵式。
這使得SkinCompatResources中的mSkinName一直都會是空字串。
進一步影響到getDrawable(...)涵式當中的參數skinName會維持空字串。

我目前的的work aound是在 ZipSDCardLoader 底下新增一個 String mSkinName; 
並在 loadSkinInBackground(...) 中讓 mSkinName = skinName;
而在getDrawable(...)涵式當中就使用mSkinName 來代替空字串的 skinName

**Comment by ximsfei** [comment]
zip换肤是可以和其他的换肤组合起来使用的。
资源加载优先级: 动态设置资源-加载策略中的资源-插件式换肤/应用内换肤-应用资源。

**Comment by dyguests** [comment]
我也遇到同样的问题

使用自定义`SkinSDCardLoader`时，
如果`SkinSDCardLoader#getSkinPath`使用的是自定义的路径（官方demo中的路径也不行），
那么`SkinSDCardLoader#loadSkinInBackground`时，取不到`pkgName`。
导致不会执行`SkinCompatResources#setupSkin`方法。

这样获取资源文件时就取不到`skinName`了，一直是空字串。

我看了一下demo，demo中没有用`skinName`，而是把路径写死了。
这样多少皮肤切换时就用了。

能否给一个能读取到`skinName`的解决方案呢？

另：目前我使用的解决方案也是 @CaviarWang 上文提到的解决方案。

非常感谢。
