### ISSUE TITLE
非原皮肤viewHolder createHolder耗时严重

### ISSUE THREAD

**Issue by YummyLau** [ximsfei/Android-skin-support#235]
在开发过程中，原黑色皮肤createHolder耗时为140ms，白色皮肤下耗时为平均为190ms。大部分在构建view的情况下耗时变长了。 这部分有优化吗？

**Comment by YummyLau** [comment]
非原皮肤是非应用内换肤，通过读取zip包获取resource对象处理哦，请教下作者下。 @ximsfei

**Comment by ximsfei** [comment]
试过插件式换肤的耗时吗？

**Comment by YummyLau** [comment]
@ximsfei 试过插件式和应用内换肤，非默认皮肤都会比默认皮肤在创建view的时候更耗时

**Comment by YummyLau** [comment]
@ximsfei viewtrace 和 systemTrace ，cpu profiler测试过，在SkinCompatBackgroundHelper # applySKin 中getSKinDrawable

**Comment by scsfwgy** [comment]
一般或者资源文件都应该一次获取吧，比如在初始化的时候。使用的时候加载对应资源文件就好，没必要每次render viewholder的时候都去获取

**Comment by YummyLau** [comment]
@scsfwgy 3q，可以考虑在createHolder的时候回去，但是有部分资源在bindHolder的时候获取，还是解决不了。

**Comment by YummyLau** [comment]
@scsfwgy createHolder 构建view的时候这部分耗时依然存在。哪怕只获取一次。

**Comment by scsfwgy** [comment]
代码逻辑应该不复杂，我用的是直接在应用内定义res-night这种方式，框架就是寻找对应的后缀的资源，怎么会有明显的耗时...
