### ISSUE TITLE
3.1.1版本跟项目里推荐的flycotablayout2.1.2.2有兼容问题

### ISSUE THREAD

**Issue by liyuhaolol** [ximsfei/Android-skin-support#238]
3.0.0之前的版本，当我切换皮肤的时候，我只要调用tab.notifyDataSetChanged()就可以换肤，在3.1.1版本这么干就失效了，不会切换对应的颜色，这是为什么呢？更新一下，通过测试，3.1.0-beta就已经有这个问题了，简单说下我这里实现的逻辑，当切换皮肤时，我通过广播通知一个hide的fragment进行皮肤切换，其中调用了tab.notifyDataSetChanged()

**Comment by liyuhaolol** [comment]
我这里还在测试，这里做个汇报吧，使用的项目里推荐的flycotablayout2.1.2.2，之前用3.0.0版本的框架，当fragment或者activity处于不可见的状态时，框架可以正常进行换肤操作，但是从3.1.0开始，如果fragment和activity不可见时，就无法正常完成换肤了，这是为什么呢？

**Comment by liyuhaolol** [comment]
看了https://github.com/ximsfei/Android-skin-support/issues/141，并且根据描述，解决了问题，activity不能处于onPause状态，这个时候新版本换肤框架不会运行，所以我从“广播通知修改换肤”改为了“广播修改换肤标志，在onResume中通过标志判断是否进行换肤”，自己还是找到一个相对代价小的改动方案，也给大家看的人提个醒，给作者添麻烦了！

**Comment by ximsfei** [comment]
Activity实现SkinCompatSupportable接口，在applySkin方法中调用就可以了。
