### ISSUE TITLE
applySkin无法感知Fragment生命周期

### ISSUE THREAD

**Issue by scsfwgy** [ximsfei/Android-skin-support#243]
Activity实现SkinCompatSupportable后在切换皮肤之后，会立马回调void applySkin()。但是Fragment就不可以。应该有这样的需求：在主页存活状态下，设置皮肤之后，需要子页面（Fragment）立马通过applySkin()更新相关皮肤配置。

**Comment by scsfwgy** [comment]
@ximsfei

**Comment by ximsfei** [comment]
可以自行在Activity的applySkin方法中，调用Fragment的applySkin方法。

**Comment by scsfwgy** [comment]
ok,我是用RxBus广播出去了...
