### ISSUE TITLE
关于自定义view设置 Paint 颜色问题

### ISSUE THREAD

**Issue by windfone** [ximsfei/Android-skin-support#244]
楼主大神，我在自定义view里这样换画笔得颜色，颜色换肤成了黑色，不是我要的颜色也不是原颜色，请问这可能是哪方面得问题呢，部分代码如下：

public WaveView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        this.context = context;
        TypedArray a = context.obtainStyledAttributes(attrs, R.styleable.WaveView);
        resid = a.getResourceId(R.styleable.WaveView_wave_color, INVALID_ID);
    }

    @Override
    public void applySkin() {
        super.applySkin();
        paint.setColor(SkinCompatResources.getColor(context,resid));
    }

**Comment by ximsfei** [comment]
```java
@Override
public void applySkin() {
    super.applySkin();
    paint.setColor(SkinCompatResources.getColor(context,resid));
    invalidate();
}
```

**Comment by ximsfei** [comment]
```xml
<xxx.WaveView
    app:wave_color="@color/?"/>
```
这里的？是什么

**Comment by windfone** [comment]
布局里是 这样的   app:wave_color="@color/wave_color"；

**Comment by windfone** [comment]
@ximsfei  楼主大神，

**Comment by ximsfei** [comment]
调试一下，看看这个resid对不对

**Comment by windfone** [comment]
@ximsfei ，我对比了下resid是正确的，而且不调用applySkin方法，之后我把刷新  invalidate()方法写到构造函数里就可以了，不知道为什么, 部分代码如下：
public class WaveView extends SkinCompatView {

    private int _recordlength;

    private float gap;

    private Boolean isfrist = true;

    private double _rate = -1;

    private Paint paint;

    private ArrayList<Double> heightrects;

    private int resid;
    private Context context;

    public WaveView(Context context) {
        super(context);
    }

    public WaveView(Context context, AttributeSet attrs) {
        super(context, attrs);
        this.context = context;
        paint = new Paint();
//        paint.setColor(getResources().getColor(R.color.colorAccent));
        heightrects = new ArrayList<Double>();
        initAttrs(attrs);
    }

    // *************************** 换肤 ****************************//
    public WaveView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        initAttrs(attrs);
    }

    private void initAttrs(AttributeSet attrs){
        TypedArray a = context.obtainStyledAttributes(attrs, R.styleable.WaveView);
        resid = a.getResourceId(R.styleable.WaveView_wave_color, 0);
        paint.setColor(SkinCompatResources.getColor(context,resid));
        invalidate();
    }

    @Override
    public void applySkin() {
        super.applySkin();
//        paint.setColor(SkinCompatResources.getColor(context,resid));
//        invalidate();
    }

**Comment by ximsfei** [comment]
paint在什么地方用到了

**Comment by windfone** [comment]
1. 自定义View ：
public class WaveView extends SkinCompatView {

    private int _recordlength;

    private float gap;

    private Boolean isfrist = true;

    private double _rate = -1;

    private Paint paint;

    private ArrayList<Double> heightrects;

    private int resid;
    private Context context;

    public WaveView(Context context) {
        super(context);
    }

    public WaveView(Context context, AttributeSet attrs) {
        super(context, attrs);
        this.context = context;
        paint = new Paint();
//        paint.setColor(getResources().getColor(R.color.colorAccent));
        heightrects = new ArrayList<Double>();
        initAttrs(attrs);
    }

    // *************************** 换肤 ****************************//
    public WaveView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        initAttrs(attrs);
    }

    private void initAttrs(AttributeSet attrs){
        TypedArray a = context.obtainStyledAttributes(attrs, R.styleable.WaveView);
        resid = a.getResourceId(R.styleable.WaveView_wave_color, 0);
        paint.setColor(SkinCompatResources.getColor(context,resid));
        invalidate();
    }

    @Override
    public void applySkin() {
        super.applySkin();
//        paint.setColor(SkinCompatResources.getColor(context,resid));
//        invalidate();
    }
    // *************************** 换肤 ****************************//

    public void set_recordlength(int recordlength) {
        _recordlength = recordlength * 12;//13

        //每次设置 都需要重新计算
        if(!isfrist)
        {
            gap = (float)getMeasuredWidth() / (float) _recordlength;
            DecimalFormat decimalFormat=new DecimalFormat(".00");
            String p=decimalFormat.format(gap);//format 返回的是字符串
            gap = Float.valueOf(p);
        }
    }


    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
    }

    @Override
    protected void onLayout(boolean changed, int left, int top, int right, int bottom) {
        super.onLayout(changed, left, top, right, bottom);
    }

    @Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);

        //第一次计算gap值
        if(isfrist)
        {
            gap = (float)getMeasuredWidth() / (float) _recordlength;
            DecimalFormat decimalFormat=new DecimalFormat(".00");
            String p=decimalFormat.format(gap);//format 返回的是字符串
            gap = Float.valueOf(p);
            isfrist = false;

            return;
        }

        if(_rate != -1){

            for (int i =0;i<heightrects.size();i++)
            {
                int _height = (int)(getHeight()*heightrects.get(i));
                int _left = (getHeight()- _height)/2;
                canvas.drawRect(i*gap,_left,(i+1)*gap,_left+_height,paint);
            }
        }
    }

    public void setHeightRect(double rate){
        _rate = rate;
        if(_rate<0.02)
        {
            _rate = 0.02;
        }
        heightrects.add(_rate);
        invalidate();
    }

    public void clear(){
        heightrects.clear();
        invalidate();
    }

2. attr.xml里面：
<resources>

    <declare-styleable name="WaveView">
        <attr format="color" name="wave_color"/>
    </declare-styleable>
</resources>

3. xml布局：
<com.xjfhk.exampad.widget.WaveView
                    android:layout_marginLeft="10px"
                    android:id="@+id/waveview"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    android:layout_height="140px"
                    android:layout_alignParentBottom="true"
                    app:wave_color="@color/wave_color"
                    />


@ximsfei  在onDraw（）里面用到了paint 绘制矩形
