### ISSUE TITLE
SkinCompatUserThemeManager.getDrawable()方法读取SD卡图片宽高不正确。

### ISSUE THREAD

**Issue by zhaowenliang** [ximsfei/Android-skin-support#245]
public Drawable getDrawable(Context context, @DrawableRes int drawableRes) {
        Drawable drawable = getCachedDrawable(drawableRes);
        if (drawable == null) {
            String entry = getEntryName(drawableRes, KEY_TYPE_DRAWABLE);
            if (!TextUtils.isEmpty(entry)) {
                String drawablePathAndAngle = mDrawablePathAndAngleMap.get(entry);
                if (!TextUtils.isEmpty(drawablePathAndAngle)) {
                    String[] splits = drawablePathAndAngle.split(":");
                    String path = splits[0];
                    int angle = 0;
                    if (splits.length == 2) {
                        angle = Integer.valueOf(splits[1]);
                    }
                    if (checkPathValid(path)) {
                        if (angle == 0) {
                            // 没有传入Resource，加载出来的图片宽高为真实宽高/density.
                            // drawable = Drawable.createFromPath(path);
                            Bitmap bitmap = BitmapFactory.decodeFile(path);
                            if (bitmap != null) {
                                return new BitmapDrawable(context.getResources(), bitmap);
                            }
                        } else {
                            Matrix m = new Matrix();
                            m.postRotate(angle);
                            Bitmap bitmap = BitmapFactory.decodeFile(path);
                            bitmap = Bitmap.createBitmap(bitmap, 0, 0,
                                    bitmap.getWidth(), bitmap.getHeight(), m, true);
                            // 传入Resources
                            drawable = new BitmapDrawable(context.getResources(), bitmap);
                        }
                        if (drawable != null) {
                            addDrawableToCache(drawableRes, drawable);
                        }
                    }
                }
            }
        }
        return drawable;
    }
这是修改过的代码，增加了Context参数，创建Drawable的时候传入了Resource。这个能否更新到库中呢？

**Comment by ximsfei** [comment]
可以的。你也可以提个pr

**Comment by zhaowenliang** [comment]
前段时间忙别的事情，把这个给忘掉了。你更新的版本的时候顺带改一下就行，我把issue关掉了。
