### ISSUE TITLE
请帮忙看下几个使用方面的问题，感谢～

### ISSUE THREAD

**Issue by fissure** [ximsfei/Android-skin-support#248]
1.首先一个简单的项目，引入skin.support:skin-support:3.1.1，编译不通过，是否需要其他依赖没有说明，如“No resource found that matches the given name 'android:Widget.Material.Button.Colored'.”？
2.下载项目只使用其中的一个skin-support，找全所有的依赖包编译通过，按照文档步骤，在Application初始化添加SkinCompatManager.withoutActivity(this).addStrategy(new CustomSDCardLoader());
在界面点击操作时调用SkinCompatManager.getInstance().loadSkin(skinName, null, CustomSDCardLoader.SKIN_LOADER_STRATEGY_SDCARD);并不能生效，皮肤包制作没有问题，文件检查(自己添加log)是存在的。
3.放在assets/skins目录下的皮肤包没有做检查是否存在？

原项目由于本机网络问题无法获取到部分依赖包所以无法编译通过

**Comment by ximsfei** [comment]
1. 可能是你的support版本太低。
2. 皮肤文件放在哪儿了？
3. 没有。

**Comment by fissure** [comment]
private static final String SKIN_A_DIR = "/data/local/tmp/";
    @Override
    protected String getSkinPath(Context context, String skinName) {
        return SKIN_A_DIR + skinName;
    }
皮肤文件就在这个/data/local/tmp/目录下放着的，最新版本是不用继承SkinCompatActivity(已不存在)这个对吧？不确定是否缺少配置。。。（https://blog.csdn.net/ximsfei/article/details/54586827）

另外如果support版本太低，建议添加一项最低支持版本的说明。
感谢作者的答复

**Comment by fissure** [comment]
@ximsfei 单步调试找到问题了，需要实现换肤功能的页面必须实现SkinCompatSupportable这个接口，我的界面并非自定义view...？？？
我在皮肤包添加了两项资源，string和color，为什么只有color生效了而字符串不会生效呢？
Android-Skin-Loader这个是可以的呀
