### ISSUE TITLE
shape 文件不支持呀

### ISSUE THREAD

**Issue by cyy2yjp** [ximsfei/Android-skin-support#25]

**Comment by ximsfei** [comment]
如果可以的话，能不能描述的清晰点
demo中有例子[shape](https://github.com/ximsfei/Android-skin-support/blob/master/skin-app/src/main/res/drawable/bg_bar.xml)

**Comment by cyy2yjp** [comment]
不好意思 指示替换了颜色 没有在另一个项目加入shape文件

**Comment by ximsfei** [comment]
解决了就好:)
