### ISSUE TITLE
希望开放SkinCompatResources#getTargetResId权限

### ISSUE THREAD

**Issue by scsfwgy** [ximsfei/Android-skin-support#250]
在实际应用中有获取资源文件id的需求，在换肤模式中会自动拼接换肤资源的后缀。比如获取图片、drawable等的资源id等。现在调用SkinCompatResources#getTargetResId是通过反射实现的。要么提供细化的获取color、drawable等资源的方法？

**Comment by Longalei** [comment]
通过SkinBuildInLoader实现

**Comment by wuzhxyl** [comment]
自己通过反射玩吧我就是这么干的..

**Comment by zt80hou** [comment]
> 通过SkinBuildInLoader实现 @scsfwgy

如何实现,求教

**Comment by zt80hou** [comment]
> 自己通过反射玩吧我就是这么干的..

如何实现,求教
