### ISSUE TITLE
在换肤后，切换RTL状态，图标方向错误

### ISSUE THREAD

**Issue by JarediKey** [ximsfei/Android-skin-support#252]
loadSkin后，从正常语言切换到阿拉伯语，布局从LTR变成RTL，做了RTL适配的资源文件不会被加载。
如果是在RTL下，未加载皮肤情况下，loadSkin则会去加载做了RTL适配的资源文件。
请问作者这个问题出在哪里？

**Comment by Longalei** [comment]
个人猜想：1.从正常语言切换到阿拉伯语，布局从LTR变成RTL。此时杀掉App,重启而不是直接打开会不会加载做了RTL适配的资源文件？
2.根据你说的在RTL下，可以加载做了RTL适配的资源文件那么重启App是可以成功的。如果需要支持在切换语言，App中加载做了RTL适配的资源文件那么直接在Application中的onConfigurationChanged中对语言处理SkinCompatManager重新加载一次。

**Comment by JarediKey** [comment]
@Longalei 感谢你热心回复。
这个问题我已经解决。
问题原因：通过ResId加载资源文件时选择LTR还是RTL目录下的文件是根据Resources中Configuration对象里的layoutDirection值判断。在loadSkin时，SkinCompatResources类会调用setupSkin()方法，传入的Resource是从最开始初始化时传入的App Context中拿到的。此时的layoutDirection是LTR，所以在切换RTL后，这个layoutDirection没有被修改，还是LTR，所以加载的资源文件全都是LTR的。
解决方案：在切换RTL后，获取SkinCompatResources的mResources，对它进行修改。就可以了。

**Comment by Longalei** [comment]
嗯嗯了。 @JarediKey
