### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by cao1922113** [ximsfei/Android-skin-support#256]
之前用了一个换肤框架，由于一些机型兼容的问题就换了这个，发现换肤是能换，但是比以前卡了很多，如果在application中注释掉初始化的代码之后，应用还是和之前一样流畅，只要一打开就卡的要死，请问是不是有什么细节的操作需要注意，另外我通过Android Profiler查看内存也发现，Skin开头的类都是内存占用很大的类，希望作者能否提供一个优化的方案

**Comment by pye52** [comment]
按道理应该不会把所有资源缓存起来吧，只是缓存id的话还会占用大量内存么？

**Comment by ximsfei** [comment]
1. 应用内换肤、插件换肤，换肤框架不会缓存drawable，colorstatelist等资源。
2. 关闭换肤功能后，正常的View空间也是内存占用较大的一部分类
3. 关于一打开就卡的要死的问题，我会持续跟进优化一下

**Comment by Bentleyli** [comment]
请问卡顿的问题最后能解决吗？我现在也是遇到了

**Comment by Bentleyli** [comment]
> 之前用了一个换肤框架，由于一些机型兼容的问题就换了这个，发现换肤是能换，但是比以前卡了很多，如果在application中注释掉初始化的代码之后，应用还是和之前一样流畅，只要一打开就卡的要死，请问是不是有什么细节的操作需要注意，另外我通过Android Profiler查看内存也发现，Skin开头的类都是内存占用很大的类，希望作者能否提供一个优化的方案

请教大神，问题最后是怎么解决的呢？
