### ISSUE TITLE
换肤后 使用的第三方XTabLayout控件的文字颜色会变成紫色，targetSdk 26,之前是17正常

### ISSUE THREAD

**Issue by pingxu** [ximsfei/Android-skin-support#257]
换肤后 使用的第三方XTabLayout控件的文字颜色会变成紫色，targetSdk 26,之前是17正常

**Comment by getglory** [comment]
你需要继承这个控件，自己实现换肤的步骤

**Comment by hxingever** [comment]
> 换肤后 使用的第三方XTabLayout控件的文字颜色会变成紫色，targetSdk 26,之前是17正常

我用的库自带的SkinMaterialTabLayout，在fragment里面使用文字也变成紫色了，求助

**Comment by hxingever** [comment]
> 你需要继承这个控件，自己实现换肤的步骤

我用的库自带的SkinMaterialTabLayout，在fragment里面使用文字也变成紫色了，求助

**Comment by ximsfei** [comment]
> > 你需要继承这个控件，自己实现换肤的步骤
> 
> 我用的库自带的SkinMaterialTabLayout，在fragment里面使用文字也变成紫色了，求助

创建View用的Context是什么

**Comment by hxingever** [comment]
> > > 你需要继承这个控件，自己实现换肤的步骤
> > 
> > 
> > 我用的库自带的SkinMaterialTabLayout，在fragment里面使用文字也变成紫色了，求助
> 
> 创建View用的Context是什么

父类：
public abstract class BaseFragment extends Fragment {
    private View view;
    protected abstract void initView(View view, Bundle savedInstanceState);
    //获取布局文件ID
    protected abstract int getLayoutId();
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        view = null;
        view = inflater.inflate(getLayoutId(), container, false);
        initView(view, savedInstanceState);
        return view;
    }
}

子类fragment（是mainActivity中r的某一个：通过getSupportFragmentManager().beginTransaction().show()/hide()方式加载的）继承的BaseFragment，重写的initView()方法，用butterKnife绑定的view初始化，设置界面点击换肤按钮换肤，tabLayout文字变成紫色，tabIndicator换颜色正常。

**Comment by LinXueyuanStdio** [comment]
主题的锅，检查一下主题

**Comment by hxingever** [comment]
> > > 你需要继承这个控件，自己实现换肤的步骤
> > 
> > 
> > 我用的库自带的SkinMaterialTabLayout，在fragment里面使用文字也变成紫色了，求助
> 
> 创建View用的Context是什么


![_20190830093454](https://user-images.githubusercontent.com/9794894/63987462-f14d5780-cb0a-11e9-8fc6-583911d22121.png)

**Comment by ximsfei** [comment]
嗯，检查下主题，或者提供个demo？

**Comment by hxingever** [comment]
> 嗯，检查下主题，或者提供个demo？
 搞了个简单的demo，麻烦帮我看下 是哪里的问题 点了换肤之后 资讯fragment中的tabLayout文本变成紫色 
[hxtest.zip](https://github.com/ximsfei/Android-skin-support/files/3568740/hxtest.zip)

**Comment by hxingever** [comment]
> 嗯，检查下主题，或者提供个demo？

@ximsfei

**Comment by 282144757** [comment]
我也遇到同样的问题，楼主怎么解决的？
