### ISSUE TITLE
可以动态切换布局吗?

### ISSUE THREAD

**Issue by dtboy1995** [ximsfei/Android-skin-support#259]
可以动态切换布局吗?

**Comment by CommaYu** [comment]
@dtboy1995 这个问题没有被回答就关闭了？为何？我也想知道能不能换一下布局来着。

**Comment by dtboy1995** [comment]
@CommaYu，我觉得这个需求不是这个库的核心功能，这个库的核心功能是修改布局中的资源参数，而且对于很细节的布局控制，光使用库也不行。。（其实是问了几天没人回答就关闭了，最后可以用热更新框架去把fragment更新上去就行，重启app嘛）
