### ISSUE TITLE
状态栏换肤不支持带有google原生侧滑菜单的界面

### ISSUE THREAD

**Issue by wqjuser** [ximsfei/Android-skin-support#26]
新建工程后直接使用框架换肤，目前发现三星one5和华为荣耀4x的状态栏颜色并没有改变，仍然是默认的颜色

**Comment by ximsfei** [comment]
到skin-support:1.2.5还没有支持状态栏换肤哦。如果可以的话，把问题描述清楚一些吧，直接拉取代码的话，状态栏换肤，只支持到Android 5.0以上哈。 ：）

**Comment by wqjuser** [comment]
(⊙o⊙)哦，今天看你的更新，我以为支持了状态栏换肤了

**Comment by wqjuser** [comment]
这是build文件的依赖 `compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.android.support:design:25.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-beta4'
    testCompile 'junit:junit:4.12'
    compile 'com.jakewharton:butterknife:8.5.1'
    compile 'com.jakewharton:butterknife-compiler:8.5.1'
    compile 'skin.support:skin-support:1.2.5'          // skin-support 基础控件支持
    compile 'skin.support:skin-support-design:1.2.2'   // skin-support-design material design 控件支持[可选]
    compile 'skin.support:skin-support-cardview:1.2.0' // skin-support-cardview CardView 控件支持[可选]`

**Comment by ximsfei** [comment]
这些暂时是最新的。:)

**Comment by wqjuser** [comment]
恩，会持续关注的
