### ISSUE TITLE
使用AndroidStudio3.3版本、Androidx支持库，为什么运行这个Demo换肤的时候很多组件都没有变色？

### ISSUE THREAD

**Issue by Wzz1252** [ximsfei/Android-skin-support#260]
![image](https://user-images.githubusercontent.com/10561633/53086374-f15b1200-353f-11e9-9694-05b38b7ab106.png)
![image](https://user-images.githubusercontent.com/10561633/53086388-f91ab680-353f-11e9-87b5-eaef64b2ced1.png)
![image](https://user-images.githubusercontent.com/10561633/53086463-20718380-3540-11e9-8a5a-5b09580cb0c1.png)

只是随便截了几张图

**Comment by lovephantasy** [comment]
同样的问题，请问楼主解决了吗

**Comment by AndyLeeBlue** [comment]
今天运行了下，果然如此，不太敢贸然尝试啊，撸主能说明下吗？

**Comment by Wzz1252** [comment]
> 今天运行了下，果然如此，不太敢贸然尝试啊，撸主能说明下吗？

换肤的颜色就是这个样子，不算问题，自己改改颜色就行。。。但是对于TabLayout和一些其他的系统组件支持的不是很好，修改其他比较蛋疼

**Comment by ximsfei** [comment]
皮肤包里的颜色本身就是这样的
