### ISSUE TITLE
回调函数错误：换肤SkinLoaderListener回调不正确，无法进入onFailed！

### ISSUE THREAD

**Issue by coding-dream** [ximsfei/Android-skin-support#262]
1. 出现场景：用户成功加载换肤后，sp里面保存了skinName，然后用户删除磁盘缓存，再次加载换肤如果失败则用默认的皮肤，但是回调接口是onSuccess。
```
SkinLoadTask.doInBackground
// 使用sdkcard加载策略，loadSkinInBackground方法 如果skin包不存在，返回了null
String skinName = this.mStrategy.loadSkinInBackground(SkinCompatManager.this.mAppContext, params[0]);
// ....
return params[0];

```
但是此处在return的时候返回值仍然是params[0]，所以导致onPostExecute内接受的参数即使皮肤包不存在，回调函数也是onSuccess().
希望作者有空修复下此Bug。

2. 还有一个问题就是：RTL的支持，换肤后，drawableStart 和 padingStart是不支持的，用的是skin-support-3.1.1版本，不知作者是否现在已经修复了。

谢谢！！

**Comment by Elaine666** [comment]
你直接提个PR吧，return skinName；

**Comment by ximsfei** [comment]
已修复
