### ISSUE TITLE
Zip策略换肤，只支持指定的资源id换肤吗？不能像插件换肤一样，只把自己需要的资源文件打包么？例如，颜色的替换，不能直接将color.xml文件放到zip里面吗？

### ISSUE THREAD

**Issue by Gengxiuxiu** [ximsfei/Android-skin-support#267]

**Comment by ximsfei** [comment]
Zip策略换肤，不支持直接将color.xml文件放到zip里面。可以使用[自定义加载器](https://github.com/ximsfei/Android-skin-support#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%A0%E8%BD%BD%E7%AD%96%E7%95%A5)来实现
