### ISSUE TITLE
Activity 中打开 Toolbar 中的 Menu 导致 SkinObserver 中的 SkinHelpers 数量增加！

### ISSUE THREAD

**Issue by Lrony** [ximsfei/Android-skin-support#269]
场景：
我在测试的 Demo 中使用 Toolbar 上的 Menu 来控制换肤。
但是发现一旦打开 Menu 那么当前的 SkinCompatDelegate 就会走进 onCreateView，
而且 SkinHelpers 数量也会增加 24！
每次打开都会增加！

重现方法：
1. 在 Activity 中重写 onCreateOptionsMenu 来使用 Menu。
2. 点击 Toolbar上的 Menu Icon 打开 Menu 即可。
3. 我是在 SkinCompatDelegate.java 中的 applySkin 方法输出的 LOG，用来观察 mSkinHelpers 数量。

我认为这个问题会导致内存泄露。
目前我只测试出这个 CASE，但是我猜想会不会在所有会执行 onCreateView 的地方都会有这个问题？但是我测试屏幕旋转不会有这个问题。

还请作者帮忙分析分析～

**Comment by Lrony** [comment]
```java
new AlertDialog.Builder(this)
                .setMessage("Hi")
                .show();
```

Activity中弹出Dialog也会有这个问题。

**Comment by Lrony** [comment]
```
onCreateView LinearLayout
onCreateView ViewStub
onCreateView FrameLayout
onCreateView android.support.v7.widget.FitWindowsFrameLayout
onCreateView android.support.v7.widget.ContentFrameLayout
onCreateView android.support.v7.widget.ViewStubCompat
onCreateView android.support.v7.widget.AlertDialogLayout
onCreateView LinearLayout
onCreateView LinearLayout
onCreateView ImageView
onCreateView android.support.v7.widget.DialogTitle
onCreateView android.widget.Space
onCreateView FrameLayout
onCreateView View
onCreateView android.support.v4.widget.NestedScrollView
onCreateView LinearLayout
onCreateView android.widget.Space
onCreateView TextView
onCreateView android.widget.Space
onCreateView View
onCreateView FrameLayout
onCreateView FrameLayout
onCreateView ScrollView
onCreateView android.support.v7.widget.ButtonBarLayout
onCreateView Button
onCreateView android.widget.Space
onCreateView Button
onCreateView Button
```
打开Dialog时 `SkinCompatDelegate`中会创建以上View，应该是Dialog的View创建也被代理了。
但是这些View并没有被释放，导致`mSkinHelpers`越来越多

**Comment by ximsfei** [comment]
刚看了一下，确实会增加mSkinHelpers中数量。不过不会造成内存泄漏，mSkinHelpers中的View是通过WeakReference引用的，Toolbar Menu关闭后，垃圾回收View会自动释放。如图实际mSkinHelpers中的referent对象为空
![image](https://user-images.githubusercontent.com/9425734/82723803-0f479180-9d04-11ea-90b1-b2147d79703b.png)
