### ISSUE TITLE
drawable 里面设置了颜色它是一个selector 貌似没效果

### ISSUE THREAD

**Issue by CharlesMing** [ximsfei/Android-skin-support#27]
代码这样写的
` <item android:drawable="@drawable/ic_button_pressed"
          android:state_pressed="true"
          android:state_window_focused="false"/>
    <item android:drawable="@drawable/ic_button_enable" android:state_enabled="false"/>
    <item android:drawable="@drawable/ic_button_normal" android:state_enabled="true"/>
    <item android:drawable="@drawable/ic_button_normal"/>`
ic_button_pressed :
`<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="@color/color10"/>
    <corners android:radius="@dimen/app_radius_size"/>
</shape>`

ic_button_enable:
`<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="@color/color10"/>
    <corners android:radius="@dimen/app_radius_size"/>`
</shape>
ic_button_normal:
`<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="@color/color4"/>
    <corners android:radius="@dimen/app_radius_size"/>
</shape>`
这样做之后不能进行换肤，什么原因呢

**Comment by ximsfei** [comment]
可以换肤的，你需要在皮肤包里也写上这些xml文件。参考demo 中的例子 :)

**Comment by CharlesMing** [comment]
谢谢，原来如此

**Comment by CharlesMing** [comment]
再请教一个问题：textView.setTextColor(ContextCompat.getColor(_mActivity, R.color.color8)); 这样是无法实现换肤的吗？必须是在布局文件中添加才可以吗？

**Comment by ximsfei** [comment]
是的，无法通过setTextColor换肤，可以通过布局文件中添加，也可以通过textView.setTextAppearance(R.style. SkinCompatTextAppearance)进行换肤。
详情可以查看[SkinCompatTextAppearance](https://github.com/ximsfei/Android-skin-support/blob/master/skin-app/src/main/res/values/styles.xml)
:)

**Comment by mr-wind** [comment]
有没有只在皮肤包里修改color.xml   不需要再在皮肤包的drawable中添加这些selector的写法？感觉应该有一种只改color不改drawable的策略

**Comment by ximsfei** [comment]
暂时没有

**Comment by xfhy** [comment]
大佬,请教一个问题,我现在皮肤颜色值是从网络加载的,需要动态修改本地的颜色值,但是shape好像不支持..
我是在代码中动态修改colorAccent颜色的
`SkinCompatUserThemeManager.get().addColorState(R.color.colorAccent, "#40FF6D")`

```xml
<shape xmlns:android="http://schemas.android.com/apk/res/android"
       android:shape="rectangle">

    <corners android:radius="2dp"/>

    <solid android:color="@color/colorAccent"/>

</shape>
```

**Comment by androidHQJ** [comment]
> 

我也遇到这个问题了，请问你这个问题解决了吗？
