### ISSUE TITLE
使用第三方（自定义）控件的一个疑问

### ISSUE THREAD

**Issue by Lrony** [ximsfei/Android-skin-support#270]
```
SkinCompatCircleImageView extends CircleImageView implements SkinCompatSupportable
```
以这个第三方控件为例。
我既然都包装过了，为什么还要去干涉这个View的创建呢？
我直接在布局文件中使用`SkinCompatCircleImageView`是不是更方便呢？
还是有我没考虑到的问题，麻烦帮忙解答下～谢谢！

**Comment by Lrony** [comment]
是为了不修改现有代码么？

**Comment by ximsfei** [comment]
为了不修改项目代码，减少对业务代码的侵入
