### ISSUE TITLE
在replugin下的插件程序中使用换肤功能，不能及时生效

### ISSUE THREAD

**Issue by sjiao** [ximsfei/Android-skin-support#271]
在replugin下的插件程序中使用换肤功能，点击换肤之后，界面无变化，需要退出当前activity，再次进入才能看到变化。并且所有支持换肤的activity都需要重新打开，才能生效。

请问有什么解决方案么？

**Comment by ximsfei** [comment]
在插件化工程中使用换肤框架，需要自行适配一下
