### ISSUE TITLE
项目使用Glide加载Gif图片,经测试无法换肤

### ISSUE THREAD

**Issue by NaclFire** [ximsfei/Android-skin-support#275]
项目中一个全局dialog,使用的是gif图片,使用Glide加载,把图片放进皮肤包,发现无法更换,请问这个是不支持还是我没用对?

**Comment by ximsfei** [comment]
Glide，fresco等图片加载库，未适配，需要自己适配。
可以在对应的Activity，实现换肤接口，再applySkin方法中进行手动更新
