### ISSUE TITLE
我是否可以通过style 在里面写自定义属性？

### ISSUE THREAD

**Issue by CharlesMing** [ximsfei/Android-skin-support#28]
比如：`<style name="CustomColor"><item name="custombackgroundColor">@color/red</item></style>`
我怎么在代码中实现？是否可以参考SkinCompatTextView 这个类来实现？

**Comment by ximsfei** [comment]
可以的。不过需要自己去扩展 :)

**Comment by lmz1993** [comment]
项目中有很多@style/xxx
的，希望后期能维护支持~急急急

**Comment by VliceZ** [comment]
@ximsfei @lmz1993 具体怎么配置，有文档吗?
