### ISSUE TITLE
设置了setSkinStatusBarColorEnable(提示过期 红色)状态栏没有变色 求解决？

### ISSUE THREAD

**Issue by RayhoWong** [ximsfei/Android-skin-support#280]
colorPrimary_night和colorPrimaryDark_night颜色换肤后没有应用，不知道什么原因

**Comment by RayhoWong** [comment]
colorPrimary_night和colorPrimaryDark_night颜色换肤后没有应用，不知道什么原因

**Comment by ximsfei** [comment]
框架状态栏换肤已弃用，可以自行扩展实现
