### ISSUE TITLE
初始化为default的问题

### ISSUE THREAD

**Issue by AndyGu** [ximsfei/Android-skin-support#281]
LinearLayout中手动addView(itemView)，itemView中包含TextView，针对TextView的textColor在xml中设置了style，
`<style name="TvTextStyle">
        <item name="android:textColor">@color/tv_selector</item>
</style>` 

tv_selector是这样的
`<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_selected="true" android:color="@color/tv_white" />
    <item android:state_pressed="true" android:color="@color/tv_white"  />
    <item android:state_focused="true" android:color="@color/tv_white"  />
    <item android:color="@color/text_black" />
</selector>`

itemView中xml设置了`style="@style/TvTextStyle"`
tv_selector中的颜色都有日夜间对应，tv_selector也有日夜间对应
问题是：在TvTextStyle没有夜间对应的情况下，夜间模式进入app显示默认的日间style，在设置了
`<style name="TvTextStyle_night">
        <item name="android:textColor">@color/tv_selector_night</item>
</style>` 
之后就好了，
但是利用demo测试却没有这个问题，我看demo也并没有设置TextStyle_night, 请问下可能是什么原因？

**Comment by ximsfei** [comment]
应用内换肤最终都是通过资源名加后缀/前缀的方式实现的
