### ISSUE TITLE
ImageView初始化问题

### ISSUE THREAD

**Issue by AndyGu** [ximsfei/Android-skin-support#282]
activity中的用tablayout+viewpager的模式装载fragment，在本地记录是否为夜间模式，ImageView src设置为的drawable文件夹下的selector，
`<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
     <item android:drawable="@mipmap/btn_selected" android:state_selected="true"/>
    <item android:drawable="@mipmap/btn_selected" android:state_pressed="true"/>
    <item android:drawable="@mipmap/btn_normal"/>
</selector>`

`<ImageView
     android:layout_width="wrap_content"
     android:layout_height="wrap_content"
     android:src="@drawable/btn_selector" />`
当由夜间模式开启app时 ，在初始化时只加载为日间模式的图片，并未加载为_night后缀的selector，demo并无此现象，不知道是启动时加载夜间模式错误，还是图片有问题，还是xml设置有问题，还是之前在同一界面切换日夜间模式所致？

**Comment by ximsfei** [comment]
Application中loadSkin，应用重启后，会加载上次的皮肤资源。
不需要接入应用自己记录夜间模式
