### ISSUE TITLE
关于TextView的textcolor的颜色值为?attr/时，SkinCompatTextView会崩溃且不支持自定义属性值的换肤

### ISSUE THREAD

**Issue by linmscat** [ximsfei/Android-skin-support#283]
TextView中的textcolor或者background有时候会用引用值?attr/，此时换肤框架会在SkinCompatTextView的构造方法：public SkinCompatTextView(Context context, AttributeSet attrs, int defStyleAttr)崩溃，崩溃堆栈：
2019-05-06_14_49_19,uuid:7667f327-b137-41a6-a569-ef2d7c2f986d
JAVA Crash:Failed to resolve attribute at index 37: TypedValue{t=0x2/d=0x7f030128 a=-1}
ERROR STACK:
android.view.InflateException:Binary XML file line #23: Binary XML file line #23: Error inflating class TextView

......
Caused by:
java.lang.UnsupportedOperationException:Failed to resolve attribute at index 37: TypedValue{t=0x2/d=0x7f030128 a=-1}
android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:733)
android.view.View.<init>(View.java:5289)
android.widget.TextView.<init>(TextView.java:875)
android.widget.TextView.<init>(TextView.java:869)
android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:75)

作者看能否添加对?attr/的支持

**Comment by ximsfei** [comment]
参考demo实现，框架支持?attr/属性设置background/textColor，检查一下主题是否设置正确
![image](https://user-images.githubusercontent.com/9425734/82724734-dced6280-9d0a-11ea-8d1b-10948409c498.png)
