### ISSUE TITLE
关于ActionBar修改背景颜色问题

### ISSUE THREAD

**Issue by GlimmerYang** [ximsfei/Android-skin-support#284]
对于自己定义的布局，可以随意的更改颜色值，但是在style中规定的那些actionbar各种相关颜色值，在 SkinCompatUserThemeManager.get().addColorState(R.color.t1_8_background, color);
            SkinCompatUserThemeManager.get().apply();之后也没有变换颜色，所以是不是不支持actionbar的颜色变化，除非自己定义toolbar

**Comment by ximsfei** [comment]
是的，可以自定义toolbar
