### ISSUE TITLE
关于应用内替换drawable文件夹下面的图片

### ISSUE THREAD

**Issue by GlimmerYang** [ximsfei/Android-skin-support#285]
假如drawable文件下有ic_all,ic_null,本来是加载的ic_call，现在动态将ic_call改成ic_null的内容可以吗

**Comment by ximsfei** [comment]
参考下[自定义加载策略](https://github.com/ximsfei/Android-skin-support#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%A0%E8%BD%BD%E7%AD%96%E7%95%A5)
