### ISSUE TITLE
插件化工程换肤，存在资源引用问题

### ISSUE THREAD

**Issue by dudumuta** [ximsfei/Android-skin-support#286]
我们工程是插件化的，资源id都重新定义。在这种情况下全局监听，调用imageview的换肤，居然会影响到别的业务。checkResourceId(mSrcResId)这个方法的调用是否考虑插件化资源重新定义id的场景。好尴尬，这个坑导致项目要下线。

**Comment by ximsfei** [comment]
插件化的项目，需要自行修改下换肤框架。。不同的插件化方案，可能会不太一样
