### ISSUE TITLE
xxx.setBackground()怎么实现换肤 求解 谢谢 

### ISSUE THREAD

**Issue by Bleach1** [ximsfei/Android-skin-support#287]

**Comment by scsfwgy** [comment]
随便找一个support中的系统组件的实现方式，基本一致。比如：SkinTextView

**Comment by Bleach1** [comment]
OK，我试了一下setBackground  setBackgroundDrawable 都不行 setBackgroundResource  OK

**Comment by ximsfei** [comment]
框架的原理，是根据resid，获取resname；
再根据resname，获取皮肤包里的resid，最终获取皮肤包里的资源。
直接设置drawable，无法知道，如何从皮肤包里获取资源。
