### ISSUE TITLE
可以考虑提供一个接口，监听切换语言

### ISSUE THREAD

**Issue by scsfwgy** [ximsfei/Android-skin-support#289]
原因:现在skin_support的好处在于可以实时监听实时更换皮肤，如果我们更广义一点是更换资源。像语言国际化，现在一般的做法都是手动切换语言后重新加载首页（其它页面直接顶掉），相当于变相的重启了APP，体验其实不好。如果采用skin_support体验会好很多。

**Comment by DaveBoy** [comment]
它内部持有了view的  反射拿到调用刷新语言的方法（自己自定义一个textview）就行了
