### ISSUE TITLE
发现框架的一个bug

### ISSUE THREAD

**Issue by mojunmo1216** [ximsfei/Android-skin-support#291]
当执行错误路径的skin文件时， SkinCompatManager.getInstance().loadSkin("result.skin" , new SkinCompatManager.SkinLoaderListener(){
@override
public void onStart() {
}
@override
public void onSuccess() {
}
@override
public void onFailed(String errMsg) {

                    }},SkinCompatManager.SKIN_LOADER_STRATEGY_BUILD_IN);
一直返回的回调都是success，因为
try {
                if (params.length == 1) {
                    String skinName = mStrategy.loadSkinInBackground(mAppContext, params[0]);
                    if (TextUtils.isEmpty(skinName)) {
                        SkinCompatResources.getInstance().reset(mStrategy);
              
                    }
                    return params[0];
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

返回的还是有值的皮肤包名，不是null改为这个就好了
try {
                if (params.length == 1) {
                    String skinName = mStrategy.loadSkinInBackground(mAppContext, params[0]);
                    if (TextUtils.isEmpty(skinName)) {
                        SkinCompatResources.getInstance().reset(mStrategy);
                        return null;
                    }
                    return params[0];
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

**Comment by ximsfei** [comment]
修复了
