### ISSUE TITLE
skin 4.0.1 换肤Native奔溃

### ISSUE THREAD

**Issue by steven2947** [ximsfei/Android-skin-support#293]
奔溃日志：

signal 7 (SIGBUS), code 0 (SI_USER), fault addr 00000bee
  r0 b9199fec  r1 b94adf50  r2 00000006  r3 b918c720
  r4 b9199fec  r5 00000006  r6 b9190878  r7 00000000
  r8 a118aa5c  r9 b94adf50  10 b94adf50  fp 00000006
  ip b6d75d68  sp be8a12b8  lr b6d68863  pc b6d64f96  cpsr 600e0030
    00 pc 00013f96 android::ResStringPool::indexOfString(unsigned short const*, unsigned int) const LINE:libandroidfw.so
    01 pc 0001785f android::ResTable::identifierForName(unsigned short const*, unsigned int, unsigned short const*, unsigned int, unsigned short const*, unsigned int, unsigned int*) const LINE:libandroidfw.so
    02 pc 000878b7 /system/lib/libandroid_runtime.so
    03 pc 0089be4d /system/framework/arm/boot.oat

    >>> [Dalvik stack info] <<<
    at android.content.res.AssetManager.getResourceIdentifier(Native method)
    at android.content.res.Resources.getIdentifier(Resources.java:2059)
    at skin.support.content.res.SkinCompatResources.getTargetResId(SkinCompatResources.java:118)
    at skin.support.content.res.SkinCompatVectorResources.getSkinDrawableCompat(SkinCompatVectorResources.java:79)
    at skin.support.content.res.SkinCompatVectorResources.getDrawableCompat(SkinCompatVectorResources.java:89)
    at skin.support.widget.SkinCompatBackgroundHelper.applySkin(SkinCompatBackgroundHelper.java:50)
    at skin.support.widget.SkinCompatBackgroundHelper.loadFromAttributes(SkinCompatBackgroundHelper.java:35)
    at skin.support.constraint.SkinCompatConstraintLayout.<init>(SkinCompatConstraintLayout.java:28)
    at skin.support.constraint.SkinCompatConstraintLayout.<init>(SkinCompatConstraintLayout.java:22)
    at skin.support.constraint.app.SkinConstraintViewInflater.createView(SkinConstraintViewInflater.java:16)
    at skin.support.app.SkinCompatViewInflater.createViewFromInflater(SkinCompatViewInflater.java:77)
    at skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:46)
    at skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:56)
    at skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:31)
    at androidx.core.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
    at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
    at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
    at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
    at com.xxz.android.presentation.ui.activities.MainActivity.onCreate(MainActivity.kt:78)
    at android.app.Activity.performCreate(Activity.java:6222)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2407)
    at android.app.ActivityThread.access$800(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5321)
    at java.lang.reflect.Method.invoke!(Native method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

---------------------------------------

是再次回到首页时奔溃的，之前3.+的版本没有出现，更新到4.0.1就出现比较频繁

**Comment by xiaoxing1992** [comment]
您这个解决了吗  我这个是魅族手机  也是相同的错误 版本3.1.4

**Comment by xiaoxing1992** [comment]
2020-03-04 10:32:07.980 25067-25067/? E/priviteSocial: 欢迎使用友盟社会化分享业务!
2020-03-04 10:32:07.984 25067-25067/? E/MobclickAgent: setPageCollectionMode can not be called in child process
2020-03-04 10:32:08.114 24541-25124/com.motoband E/CrashReport: #++++++++++Record By Bugly++++++++++#
2020-03-04 10:32:08.114 24541-25124/com.motoband E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
2020-03-04 10:32:08.114 24541-25124/com.motoband E/CrashReport: # PKG NAME:
2020-03-04 10:32:08.115 24541-25124/com.motoband E/CrashReport: # APP VER: 
2020-03-04 10:32:08.115 24541-25124/com.motoband E/CrashReport: # LAUNCH TIME: 2020-03-04 10:31:58
2020-03-04 10:32:08.115 24541-25124/com.motoband E/CrashReport: # CRASH TYPE: NATIVE_CRASH
2020-03-04 10:32:08.115 24541-25124/com.motoband E/CrashReport: # CRASH TIME: 2020-03-04 10:32:08
2020-03-04 10:32:08.115 24541-25124/com.motoband E/CrashReport: # CRASH PROCESS: com.motoband
2020-03-04 10:32:08.115 24541-25124/com.motoband E/CrashReport: # CRASH THREAD: main(2)
2020-03-04 10:32:08.115 24541-25124/com.motoband E/CrashReport: # REPORT ID: d6129eb7-4c98-4560-b5e7-0fbe93e19c9c
2020-03-04 10:32:08.116 24541-25124/com.motoband E/CrashReport: # CRASH DEVICE: 16th Plus UNROOT
2020-03-04 10:32:08.116 24541-25124/com.motoband E/CrashReport: # RUNTIME AVAIL RAM:1528762368 ROM:20073926656 SD:19969069056
2020-03-04 10:32:08.116 24541-25124/com.motoband E/CrashReport: # RUNTIME TOTAL RAM:8038121472 ROM:118690562048 SD:118585704448
2020-03-04 10:32:08.116 24541-25124/com.motoband E/CrashReport: # EXCEPTION FIRED BY KERNEL UNKNOWN
2020-03-04 10:32:08.116 24541-25124/com.motoband E/CrashReport: # CRASH STACK: 
2020-03-04 10:32:08.116 24541-25124/com.motoband E/CrashReport: SIGBUS(BUS_ADRERR)
    0xcad811f8
    #00    pc 000252c6    /system/lib/libandroidfw.so (_ZNK7android13ResStringPool13indexOfStringEPKDsj+53) [armeabi-v7a::23a7c7e9204b1a993a7e7e494523de5b]
    #01    pc 0002a36f    /system/lib/libandroidfw.so (_ZNK7android8ResTable17identifierForNameEPKDsjS2_jS2_jPj+462) [armeabi-v7a::23a7c7e9204b1a993a7e7e494523de5b]
    #02    pc 000a9cad    /system/lib/libandroid_runtime.so [armeabi-v7a::55b53e1e41508c563a8744f056b56015]
    #03    pc 009b8a8b    /system/framework/arm/boot-framework.oat (oatexec+3979915) [armeabi::2b0d5689266c18edf262446a78665419]
    java:
    android.content.res.ResourcesImpl.getIdentifier(ResourcesImpl.java:275)
    android.content.res.Resources.getIdentifier(Resources.java:1923)
    skin.support.content.res.SkinCompatResources.getTargetResId(SkinCompatResources.java:104)
    skin.support.content.res.SkinCompatResources.getSkinValue(SkinCompatResources.java:230)
    skin.support.content.res.SkinCompatResources.getValue(SkinCompatResources.java:260)
    skin.support.content.res.SkinCompatDrawableManager.createDrawableIfNeeded(SkinCompatDrawableManager.java:220)
    skin.support.content.res.SkinCompatDrawableManager.getDrawable(SkinCompatDrawableManager.java:183)
    skin.support.content.res.SkinCompatDrawableManager.getDrawable(SkinCompatDrawableManager.java:174)
    skin.support.content.res.SkinCompatResources.getSkinDrawableCompat(SkinCompatResources.java:187)
    skin.support.content.res.SkinCompatResources.getDrawableCompat(SkinCompatResources.java:252)
    skin.support.widget.SkinCompatBackgroundHelper.applySkin(SkinCompatBackgroundHelper.java:49)
    skin.support.widget.SkinCompatBackgroundHelper.loadFromAttributes(SkinCompatBackgroundHelper.java:35)
    skin.support.widget.SkinCompatTextView.<init>(SkinCompatTextView.java:27)
    skin.support.widget.SkinCompatTextView.<init>(SkinCompatTextView.java:21)
    skin.support.app.SkinCompatViewInflater.createViewFromFV(SkinCompatViewInflater.java:146)
    skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:91)
    skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:63)
    skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:37)
    android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
    android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    android.view.View.inflate(View.java:23454)
    com.motoband.ui.view.TPMSRidingView.initView(TPMSRidingView.java:44)
    com.motoband.ui.view.TPMSRidingView.<init>(TPMSRidingView.java:35)
    java.lang.reflect.Constructor.newInstance0(Native Method)
    java.lang.reflect.Constructor.newInstance(Constructor.java:334)
    skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:289)
    skin.support.app.SkinCompatViewInflater.createViewFromTag(SkinCompatViewInflater.java:238)
    skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:103)
    skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:63)
    skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:37)
    android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
    android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
    android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    android.view.LayoutInflater.parseInclude(LayoutInflater.java:995)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
2020-03-04 10:32:08.116 24541-25124/com.motoband E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#

**Comment by xiaoxing1992** [comment]
2020-03-04 10:32:08.116 24541-25124/  E/CrashReport: SIGBUS(BUS_ADRERR)
    0xcad811f8
    #00    pc 000252c6    /system/lib/libandroidfw.so (_ZNK7android13ResStringPool13indexOfStringEPKDsj+53) [armeabi-v7a::23a7c7e9204b1a993a7e7e494523de5b]
    #01    pc 0002a36f    /system/lib/libandroidfw.so (_ZNK7android8ResTable17identifierForNameEPKDsjS2_jS2_jPj+462) [armeabi-v7a::23a7c7e9204b1a993a7e7e494523de5b]
    #02    pc 000a9cad    /system/lib/libandroid_runtime.so [armeabi-v7a::55b53e1e41508c563a8744f056b56015]
    #03    pc 009b8a8b    /system/framework/arm/boot-framework.oat (oatexec+3979915) [armeabi::2b0d5689266c18edf262446a78665419]
    java:
    android.content.res.ResourcesImpl.getIdentifier(ResourcesImpl.java:275)
    android.content.res.Resources.getIdentifier(Resources.java:1923)
    skin.support.content.res.SkinCompatResources.getTargetResId(SkinCompatResources.java:104)
    skin.support.content.res.SkinCompatResources.getSkinValue(SkinCompatResources.java:230)
    skin.support.content.res.SkinCompatResources.getValue(SkinCompatResources.java:260)
    skin.support.content.res.SkinCompatDrawableManager.createDrawableIfNeeded(SkinCompatDrawableManager.java:220)
    skin.support.content.res.SkinCompatDrawableManager.getDrawable(SkinCompatDrawableManager.java:183)
    skin.support.content.res.SkinCompatDrawableManager.getDrawable(SkinCompatDrawableManager.java:174)
    skin.support.content.res.SkinCompatResources.getSkinDrawableCompat(SkinCompatResources.java:187)
    skin.support.content.res.SkinCompatResources.getDrawableCompat(SkinCompatResources.java:252)
    skin.support.widget.SkinCompatBackgroundHelper.applySkin(SkinCompatBackgroundHelper.java:49)
    skin.support.widget.SkinCompatBackgroundHelper.loadFromAttributes(SkinCompatBackgroundHelper.java:35)
    skin.support.widget.SkinCompatTextView.<init>(SkinCompatTextView.java:27)
    skin.support.widget.SkinCompatTextView.<init>(SkinCompatTextView.java:21)
    skin.support.app.SkinCompatViewInflater.createViewFromFV(SkinCompatViewInflater.java:146)
    skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:91)
    skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:63)
    skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:37)
    android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
    android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    android.view.View.inflate(View.java:23454)
    com.motoband.ui.view.TPMSRidingView.initView(TPMSRidingView.java:44)
    com.motoband.ui.view.TPMSRidingView.<init>(TPMSRidingView.java:35)
    java.lang.reflect.Constructor.newInstance0(Native Method)
    java.lang.reflect.Constructor.newInstance(Constructor.java:334)
    skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:289)
    skin.support.app.SkinCompatViewInflater.createViewFromTag(SkinCompatViewInflater.java:238)
    skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:103)
    skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:63)
    skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:37)
    android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
    android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
    android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    android.view.LayoutInflater.parseInclude(LayoutInflater.java:995)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:859)

**Comment by xiaoxing1992** [comment]
2020-03-04 10:32:08.116 24541-25124/com.motoband E/CrashReport: SIGBUS(BUS_ADRERR)
    0xcad811f8
    #00    pc 000252c6    /system/lib/libandroidfw.so (_ZNK7android13ResStringPool13indexOfStringEPKDsj+53) [armeabi-v7a::23a7c7e9204b1a993a7e7e494523de5b]
    #01    pc 0002a36f    /system/lib/libandroidfw.so (_ZNK7android8ResTable17identifierForNameEPKDsjS2_jS2_jPj+462) [armeabi-v7a::23a7c7e9204b1a993a7e7e494523de5b]
    #02    pc 000a9cad    /system/lib/libandroid_runtime.so [armeabi-v7a::55b53e1e41508c563a8744f056b56015]
    #03    pc 009b8a8b    /system/framework/arm/boot-framework.oat (oatexec+3979915) [armeabi::2b0d5689266c18edf262446a78665419]
    java:
    android.content.res.ResourcesImpl.getIdentifier(ResourcesImpl.java:275)
    android.content.res.Resources.getIdentifier(Resources.java:1923)
    skin.support.content.res.SkinCompatResources.getTargetResId(SkinCompatResources.java:104)
    skin.support.content.res.SkinCompatResources.getSkinValue(SkinCompatResources.java:230)
    skin.support.content.res.SkinCompatResources.getValue(SkinCompatResources.java:260)
    skin.support.content.res.SkinCompatDrawableManager.createDrawableIfNeeded(SkinCompatDrawableManager.java:220)
    skin.support.content.res.SkinCompatDrawableManager.getDrawable(SkinCompatDrawableManager.java:183)
    skin.support.content.res.SkinCompatDrawableManager.getDrawable(SkinCompatDrawableManager.java:174)
    skin.support.content.res.SkinCompatResources.getSkinDrawableCompat(SkinCompatResources.java:187)
    skin.support.content.res.SkinCompatResources.getDrawableCompat(SkinCompatResources.java:252)
    skin.support.widget.SkinCompatBackgroundHelper.applySkin(SkinCompatBackgroundHelper.java:49)
    skin.support.widget.SkinCompatBackgroundHelper.loadFromAttributes(SkinCompatBackgroundHelper.java:35)
    skin.support.widget.SkinCompatTextView.<init>(SkinCompatTextView.java:27)
    skin.support.widget.SkinCompatTextView.<init>(SkinCompatTextView.java:21)
    skin.support.app.SkinCompatViewInflater.createViewFromFV(SkinCompatViewInflater.java:146)
    skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:91)
    skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:63)
    skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:37)
    android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
    android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    android.view.LayoutInflater.inflate(LayoutInflater.java:374)

    java.lang.reflect.Constructor.newInstance0(Native Method)
    java.lang.reflect.Constructor.newInstance(Constructor.java:334)
    skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:289)
    skin.support.app.SkinCompatViewInflater.createViewFromTag(SkinCompatViewInflater.java:238)
    skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:103)
    skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:63)
    skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:37)
    android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
    android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
    android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    android.view.LayoutInflater.parseInclude(LayoutInflater.java:995)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:859)

**Comment by xiaoxing1992** [comment]
2020-03-04 10:32:08.116 24541-25124/E/CrashReport: SIGBUS(BUS_ADRERR)
    0xcad811f8
    #00    pc 000252c6    /system/lib/libandroidfw.so (_ZNK7android13ResStringPool13indexOfStringEPKDsj+53) [armeabi-v7a::23a7c7e9204b1a993a7e7e494523de5b]
    #01    pc 0002a36f    /system/lib/libandroidfw.so (_ZNK7android8ResTable17identifierForNameEPKDsjS2_jS2_jPj+462) [armeabi-v7a::23a7c7e9204b1a993a7e7e494523de5b]
    #02    pc 000a9cad    /system/lib/libandroid_runtime.so [armeabi-v7a::55b53e1e41508c563a8744f056b56015]
    #03    pc 009b8a8b    /system/framework/arm/boot-framework.oat (oatexec+3979915) [armeabi::2b0d5689266c18edf262446a78665419]
    java:
    android.content.res.ResourcesImpl.getIdentifier(ResourcesImpl.java:275)
    android.content.res.Resources.getIdentifier(Resources.java:1923)
    skin.support.content.res.SkinCompatResources.getTargetResId(SkinCompatResources.java:104)
    skin.support.content.res.SkinCompatResources.getSkinValue(SkinCompatResources.java:230)
    skin.support.content.res.SkinCompatResources.getValue(SkinCompatResources.java:260)
    skin.support.content.res.SkinCompatDrawableManager.createDrawableIfNeeded(SkinCompatDrawableManager.java:220)
    skin.support.content.res.SkinCompatDrawableManager.getDrawable(SkinCompatDrawableManager.java:183)
    skin.support.content.res.SkinCompatDrawableManager.getDrawable(SkinCompatDrawableManager.java:174)
    skin.support.content.res.SkinCompatResources.getSkinDrawableCompat(SkinCompatResources.java:187)
    skin.support.content.res.SkinCompatResources.getDrawableCompat(SkinCompatResources.java:252)
    skin.support.widget.SkinCompatBackgroundHelper.applySkin(SkinCompatBackgroundHelper.java:49)
    skin.support.widget.SkinCompatBackgroundHelper.loadFromAttributes(SkinCompatBackgroundHelper.java:35)
    skin.support.widget.SkinCompatTextView.<init>(SkinCompatTextView.java:27)
    skin.support.widget.SkinCompatTextView.<init>(SkinCompatTextView.java:21)
    skin.support.app.SkinCompatViewInflater.createViewFromFV(SkinCompatViewInflater.java:146)
    skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:91)
    skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:63)
    skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:37)
    android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
    android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    java.lang.reflect.Constructor.newInstance0(Native Method)
    java.lang.reflect.Constructor.newInstance(Constructor.java:334)
    skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:289)
    skin.support.app.SkinCompatViewInflater.createViewFromTag(SkinCompatViewInflater.java:238)
    skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:103)
    skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:63)
    skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:37)
    android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
    android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
    android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    android.view.LayoutInflater.parseInclude(LayoutInflater.java:995)
    android.view.LayoutInflater.rInflate(LayoutInflater.java:859)

**Comment by Mr-litao** [comment]
@ximsfei 请问下这个问题怎么解决

**Comment by KAImportad** [comment]
请问解决了吗，遇到了相同的问题

**Comment by jarkeet** [comment]
请问解决了吗？ 我这边也会偶发出现，但是不知道怎么解决 @KAImportad @steven2947
