### ISSUE TITLE
讲support包升级为28.0.0后，ColorStateList报错

### ISSUE THREAD

**Issue by yumi0629** [ximsfei/Android-skin-support#299]
将support包从27升级至28时，使用```SkinCompatResources.getColorStateList()```方法会抛出运行时异常（已捕捉未崩溃），但是会导致获取不到颜色值，导致手机显示紫红色的很怪异的颜色。
```
ColorStateList color/mtrl_tabs_legacy_text_color_selector has unresolved theme attributes!
             Consider using Resources.getColorStateList(int, Theme)
             or Context.getColorStateList(int)
        at android.content.res.Resources.getColorStateList(Resources.java:1011)
```

**Comment by noobfresh** [comment]
同遇到

**Comment by noobfresh** [comment]
这个问题，我是在华为机型Mate10，EMUI 9.0上遇到。后来找到相应解决方法，原来获取颜色的方法，根据版本修改成 高版本使用：Resources.getColorStateList(int, Theme)即可。
根据这个警告说的来处理就行

**Comment by hxingever** [comment]
> 将support包从27升级至28时，使用`SkinCompatResources.getColorStateList()`方法会抛出运行时异常（已捕捉未崩溃），但是会导致获取不到颜色值，导致手机显示紫红色的很怪异的颜色。
> 
> ```
> ColorStateList color/mtrl_tabs_legacy_text_color_selector has unresolved theme attributes!
>              Consider using Resources.getColorStateList(int, Theme)
>              or Context.getColorStateList(int)
>         at android.content.res.Resources.getColorStateList(Resources.java:1011)
> ```

遇到同样的问题  求解决方案 贴个代码片最好了  谢谢
