### ISSUE TITLE
drawable 里面的shape文件怎么更换颜色？

### ISSUE THREAD

**Issue by willsame** [ximsfei/Android-skin-support#30]
drawable 里面的shape文件怎么更换颜色？我设置了setBackgroundResource(R.drawable.xxx);发现没有用

**Comment by ximsfei** [comment]
[Demo](https://github.com/ximsfei/Android-skin-support/blob/master/skin-app/src/main/res/drawable/bg_bar.xml)里有 :)

**Comment by willsame** [comment]
已经解决了，谢谢
