### ISSUE TITLE
为什么一定要用V7包的主题，原理是什么？

### ISSUE THREAD

**Issue by LINYIQIANG** [ximsfei/Android-skin-support#302]
https://github.com/ximsfei/Android-skin-support/blob/master/docs/FAQ.md 
为什么使用了V7的控件一定要用V7包的主题，原理是什么，请大神解释一下。我因为项目原因不能继承V7的主题，我有么有其他方案处理，避免去继承V7的主题。请大神解答谢谢！

**Comment by getglory** [comment]
你发的链接里不就有回答吗。因为框架所有的View都是继承自v7包的下的View。通过设置LayoutInflater.Factory2将布局中的TextView替换成SkinCompatTextView，而SkinCompatTextView是继承自AppCompatTextView。AppCompatActivity的风格与Activity不同也是通过设置Factory动态将控件替换掉的。

**Comment by getglory** [comment]
具体的解决方法你可以加群问下作者看看
