### ISSUE TITLE
support库 compileSdkVersion = 28, supportLibraryVersion = 28.0.0,会报错

### ISSUE THREAD

**Issue by yuluowusheng** [ximsfei/Android-skin-support#307]
是因为api28修改了AppCompatDelegateImpl的实现，统一了AppCompatDelegate，我已经修改完了，但是如果用的话要全部源码依赖，太麻烦了，大大能否在闲暇之余发个新版本支持下呢？我们的项目还没升级androix😭

**Comment by ximsfei** [comment]
已经修复了3.1.3版本，你试下？

**Comment by yuluowusheng** [comment]
好了呢，亲，感谢
