### ISSUE TITLE
fragment使用 FragmentTransaction.replace的方式加载，换肤不生效

### ISSUE THREAD

**Issue by yuluowusheng** [ximsfei/Android-skin-support#308]
<FrameLayout
        android:id="@+id/realtabcontent"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginBottom="@dimen/px100" />
这是fragment载体，可能是我犯了什么低级错误，但是实在找不出来了，大大能否提供点建议，为我解决这个问题，指引下方向😭

**Comment by yuluowusheng** [comment]
FrameLayout
        android:id="@+id/realtabcontent"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginBottom="@dimen/px100"

**Comment by ximsfei** [comment]
你的View是通过LayoutInflater创建的么？

**Comment by yuluowusheng** [comment]
if (mHomeFrameLayout == null) {
            mHomeFrameLayout = (FrameLayout) inflater.inflate(R.layout.home_page_main_layout, container, false);
}
        return mHomeFrameLayout;
是的

**Comment by ximsfei** [comment]
提供一个demo吧，这样看不出来。。。也许写demo的时候，就发现问题了

**Comment by yuluowusheng** [comment]
[fragmenterror.zip](https://github.com/ximsfei/Android-skin-support/files/3595085/fragmenterror.zip)
大大写了个不成功的demo，有时间的时候还请帮忙瞅一瞅

**Comment by yuluowusheng** [comment]
找到问题了，卧槽，打扰大大了

**Comment by ximsfei** [comment]
啥问题，学习下。。。

**Comment by yuluowusheng** [comment]
Activity的根view的setfactory被重写了。。

**Comment by YousYu** [comment]
请问一下这个是怎么解决的？我的也没有重写那个方法

**Comment by YousYu** [comment]
> Activity的根view的setfactory被重写了。。

请问一下这个是怎么解决的？我的也没有重写那个方法

**Comment by YousYu** [comment]
> 啥问题，学习下。。。

请问一下这个是怎么解决的？我的也没有重写那个方法
