### ISSUE TITLE
shape 文件，里面的gradient 失效了。

### ISSUE THREAD

**Issue by willsame** [ximsfei/Android-skin-support#31]
<shape xmlns:android="http://schemas.android.com/apk/res/android">

    <gradient
        android:startColor="@color/white"   // white 是 #ffffff 色
        android:endColor="@color/cfbf1f2"
        android:angle="0" />
</shape>

然后是在 RecyclerView 里面
 为LinearLayout 设置的一个 渐变色
 viewholder.itemRootview.setBackgroundResource(Constant.quote_default_bg);
// quote_default_bg = R.drawable.quote_default_gradient;   quote_default_gradient是上面的shape文件
发现设置的渐变背景色没有了，皮肤包里面也有对应的资源文件，不知道是什么原因

**Comment by ximsfei** [comment]
[gradient-shape](https://github.com/ximsfei/Android-skin-support/blob/master/skin-app/src/main/res/layout/fragment.xml) 看一下这个demo :)
