### ISSUE TITLE
androidx 状态栏失效

### ISSUE THREAD

**Issue by qsw-net** [ximsfei/Android-skin-support#311]
androidx 状态栏失效

**Comment by qsw-net** [comment]
3.1.4 状态栏 没有问题，4.0.4无效了

**Comment by qsw-net** [comment]
3.1.4换肤后 退出在进 状态栏换肤无效

**Comment by hezihaog** [comment]
+1

**Comment by NaoiAyato** [comment]
用被折叠的Toolbar的颜色代替沉浸状态栏，可以配合https://github.com/gyf-dev/ImmersionBar 这个解决
