### ISSUE TITLE
在aar工程中使用插件换肤的问题

### ISSUE THREAD

**Issue by roylwt** [ximsfei/Android-skin-support#312]
我在aar工程中使用了插件换肤的方式，在主工程引用aar后，调用SkinCompatManager.getInstance().loadSkin()后回调了onSuccess()，但是换肤没有成功，请问是为什么？

**Comment by roylwt** [comment]
使用应用内换肤的方式也不好使

**Comment by xxxga0** [comment]
你好，请问你是怎么解决这个问题的呢？
