### ISSUE TITLE
MpAndroidChart中坐标轴换肤

### ISSUE THREAD

**Issue by swallowsonny** [ximsfei/Android-skin-support#316]
MpAndroidChart中坐标轴该如何换肤呢，能否提供个思路

**Comment by wowo3129** [comment]
你説的太隨意了，可以贴个你写的简易demo，不然谁都不知道你怎么画的坐标轴，更何况帮忙解

**Comment by ximsfei** [comment]
可以参考[自定义属性](https://github.com/ximsfei/Android-skin-support/issues/344#issuecomment-632977418)换肤
