### ISSUE TITLE
关于PackageManager.getResourcesForApplication（）方法

### ISSUE THREAD

**Issue by Dan-Humphrey** [ximsfei/Android-skin-support#317]
![image](https://user-images.githubusercontent.com/52402754/66386281-8a1d9f80-e9f4-11e9-8320-7fdf82c75707.png)

大佬，想问下getResourcesForApplication（）方法为什么可以返回一个未安装的皮肤包的资源对象，未安装的应用不是会抛NameNotFoundException么。
我看插件式换肤和指定sdcard路径换肤都是走这里。

**Comment by ximsfei** [comment]
![Uploading image.png…]()
