### ISSUE TITLE
作者可以提供 完整的案例吗

### ISSUE THREAD

**Issue by KunMinX** [ximsfei/Android-skin-support#319]
不要求多么复杂的案例，只是常见的像 首页、详情 这样的场景，提供 一两个 白天黑夜 的切换看看。
因为目前 demo 跑起来，实在看不出这个皮肤库 最终能做到什么程度的效果，

**Comment by ximsfei** [comment]
https://github.com/ximsfei/Skin-Demo

很早以前做过一个demo，可以参考
