### ISSUE TITLE
TextView 的setBackgroundColor()方法失效, setBackgroundResource()可以

### ISSUE THREAD

**Issue by laiqurufeng** [ximsfei/Android-skin-support#32]
setBackgroundColor()在 6.0版本上无效, 4.4.2版本上正常.
复现方法 :PopupWindow 上动态更改 TextView背景的颜色

**Comment by ximsfei** [comment]
setBackgroundColor 不支持换肤 :)

**Comment by laiqurufeng** [comment]
setBackgroundColor 不支持换肤 :)

不是支不支持换肤的问题. setBackgroundColor()动态更改背景颜色无效了.
SkinCompatViewInflater 中 把TextView 替换成AppCompatTextView, 调用setBackgroundColor()有效果的.

看了下代码,SkinCompatBackgroundHelper代码的问题.
