### ISSUE TITLE
EditText的光标怎么换肤？

### ISSUE THREAD

**Issue by dev-fancyluo** [ximsfei/Android-skin-support#322]
默认是取的colorAccent的颜色，但是我设置了colorAccent_blue没有效果

**Comment by ximsfei** [comment]
反射自行实现，需要考虑不同rom的兼容性问题

**Comment by dev-fancyluo** [comment]
> 反射自行实现，需要考虑不同rom的兼容性问题

这个是要自定义View方式，在applySkin里面实现？

**Comment by dev-fancyluo** [comment]
`public class CustomSkinEditText extends SkinCompatEditText {

    private int resId;

    public CustomSkinEditText(Context context) {
        super(context);
        setup(context);
    }

    public CustomSkinEditText(Context context, AttributeSet attrs) {
        super(context, attrs);
        setup(context);
    }

    private void setup(Context context) {
        resId = R.drawable.common_edittext_cursor_drawable;
        setCursorSkin();
    }

    @Override
    public void applySkin() {
        super.applySkin();
        setCursorSkin();
    }

    private void setCursorSkin() {
        try {
            Field f = TextView.class.getDeclaredField("mCursorDrawableRes");
            f.setAccessible(true);
            f.set(this, resId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}`
我这样使用有问题吗？但是没有换肤的效果

**Comment by ximsfei** [comment]
> public class CustomSkinEditText extends SkinCompatEditText {
> 
> ```
> private int resId;
> 
> public CustomSkinEditText(Context context) {
>     super(context);
>     setup(context);
> }
> 
> public CustomSkinEditText(Context context, AttributeSet attrs) {
>     super(context, attrs);
>     setup(context);
> }
> 
> private void setup(Context context) {
>     resId = R.drawable.common_edittext_cursor_drawable;
>     setCursorSkin();
> }
> 
> @Override
> public void applySkin() {
>     super.applySkin();
>     setCursorSkin();
> }
> 
> private void setCursorSkin() {
>     try {
>         Field f = TextView.class.getDeclaredField("mCursorDrawableRes");
>         f.setAccessible(true);
>         f.set(this, resId);
>     } catch (Exception e) {
>         e.printStackTrace();
>     }
> }
> ```
> 
> }
> 我这样使用有问题吗？但是没有换肤的效果

不对，参考下自定义view换肤

**Comment by dev-fancyluo** [comment]
```   
 public static void setCursorDrawableColor(EditText editText, int resId) {
        try {
            Field f = TextView.class.getDeclaredField("mCursorDrawableRes");
            f.setAccessible(true);
            f.set(editText, resId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
我这段代码要使用的是资源ID的引用，但是框架目前只能使用 
 `SkinCompatResources.getDrawable(getContext(),resId)` 获取drawable才有换肤效果，有没有可以使用资源Id也能换肤的api？
