### ISSUE TITLE
AppCompat has already installed itself into the Window崩溃，紧急！

### ISSUE THREAD

**Issue by jerryaisa** [ximsfei/Android-skin-support#324]
![image](https://user-images.githubusercontent.com/11827807/68637432-9045f500-0539-11ea-853e-74b52a43c7c0.png)

大大好，我们接入这个库之后，存在一个崩溃！
我们
SkinCompatManager.getInstance().setSkinAllActivityEnable(false);
关闭了全局夜间，只在需要的页面，通过SkinCompatSupportable来完成换肤
MvpBaseActivity继承于AppCompatActivity，所以实现了getDelegate()方法
但是现在出现了20个用户崩溃，bugly抓到的错误就是
AppCompat has already installed itself into the Window
应该如何解决？

**Comment by 287138531** [comment]
> ![image](https://user-images.githubusercontent.com/11827807/68637432-9045f500-0539-11ea-853e-74b52a43c7c0.png)
> 
> 大大好，我们接入这个库之后，存在一个崩溃！
> 我们
> SkinCompatManager.getInstance().setSkinAllActivityEnable(false);
> 关闭了全局夜间，只在需要的页面，通过SkinCompatSupportable来完成换肤
> MvpBaseActivity继承于AppCompatActivity，所以实现了getDelegate()方法
> 但是现在出现了20个用户崩溃，bugly抓到的错误就是
> AppCompat has already installed itself into the Window
> 应该如何解决？

大佬，解决了吗？是不是都是miui android版本是9.0 的奔溃？

**Comment by yuanjunli** [comment]
目前的处理方案参考AppCompatActivity
`@NonNull
    public AppCompatDelegate getDelegate() {
        if (mDelegate == null) {
            mDelegate = AppCompatDelegate.create(this, this);
        }
        return mDelegate;
    }`

将
`override fun getDelegate(): AppCompatDelegate {
    return SkinAppCompatDelegateImpl.get(this, this)
  }`

改成(自己存储本地变量mDelegate)
‘@NonNull
    public AppCompatDelegate getDelegate() {
        if (mDelegate == null) {
            mDelegate = SkinAppCompatDelegateImpl.get(this, this);
        }
        return mDelegate;
    }’
