### ISSUE TITLE
切换主题后SwitchPreference失效

### ISSUE THREAD

**Issue by zivids** [ximsfei/Android-skin-support#326]
切换主题后SwitchPreference的check界面状态失效

**Comment by zivids** [comment]
切换主题后回到设置界面将状态栏设置为decorView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR)后SwitchPreference点击check动画效果失效

**Comment by ximsfei** [comment]
暂未发现这个问题，是否可以提供代码示例？
