### ISSUE TITLE
SkinMaterialTabLayout 文案换肤无效？

### ISSUE THREAD

**Issue by Connor4** [ximsfei/Android-skin-support#327]
``
<skin.support.design.widget.SkinMaterialTabLayout
            android:id="@+id/tab_layout"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            app:tabIndicatorColor="@color/test_tab_layout_indicator"
            app:tabSelectedTextColor="@color/test_tab_layout_text_select"
            app:tabTextColor="@color/test_tab_layout_text_normal" />
``
以及
res - value - colors目录下
``
   <color name="test_tab_layout_text_select">#477aac</color>
    <color name="test_tab_layout_text_normal">#ce3d3a</color>
    <color name="test_tab_layout_indicator">#009688</color>
``
res-night - value -colors目录下
``
    <color name="test_tab_layout_text_select_night">#F3F90E</color>
    <color name="test_tab_layout_text_normal_night">#7583C5</color>
    <color name="test_tab_layout_indicator_night">#C279ED</color>
``

使用demo中的夜间模式 - 应用内换肤，tabLayout中的文案并没有按照预期变换颜色，但是indicator是有正常变换颜色的。

**Comment by 282144757** [comment]
你这个控件换肤还有问题吗？

**Comment by Connor4** [comment]
有啊，然后我用skincompattablayout代码复制出来，在applyskin()中用延时后再执行里面的代码就正常换肤了



发自我的小米手机在 levy <notifications@github.com>，2019年11月26日 17:43写道：你这个控件换肤还有问题吗？



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ximsfei/Android-skin-support/issues/327?email_source=notifications\u0026email_token=ADIR6WCLH6ZH22RCZQZRULLQVTVSVA5CNFSM4JREVU72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFFMIVA#issuecomment-558548052",

"url": "https://github.com/ximsfei/Android-skin-support/issues/327?email_source=notifications\u0026email_token=ADIR6WCLH6ZH22RCZQZRULLQVTVSVA5CNFSM4JREVU72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFFMIVA#issuecomment-558548052",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by 282144757** [comment]
用你的延时办法后，是解决了这个问题！

**Comment by a615696671** [comment]
@Override
    public void applySkin() {
        this.post(new Runnable() {
            @Override
            public void run() {
                mTabIndicatorColorResId = SkinCompatHelper.checkResourceId(mTabIndicatorColorResId);
                if (mTabIndicatorColorResId != INVALID_ID) {
                    setSelectedTabIndicatorColor(SkinCompatResources.getColor(getContext(), mTabIndicatorColorResId));
                }
                mTabTextColorsResId = SkinCompatHelper.checkResourceId(mTabTextColorsResId);
                if (mTabTextColorsResId != INVALID_ID) {
                    setTabTextColors(SkinCompatResources.getColorStateList(getContext(), mTabTextColorsResId));
                }
                mTabSelectedTextColorResId = SkinCompatHelper.checkResourceId(mTabSelectedTextColorResId);
                if (mTabSelectedTextColorResId != INVALID_ID) {
                    int selected = SkinCompatResources.getColor(getContext(), mTabSelectedTextColorResId);
                    if (getTabTextColors() != null) {
                        setTabTextColors(getTabTextColors().getDefaultColor(), selected);
                    }
                }
            }
        });
    }
为啥要post 一下 真搞不懂

**Comment by winfredzen** [comment]
同样遇到这样的问题，第一次换肤有效，第二次 、第三次就没有效果了，最后看到这里，试了下延时，就有效果了
