### ISSUE TITLE
RecyclerView换肤问题，

### ISSUE THREAD

**Issue by llx547305571** [ximsfei/Android-skin-support#329]
看到之前issue中有说用类自定义view的方式实现RecyclerView的换肤，但是我自定义了好像还是达不到效果，能帮忙看看是缺失了什么地方吗？

`public class SkinCompatRecyclerView extends RecyclerView implements SkinCompatSupportable {

    private SkinCompatBackgroundHelper mBackgroundTintHelper;

    public SkinCompatRecyclerView(@NonNull Context context) {
        super(context, null);
    }

    public SkinCompatRecyclerView(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs, 0);
    }

    public SkinCompatRecyclerView(@NonNull Context context, @Nullable AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        mBackgroundTintHelper = new SkinCompatBackgroundHelper(this);
        mBackgroundTintHelper.loadFromAttributes(attrs, defStyle);

    }

    @Override
    public void setBackgroundResource(int resId) {
        super.setBackgroundResource(resId);
        if (mBackgroundTintHelper != null) {
            mBackgroundTintHelper.onSetBackgroundResource(resId);
        }
    }

    @Override
    public void applySkin() {
        if (mBackgroundTintHelper != null) {
            mBackgroundTintHelper.applySkin();
        }
    }
}`

**Comment by DaveBoy** [comment]
你的构造里面没调用applyskin

**Comment by ximsfei** [comment]
![image](https://user-images.githubusercontent.com/9425734/82720785-60965780-9ce9-11ea-9344-ca45fead8724.png)
![image](https://user-images.githubusercontent.com/9425734/82720788-68ee9280-9ce9-11ea-8eed-c21926565d9d.png)
xml布局文件中的View，会走两个参数的构造方法
