### ISSUE TITLE
Textview textColor属性 引用 drawable的生效 但是引用color就不生效

### ISSUE THREAD

**Issue by KevinDestinydoor** [ximsfei/Android-skin-support#332]
res 包下的values 的 colors.xml

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
        <color name="main_toolbar_title">@android:color/white</color>
     <color name="main_screen_text">#4cddff</color>
    <color name="buttonTextColorSelected">#151418</color>
    <color name="buttonTextColorNormal">#4cddff</color>
</resources>

```

 res-pink 包下的values 的 colors.xml
```
<resources>
    <color name="main_toolbar_title_pink">#7C4E57</color>
    <color name="main_screen_text_pink">#FFDCE3</color>
    <color name="buttonTextColorSelected_pink">#7C4E57</color>
    <color name="buttonTextColorNormal_pink">#EDE3B5</color>
</resources>

```

**Comment by KevinDestinydoor** [comment]
`
   <TextView
                        android:id="@+id/tv_title"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_vertical"
                        android:layout_marginLeft="16dp"
                        android:layout_marginRight="16dp"
                        android:ellipsize="end"
                        android:fontFamily="@font/arial_b"
                        android:lines="1"
                        android:text="@string/super_volume_booster"
                        android:textColor="@color/main_toolbar_title"
                        android:textSize="16sp" />`

**Comment by KevinDestinydoor** [comment]
不过， 继承了SkinCompatTextView的TextView也有效 ， 就是直接用TextView不行

**Comment by KevinDestinydoor** [comment]
我解决了这个问题。 我res包的`<color name="main_toolbar_title">@android:color/white</color>`
改成了<color name="main_toolbar_title">#ffffffff</color>

成功了。 不知道为什么

**Comment by DaveBoy** [comment]
可能是因为他存的id，check的时候判定为无效了吧   具体你断点一下就知道了

**Comment by ximsfei** [comment]
@DaveBoy @KevinDestinydoor 框架是根据属性名`main_toolbar_title`去找皮肤包里对应资源的；

`<color name="main_toolbar_title">@android:color/white</color>`，这个写法，最终解析出来的属性名是`white`，不是`main_toolbar_title`
