### ISSUE TITLE
能不能添加支持tint换肤呢?

### ISSUE THREAD

**Issue by NaclFire** [ximsfei/Android-skin-support#333]
如果加了这个功能,皮肤制作可以节省很多时间了,谢谢

**Comment by NaclFire** [comment]
虽然说可以通过自定义view来支持tint换肤,但是如果项目已经完成,这时再用自定义view的方式使用tint,那每个需要换肤的view都需要重新替换,工作量还是不小的

**Comment by DaveBoy** [comment]
你自己加一个自定义imageview不就得了。。。等更新估计要等一段时间

**Comment by NaclFire** [comment]
> 你自己加一个自定义imageview不就得了。。。等更新估计要等一段时间

我添加了自定义imageview了,然后还要替换几十个普通imageview,所以来提了个建议

**Comment by DaveBoy** [comment]
为啥要替换  直接加个属性  就行了呀  然后拦截创建那里替换一个地方就行了。。。

**Comment by DaveBoy** [comment]
```
<ImageView
                
                    app:skinTint="@color/main_player_control"
                    android:src="@drawable/skin_play"

                    />
```

**Comment by NaclFire** [comment]
> 为啥要替换 直接加个属性 就行了呀 然后拦截创建那里替换一个地方就行了。。。

我刚接触这个换肤,是这么写的:
public class SkinCompatTintImageView extends SkinCompatImageView {
    private static final int[] TINT_ATTRS = {
            android.R.attr.tint
    };
    private int resourceId;

    public SkinCompatTintImageView(Context context) {
        this(context, null);
    }

    public SkinCompatTintImageView(Context context, AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public SkinCompatTintImageView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        TypedArray typedArray = context.obtainStyledAttributes(attrs, TINT_ATTRS, defStyleAttr, 0);
        if (typedArray.hasValue(0)) {
            resourceId = typedArray.getResourceId(0, INVALID_ID);
        }
        typedArray.recycle();
        int i = SkinCompatHelper.checkResourceId(resourceId);
        if (i != INVALID_ID) {
            ColorStateList colorStateList = SkinCompatResources.getColorStateList(getContext(), i);
            if (colorStateList != null) {
                setImageTintList(colorStateList);
            }

        }

    }

    @Override
    public void applySkin() {
        super.applySkin();
    }
}

**Comment by DaveBoy** [comment]
> > 为啥要替换 直接加个属性 就行了呀 然后拦截创建那里替换一个地方就行了。。。
> 
> 我刚接触这个换肤,是这么写的:
> 
> ```
> public class SkinCompatTintImageView extends SkinCompatImageView {
>     private static final int[] TINT_ATTRS = {
>             android.R.attr.tint
>     };
>     private int resourceId;
> 
>     public SkinCompatTintImageView(Context context) {
>         this(context, null);
>     }
> 
>     public SkinCompatTintImageView(Context context, AttributeSet attrs) {
>         this(context, attrs, 0);
>     }
> 
>     public SkinCompatTintImageView(Context context, AttributeSet attrs, int defStyleAttr) {
>         super(context, attrs, defStyleAttr);
>         TypedArray typedArray = context.obtainStyledAttributes(attrs, TINT_ATTRS, defStyleAttr, 0);
>         if (typedArray.hasValue(0)) {
>             resourceId = typedArray.getResourceId(0, INVALID_ID);
>         }
>         typedArray.recycle();
>         int i = SkinCompatHelper.checkResourceId(resourceId);
>         if (i != INVALID_ID) {
>             ColorStateList colorStateList = SkinCompatResources.getColorStateList(getContext(), i);
>             if (colorStateList != null) {
>                 setImageTintList(colorStateList);
>             }
> 
>         }
> 
>     }
> 
>     @Override
>     public void applySkin() {
>         super.applySkin();
>     }
> }
> ```

肯定不行  你这个只在构造里面。。。要放在helper里面
我的写法，你可以借鉴一下，自己做下修改

```
class CustomSkinCompatImageHelper(imageView: ImageView) : SkinCompatHelper() {
    private val mView: ImageView = imageView
    private var mSrcResId = INVALID_ID
    private var mSrcCompatResId = INVALID_ID
    private var mTintResID = INVALID_ID
    var hasDrawable = false
    private var mTintEnableFlag = INVALID_ID
    fun loadFromAttributes(attrs: AttributeSet?, defStyleAttr: Int) {
        var a: TypedArray? = null
        try {
            a = mView.context.obtainStyledAttributes(attrs, R.styleable.CustomSkinCompatImageView, defStyleAttr, 0)
            mSrcResId = a.getResourceId(R.styleable.CustomSkinCompatImageView_android_src, INVALID_ID)
            mSrcCompatResId = a.getResourceId(R.styleable.CustomSkinCompatImageView_srcCompat, INVALID_ID)
            mTintResID = a.getResourceId(R.styleable.CustomSkinCompatImageView_skinTint, INVALID_ID)
            mTintEnableFlag = a.getInt(R.styleable.CustomSkinCompatImageView_tintEnable, INVALID_ID)
        } finally {
            a?.recycle()
        }
        applySkin()
    }

    fun setImageResource(resId: Int) {
        mSrcResId = resId
        applySkin()
    }

    override fun applySkin() {
        if(mView is SkinCompatCircleImageView){//解决SkinCompatCircleImageView的着色问题
            mView.setColorFilter(null)
        }
        if(hasDrawable){
            return
        }
        /**
         * 图片更换
         */
        mSrcResId = checkResourceId(mSrcResId)
        if (mSrcResId == INVALID_ID) {
            return
        }
        val notTintEnable=mTintResID== INVALID_ID||!ThemeUtil.getTintEnable(mSrcResId,mTintEnableFlag)
        val drawable = SkinCompatVectorResources.getDrawableCompat(mView.context, mSrcResId)
        if (drawable != null) {
            if(notTintEnable) {//如果此时是不可tint的 则先清除之前的tint
                val imageTintList = ImageViewCompat.getImageTintList(mView)
                if(imageTintList!=null){
                    ImageViewCompat.setImageTintList(mView,null)
                }

            }

            mView.setImageDrawable(drawable.mutate())
        }

        /**
         * 图片着色
         */
        if(notTintEnable) {
            return
        }
        try {
            val color = SkinCompatResources.getColorStateList(App.instance.applicationContext,  mTintResID)
            if(mView is SkinCompatCircleImageView){//解决SkinCompatCircleImageView的着色问题
                mView.setColorFilter(color.defaultColor, PorterDuff.Mode.SRC_ATOP)
            }else
                ImageViewCompat.setImageTintList(mView,color)
        }catch (e:Exception){
            e.printStackTraceWhenDebug()
        }

        //logIOld("imageTintListset:${this.hashCode()}",color.toString())


    }
}
```

**Comment by NaclFire** [comment]
> > > 为啥要替换 直接加个属性 就行了呀 然后拦截创建那里替换一个地方就行了。。。
> > 
> > 
> > 我刚接触这个换肤,是这么写的:
> > ```
> > public class SkinCompatTintImageView extends SkinCompatImageView {
> >     private static final int[] TINT_ATTRS = {
> >             android.R.attr.tint
> >     };
> >     private int resourceId;
> > 
> >     public SkinCompatTintImageView(Context context) {
> >         this(context, null);
> >     }
> > 
> >     public SkinCompatTintImageView(Context context, AttributeSet attrs) {
> >         this(context, attrs, 0);
> >     }
> > 
> >     public SkinCompatTintImageView(Context context, AttributeSet attrs, int defStyleAttr) {
> >         super(context, attrs, defStyleAttr);
> >         TypedArray typedArray = context.obtainStyledAttributes(attrs, TINT_ATTRS, defStyleAttr, 0);
> >         if (typedArray.hasValue(0)) {
> >             resourceId = typedArray.getResourceId(0, INVALID_ID);
> >         }
> >         typedArray.recycle();
> >         int i = SkinCompatHelper.checkResourceId(resourceId);
> >         if (i != INVALID_ID) {
> >             ColorStateList colorStateList = SkinCompatResources.getColorStateList(getContext(), i);
> >             if (colorStateList != null) {
> >                 setImageTintList(colorStateList);
> >             }
> > 
> >         }
> > 
> >     }
> > 
> >     @Override
> >     public void applySkin() {
> >         super.applySkin();
> >     }
> > }
> > ```
> 
> 肯定不行 你这个只在构造里面。。。要放在helper里面
> 我的写法，你可以借鉴一下，自己做下修改
> 
> ```
> class CustomSkinCompatImageHelper(imageView: ImageView) : SkinCompatHelper() {
>     private val mView: ImageView = imageView
>     private var mSrcResId = INVALID_ID
>     private var mSrcCompatResId = INVALID_ID
>     private var mTintResID = INVALID_ID
>     var hasDrawable = false
>     private var mTintEnableFlag = INVALID_ID
>     fun loadFromAttributes(attrs: AttributeSet?, defStyleAttr: Int) {
>         var a: TypedArray? = null
>         try {
>             a = mView.context.obtainStyledAttributes(attrs, R.styleable.CustomSkinCompatImageView, defStyleAttr, 0)
>             mSrcResId = a.getResourceId(R.styleable.CustomSkinCompatImageView_android_src, INVALID_ID)
>             mSrcCompatResId = a.getResourceId(R.styleable.CustomSkinCompatImageView_srcCompat, INVALID_ID)
>             mTintResID = a.getResourceId(R.styleable.CustomSkinCompatImageView_skinTint, INVALID_ID)
>             mTintEnableFlag = a.getInt(R.styleable.CustomSkinCompatImageView_tintEnable, INVALID_ID)
>         } finally {
>             a?.recycle()
>         }
>         applySkin()
>     }
> 
>     fun setImageResource(resId: Int) {
>         mSrcResId = resId
>         applySkin()
>     }
> 
>     override fun applySkin() {
>         if(mView is SkinCompatCircleImageView){//解决SkinCompatCircleImageView的着色问题
>             mView.setColorFilter(null)
>         }
>         if(hasDrawable){
>             return
>         }
>         /**
>          * 图片更换
>          */
>         mSrcResId = checkResourceId(mSrcResId)
>         if (mSrcResId == INVALID_ID) {
>             return
>         }
>         val notTintEnable=mTintResID== INVALID_ID||!ThemeUtil.getTintEnable(mSrcResId,mTintEnableFlag)
>         val drawable = SkinCompatVectorResources.getDrawableCompat(mView.context, mSrcResId)
>         if (drawable != null) {
>             if(notTintEnable) {//如果此时是不可tint的 则先清除之前的tint
>                 val imageTintList = ImageViewCompat.getImageTintList(mView)
>                 if(imageTintList!=null){
>                     ImageViewCompat.setImageTintList(mView,null)
>                 }
> 
>             }
> 
>             mView.setImageDrawable(drawable.mutate())
>         }
> 
>         /**
>          * 图片着色
>          */
>         if(notTintEnable) {
>             return
>         }
>         try {
>             val color = SkinCompatResources.getColorStateList(App.instance.applicationContext,  mTintResID)
>             if(mView is SkinCompatCircleImageView){//解决SkinCompatCircleImageView的着色问题
>                 mView.setColorFilter(color.defaultColor, PorterDuff.Mode.SRC_ATOP)
>             }else
>                 ImageViewCompat.setImageTintList(mView,color)
>         }catch (e:Exception){
>             e.printStackTraceWhenDebug()
>         }
> 
>         //logIOld("imageTintListset:${this.hashCode()}",color.toString())
> 
> 
>     }
> }
> ```

这个方式我也尝试过,但是我写完helper不知道怎么用,能不能贴出其他地方使用的代码,谢谢了

**Comment by DaveBoy** [comment]
CustomSkinViewInflater替换成自定义的Imageview
```
class CustomSkinCompatImageView @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0) : AppCompatImageView(context, attrs, defStyleAttr), SkinCompatSupportable {
    private val mBackgroundTintHelper: SkinCompatBackgroundHelper?
    private val mImageHelper: CustomSkinCompatImageHelper?

    init {
        mBackgroundTintHelper = SkinCompatBackgroundHelper(this)
        mBackgroundTintHelper.loadFromAttributes(attrs, defStyleAttr)

        mImageHelper = CustomSkinCompatImageHelper(this)
        mImageHelper.loadFromAttributes(attrs, defStyleAttr)
    }

    override fun setBackgroundResource(@DrawableRes resId: Int) {
        super.setBackgroundResource(resId)
        mBackgroundTintHelper?.onSetBackgroundResource(resId)
    }
    fun setImageDrawableOnly(drawable: Drawable?) {
        /**
         * 因为需求  调用此方法的是glide加载的正常图片  所以不进行tint
         */
        ImageViewCompat.setImageTintList(this,null)
        mImageHelper?.hasDrawable=true
        super.setImageDrawable(drawable)
       // ImageViewCompat.setImageTintList(this,ColorStateList.valueOf(Color.TRANSPARENT))
    }
    override fun setImageResource(@DrawableRes resId: Int) {
        // Intercept this call and instead retrieve the Drawable via the image helper
        mImageHelper?.hasDrawable=false
        mImageHelper?.setImageResource(resId)
    }
    override fun applySkin() {
        mBackgroundTintHelper?.applySkin()
        mImageHelper?.applySkin()
    }

}
```

然后给xml的imageview加个        app:skinTint="@color/play_player_name"属性

**Comment by DaveBoy** [comment]
@NaclFire

**Comment by NaclFire** [comment]
> @NaclFire

好的,我试一下

**Comment by NaclFire** [comment]
> @NaclFire

感谢你的耐心解答,我照你说的方法试了,还是有些地方不清楚,你说的自定义Inflater是仿照SkinCompatViewInflater写的吗?然后这个inflater在哪里使用?

**Comment by DaveBoy** [comment]
```
SkinCompatManager.withoutActivity(this)
                .addInflater(CustomSkinViewInflater())           // 自定义View加载
                .addInflater(SkinAppCompatViewInflater())           // 基础控件换肤初始化
                .addInflater(SkinMaterialViewInflater())            // material design 控件换肤初始化[可选]
                .addInflater(SkinConstraintViewInflater())          // ConstraintLayout 控件换肤初始化[可选]
                .setSkinWindowBackgroundEnable(false)                   // 关闭windowBackground换肤，默认打开[可选]
                .addStrategy(CustomLoader())
                .addStrategy(ZipLoader())
```

```
public class CustomSkinViewInflater implements SkinLayoutInflater {

    @Override
    public View createView(Context context, String name, AttributeSet attrs) {
        return createViewFromFV(context, name, attrs);
    }

    private View createViewFromFV(Context context, String name, AttributeSet attrs) {
        View view = null;
        /*if (name.contains(".")) {
            return null;
        }*/
        switch (name) {
            case "ImageView":
                view = new CustomSkinCompatImageView(context, attrs);
                break;
            case "TextView":
                view = new CustomSkinCompatTextView(context, attrs);
                break;
            case "androidx.appcompat.widget.SwitchCompat":
                view = new CustomSwitchCompat(context, attrs);
                break;

            default:
                break;
        }
        return view;
    }
}

```

@NaclFire

**Comment by NaclFire** [comment]
> ```
> SkinCompatManager.withoutActivity(this)
>                 .addInflater(CustomSkinViewInflater())           // 自定义View加载
>                 .addInflater(SkinAppCompatViewInflater())           // 基础控件换肤初始化
>                 .addInflater(SkinMaterialViewInflater())            // material design 控件换肤初始化[可选]
>                 .addInflater(SkinConstraintViewInflater())          // ConstraintLayout 控件换肤初始化[可选]
>                 .setSkinWindowBackgroundEnable(false)                   // 关闭windowBackground换肤，默认打开[可选]
>                 .addStrategy(CustomLoader())
>                 .addStrategy(ZipLoader())
> ```
> 
> ```
> public class CustomSkinViewInflater implements SkinLayoutInflater {
> 
>     @Override
>     public View createView(Context context, String name, AttributeSet attrs) {
>         return createViewFromFV(context, name, attrs);
>     }
> 
>     private View createViewFromFV(Context context, String name, AttributeSet attrs) {
>         View view = null;
>         /*if (name.contains(".")) {
>             return null;
>         }*/
>         switch (name) {
>             case "ImageView":
>                 view = new CustomSkinCompatImageView(context, attrs);
>                 break;
>             case "TextView":
>                 view = new CustomSkinCompatTextView(context, attrs);
>                 break;
>             case "androidx.appcompat.widget.SwitchCompat":
>                 view = new CustomSwitchCompat(context, attrs);
>                 break;
> 
>             default:
>                 break;
>         }
>         return view;
>     }
> }
> ```
> 
> @NaclFire

兄弟 你用的是androidx的依赖吗 ? 我用的是support library , 你说的这个方法我已经试过了 , 我添加了一个自定义的Inflater , 但是tint还是没有换肤效果, support library在Application的onCreate中初始化的时候是这样的:
`SkinCompatManager.withoutActivity(this)                         // 基础控件换肤初始化
            .addInflater(new SkinMaterialViewInflater())            // material design 控件换肤初始化[可选]
            .addInflater(new SkinConstraintViewInflater())          // ConstraintLayout 控件换肤初始化[可选]
            .addInflater(new SkinCardViewInflater())                // CardView v7 控件换肤初始化[可选]
            .setSkinStatusBarColorEnable(false)                     // 关闭状态栏换肤，默认打开[可选]
            .setSkinWindowBackgroundEnable(false)                   // 关闭windowBackground换肤，默认打开[可选]
            .loadSkin();`
然后android x初始化是这样的:
`SkinCompatManager.withoutActivity(this)
            .addInflater(new SkinAppCompatViewInflater())           // 基础控件换肤初始化
            .addInflater(new SkinMaterialViewInflater())            // material design 控件换肤初始化[可选]
            .addInflater(new SkinConstraintViewInflater())          // ConstraintLayout 控件换肤初始化[可选]
            .addInflater(new SkinCardViewInflater())                // CardView v7 控件换肤初始化[可选]
            .setSkinStatusBarColorEnable(false)                     // 关闭状态栏换肤，默认打开[可选]
            .setSkinWindowBackgroundEnable(false)                   // 关闭windowBackground换肤，默认打开[可选]
            .loadSkin();`
SkinAppCompatViewInflater()这个方法在support library中无法使用

我之前写的方式和你教我的一样 , 添加了:
`  // 换肤功能
        SkinCompatManager.withoutActivity((Application) context)
                .addInflater(new CustomSkinViewInflater())
                .addStrategy(new CustomSDCardLoader())
                .loadSkin();`
之后也不能实现tint换肤
我通过改源码的方式可以实现换肤 , 把tint换肤的代码放入SkinCompatImageHelper中,可以实现tint换肤 , 但是源码好像有点问题 , 有一部分TextView不能换肤了 , 所以放弃了

**Comment by NaclFire** [comment]
我看了一下 , 通过addInflater添加的自定义inflater,在createView中获取到的name,没有ImageView
@DaveBoy

**Comment by DaveBoy** [comment]
> 我看了一下 , 通过addInflater添加的自定义inflater,在createView中获取到的name,没有ImageView
> ![微信截图_20200121165620](https://user-images.githubusercontent.com/27260675/72789663-22235a00-3c6f-11ea-9d42-bf2791c64708.png)
> 
> @DaveBoy

自定义的flater放到第一个位置，优先级第一，不然会被其他的先过滤
