### ISSUE TITLE
换肤后 View.setCompoundDrawables 无法使用

### ISSUE THREAD

**Issue by Cassie-7579** [ximsfei/Android-skin-support#336]
版本： 3.1.4
项目引入第三方适配框架:  AndroidAutoSize 
问题： 当我调用以下方法后会去重新加载 Activity 的布局后出现我之前调用的 **View.setCompoundDrawables()** 方法设置 Drawable 没有生效（变成布局文件本来的设置的 Drawable），然后在不调用以下方法的时候是生效的。 
`SkinCompatManager.getInstance().loadSkin("night",SkinCompatManager.SKIN_LOADER_STRATEGY_BUILD_IN); `

**Comment by yayo292916** [comment]
Hey, how did you solve the problem? Can you please share?

**Comment by Cassie-7579** [comment]
@yayo292916  我暂时没有找到解决方法，但是我找到原因了。
因为在此框架中是通过拦截布局文件Color、Drawable 等属性然后转换成对应主题的Color。Drawable等。而且皮肤切换的时候你的 View.setCompoundDrawables 设置的属性被切换成对应主题的Drawable（这里的 Drawable 是布局文件中的 Drawable 而不是你代码生成的），所以这就造成了我们看到的“换肤后 View.setCompoundDrawables 无法使用”的问题。
而在我的项目中我不需要我只是为了去设置 Drawable 的大小，所以我自定义了一个可以设置 Drawable 大小的 TextView 等，这个只是为了解决问题而解决问题。目前还没找到可以捕获拦截代码中设置的 Drawable 的方法。
希望作者能给出更好的解决方法 @ximsfei

**Comment by ximsfei** [comment]
@Cassie-7579 @yayo292916 可以参考[demo](https://github.com/ximsfei/Android-skin-support/blob/master/demo/skin-androidx-app/src/main/java/com/ximsfei/skindemo/tab/fragment/LastFragment.java#L36)实现。
具体原因，可以研究下换肤框架的[实现原理](https://github.com/ximsfei/Android-skin-support/blob/master/docs/FAQ.md#%E6%8E%A7%E4%BB%B6%E8%B5%84%E6%BA%90%E5%9C%A8%E6%8D%A2%E8%82%A4%E4%B9%8B%E5%89%8D%E6%98%AF%E6%AD%A3%E5%B8%B8%E7%9A%84%E4%BD%86%E6%98%AF%E5%88%87%E6%8D%A2%E7%9A%AE%E8%82%A4%E5%90%8E%E6%8E%A7%E4%BB%B6%E8%B5%84%E6%BA%90%E6%81%A2%E5%A4%8D%E6%88%90%E9%BB%98%E8%AE%A4%E7%9A%84%E8%B5%84%E6%BA%90%E4%BA%86)
