### ISSUE TITLE
statusBarColor颜色有错

### ISSUE THREAD

**Issue by TangKe** [ximsfei/Android-skin-support#34]
在AndroidManifest.xml中, 如果application节点有主题, 在某个activity中又指定了主题, 同时恰好这两个主题的statusBarColor不一样, SkinCompatActivity会把application的statusBarColor读取出来, 填充到activity上

**Comment by ximsfei** [comment]
@TangKe demo中有例子哈[manifest](https://github.com/ximsfei/Android-skin-support/blob/master/skin-app/src/main/AndroidManifest.xml), 看MainActivity和MaterialDesignActivity。
