### ISSUE TITLE
夜神模拟器，安卓5.0，切换夜间模式偶尔报错

### ISSUE THREAD

**Issue by conghuahuadan** [ximsfei/Android-skin-support#342]
夜神模拟器，安卓5.0，切换夜间模式偶尔报错

java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference

![image](https://user-images.githubusercontent.com/20864280/76607153-71d72100-654e-11ea-8556-d023f486bb20.png)

**Comment by ximsfei** [comment]
这个crash日志看不出来和换肤有什么关系，有更多信息吗？
