### ISSUE TITLE
没有针对继承View的第三方控件换肤案例

### ISSUE THREAD

**Issue by wizong** [ximsfei/Android-skin-support#344]
在我项目中使用到一个第三方继承View的自定义控件，自定义属性中引用selector的drawable类型，在类初始化中调用typeArray.getDrawable，此时由于库中没有类似SkinCompatBackgroundHelper的SkinCompatDrawableHelper，从而无法使之生效。
![image](https://user-images.githubusercontent.com/18070210/77892624-79fcc380-72a5-11ea-8517-c8d6454b9566.png)

**Comment by ximsfei** [comment]
可以参考[CircleImageView](https://github.com/ximsfei/Android-skin-support/blob/master/third-part-support/circleimageview/src/main/java/skin/support/circleimageview/widget/SkinCompatCircleImageView.java)的`CircleImageView_civ_border_color`和`CircleImageView_civ_fill_color`属性
