### ISSUE TITLE
RecyclerView.ItemDecoration

### ISSUE THREAD

**Issue by Kevin088** [ximsfei/Android-skin-support#347]
RecyclerView.ItemDecoration  这个怎么更换颜色呢

**Comment by JamesGZM** [comment]
issues 里头有想同的问题 我打算写到Item里头分割线

**Comment by ximsfei** [comment]
暂时还不支持`RecyclerView.ItemDecoration`换肤，可以考虑通过布局文件中增加分割线等来实现
