### ISSUE TITLE
载入皮肤后，没有继承SkinCompatActivity的Activity也被影响

### ISSUE THREAD

**Issue by sibinte** [ximsfei/Android-skin-support#35]
载入皮肤后，没有继承SkinCompatActivity的Activity也被影响

**Comment by ximsfei** [comment]
不是很明白？:-)

**Comment by PoetKing** [comment]
同样遇到这种问题，比如第三方aar中的activity，有自己的布局文件，color值等，
LayoutInflaterCompat.setFactory(getLayoutInflater(), getSkinDelegate());
之后，第三方aar中的界面会有影响。

**Comment by ximsfei** [comment]
@PoetKing @sibinte 
第三方界面的背景会有影响？

**Comment by PoetKing** [comment]
对。背景有影响，经过测试
// int color = getResources().getColor(R.color.white);
 int color = SkinCompatResources.getInstance().getColor(R.color.white);
  TextView tv = new TextView(view.getContext());
  //tv.setBackgroundColor(color);
 tv.setBackgroundResource(R.color.white);
通过setBackgroundResource方法设置的背景有影响，第一二行两种方式获取的color值都是FFFFFFFF，setBackgroundColor这样设置没问题。

**Comment by ximsfei** [comment]
不是很明白，加一下QQ群吧：530160073

**Comment by PoetKing** [comment]
最终没有找到真正原因，不过通过修改R.color.white的值由FFFFFF到FFFFFE，可以临时解决这个问题。其实就是R.color.white（FFFFFF）通过setBackgroundResource后无法正常显示。

**Comment by arronvera** [comment]
同样出现这个问题，影响第三方

**Comment by ximsfei** [comment]
@arronvera https://github.com/ximsfei/Android-skin-support/blob/master/androidx/skin-support/src/main/java/skin/support/SkinCompatManager.java#L263

**Comment by arronvera** [comment]
你知道为什么三方的布局new 的textview引入了皮肤过后，内部的gravity不起作用了呢
