### ISSUE TITLE
androidX没有状态栏换肤？

### ISSUE THREAD

**Issue by bujinhai** [ximsfei/Android-skin-support#351]
你好，AndroidX去掉了状态栏换肤吗？用的最新4.0.4版本的依赖，源码没有状态栏换肤功能
<img width="377" alt="image" src="https://user-images.githubusercontent.com/30205430/79295516-71de8e00-7f0b-11ea-8270-74dbe65acdb5.png">

**Comment by ximsfei** [comment]
框架弃用了状态栏换肤，可以业务层自行扩展
