### ISSUE TITLE
动态更改颜色

### ISSUE THREAD

**Issue by zhangjinqiang61** [ximsfei/Android-skin-support#352]

**Comment by zhangjinqiang61** [comment]
SkinCompatUserThemeManager.get().addColorState(R.color.theme_primary_color, "#438EFD"); SkinCompatUserThemeManager.get().apply();

按照说明文档里面那样设置的 但是没有反应，请问是什么问题呢?

**Comment by ximsfei** [comment]
@zhangjinqiang61 代码中怎么使用`theme_primary_color`这个资源的？

**Comment by ximsfei** [comment]
@zhangjinqiang61 可以参考[ColorPickerActivity](https://github.com/ximsfei/Android-skin-support/blob/master/demo/skin-androidx-app/src/main/java/com/ximsfei/skindemo/picker/ColorPickerActivity.java)中的实现
