### ISSUE TITLE
启动页 过度界面无法换肤

### ISSUE THREAD

**Issue by woaimi520** [ximsfei/Android-skin-support#362]
当启动页使用例如
android:windowBackground= @drawable/layer_launcher
（为了让启动页 不会白屏添加）

使用app 内部换肤 ，这个启动过度的界面始终无法换肤，去掉之后 又会有白屏问题
好像这里不是很好处理 又不是view ，我改为动态用代码在启动页的onstart内部去设置 windowBackground还是会有白屏问题

**Comment by ximsfei** [comment]
为了让用户更快看到界面，启动页最初的windowBackground在系统层设置的，应用层控制不到，可以找视觉同学一起看下，尽量减少闪屏。

**Comment by feng612266** [comment]
> 当启动页使用例如 android:windowBackground= @drawable/layer_launcher （为了让启动页 不会白屏添加）
> 
> 使用app 内部换肤 ，这个启动过度的界面始终无法换肤，去掉之后 又会有白屏问题 好像这里不是很好处理 又不是view ，我改为动态用代码在启动页的onstart内部去设置 windowBackground还是会有白屏问题

你好，后面有找到好的过度界面换肤吗，我这边试的也不行
