### ISSUE TITLE
SkinCompatResources.getColor() 的问题

### ISSUE THREAD

**Issue by bingdu0** [ximsfei/Android-skin-support#364]
为什么SkinCompatResources.getColor()  和R.color.  的值不一样呢？导致现在无法设置状态栏的颜色。作者可以在demo 中加入更改皮肤更改状态栏的颜色吗？还有就是为什么技术交流的qq看不到了。

**Comment by ximsfei** [comment]
1. SkinCompatResources.getColor()，是根据R.color.xxx; 返回皮肤包里 xxx对应的color值。R.color. 是资源id
2. 可以在[applySkin](https://github.com/ximsfei/Android-skin-support/blob/master/demo/skin-androidx-app/src/main/java/com/ximsfei/skindemo/actionbar/ActionbarTestActivity.java)方法中，修改状态栏颜色
