### ISSUE TITLE
加载插件皮肤问题。kt项目

### ISSUE THREAD

**Issue by IClient** [ximsfei/Android-skin-support#366]
加载插件皮肤包一直加载不出来，启动app还是默认的。没提示哪里有异常。我是重写创建一个项目名skin，然后把原项目资源文件拷贝到skin下面。就随便改了几个背景颜色。然后打包后缀改成.skin。比如:red.skin。放到原项目的assets/skins目录下。由于我是组件化开发。资源文件单独放到一个模块的。楼主能帮忙看下哪里出问题了吗？

**Comment by ximsfei** [comment]
跑一下demo，按照文档一步步接入、制作皮肤包

**Comment by IClient** [comment]
能加个qq请教下嘛，大佬
