### ISSUE TITLE
progressbar动态设置setProgressDrawable没有效果，在静态页面写是有效果的。

### ISSUE THREAD

**Issue by arronvera** [ximsfei/Android-skin-support#367]
请问怎么动态设置呢？

**Comment by ximsfei** [comment]
progressbar暂时默认只支持静态布局中实现换肤；原理可参考：https://github.com/ximsfei/Android-skin-support/blob/master/docs/FAQ.md#%E5%8A%A8%E6%80%81%E8%AE%BE%E7%BD%AEtextview%E7%9A%84textcolormtextviewsettextcolorgetresourcesgetcolorrcolortext_color%E6%97%A0%E6%B3%95%E6%8D%A2%E8%82%A4

可自行扩展实现；参考：https://github.com/ximsfei/Android-skin-support/blob/master/demo/skin-androidx-app/src/main/java/com/ximsfei/skindemo/actionbar/ActionbarTestActivity.java
