### ISSUE TITLE
applySkin 未被调用

### ISSUE THREAD

**Issue by tp19970424** [ximsfei/Android-skin-support#368]
在一个第三方的继承自TextView的控件中使用
SkinCompatTextHelper.create(this)
创建
SkinCompatTextHelper对象
并实现了SkinCompatSupportable接口，可是换肤后该控件的applySkin()方法未被回调

**Comment by ximsfei** [comment]
代码实现发下

**Comment by tp19970424** [comment]
public class BoldTextView extends SimplePagerTitleView implements SkinCompatSupportable {

    private boolean sizeChange;
    private SkinCompatTextHelper skinCompatHelper;
    //    private SkinCompatBackgroundHelper mBackgroundTintHelper;
    private Context context;
    private int selectedColorId = INVALID_ID;
    private int normalColorId = INVALID_ID;

    public BoldTextView(Context context) {
        super(context);
        this.context = context;
        skinCompatHelper = SkinCompatTextHelper.create(this);
        skinCompatHelper.loadFromAttributes(null, 0);
        normalColorId = R.color.text_color_999999;
        selectedColorId = R.color.skin_theme_color;
        applyNormalColorResource();
        applySelectedColorResource();
    }

    public void setSizeChange(boolean sizeChange) {
        this.sizeChange = sizeChange;
    }

    @Override
    public void onSelected(int index, int totalCount) {
        super.onSelected(index, totalCount);
        setTypeface(Typeface.defaultFromStyle(Typeface.BOLD));
        if (!sizeChange) {
            setTextSize(16);
        } else {
            setTextSize(14);
        }
    }

    @Override
    public void onDeselected(int index, int totalCount) {
        super.onDeselected(index, totalCount);
        setTypeface(Typeface.defaultFromStyle(Typeface.NORMAL));
        setTextSize(14);
    }

    public void setNormalColorId(int normalColorId) {
        setNormalColor(getResources().getColor(normalColorId));
        this.normalColorId = normalColorId;
        applySkin();
    }

    public void setSelectedColorId(int selectedColorId) {
        setSelectedColor(getResources().getColor(selectedColorId));
        this.selectedColorId = selectedColorId;
        applySkin();
    }

    private void applyNormalColorResource() {
        normalColorId = SkinCompatHelper.checkResourceId(normalColorId);
        if (normalColorId != INVALID_ID) {
            int color = SkinCompatResources.getColor(getContext(), normalColorId);
            setNormalColor(color);
        }
    }

    private void applySelectedColorResource() {
        selectedColorId = SkinCompatHelper.checkResourceId(selectedColorId);
        if (selectedColorId != INVALID_ID) {
            int color = SkinCompatResources.getColor(getContext(), selectedColorId);
            setSelectedColor(color);
        }
    }

    @Override
    public void applySkin() {
        if (skinCompatHelper != null) {
            skinCompatHelper.applySkin();
        }
        applyNormalColorResource();
        applySelectedColorResource();
        LogUtils.e("BoldTextView:applySkin,来啊宝贝!");
    }
}

**Comment by tp19970424** [comment]
我的这句log日志一直没有打印过

**Comment by ximsfei** [comment]
你这个View是new出来的嘛？需要写在布局文件里，通过view inflate加载

**Comment by tp19970424** [comment]
这个是第三方的一个控件，我重写了。。。他只能通过new出来。。。。好吧，那我自己监听下，在设置皮肤后调用一下这个实现这个接口的view吧。。。
