### ISSUE TITLE
请问对于PopupWindow的子类该如何实现换肤呢？

### ISSUE THREAD

**Issue by Fan086** [ximsfei/Android-skin-support#370]
项目中有通过继承PopupWindow实现的子类，把它作为弹窗很方便，布局是通过setContentView传一个view进去的，但是现在需要为它实现换肤，有什么好的方式可以让它生效吗？是不是只能从java代码中去手动修改呢？

**Comment by ximsfei** [comment]
setContentView传入的view，.通过LayoutInflater.from(application).inflate()创建

**Comment by Fan086** [comment]
好的，非常感谢

**Comment by Fan086** [comment]
> setContentView传入的view，.通过LayoutInflater.from(application).inflate()创建
好的，非常感谢
