### ISSUE TITLE
可否不继承 SkinCompatActivity

### ISSUE THREAD

**Issue by jokermonn** [ximsfei/Android-skin-support#38]
如题。因为有一个库已经需要我继承它的 Activity，所以不能再兼容继承 SkinCompatActivity，还有别的方法解决吗

**Comment by ximsfei** [comment]
可以。把SkinCompatActivity里面的东西搬到自己的baseactivity里面去。:-)

**Comment by jokermonn** [comment]
thx。建议写在 README 中~相信会有挺多小伙伴和我遇到一样的情况
