### ISSUE TITLE
刷新问题

### ISSUE THREAD

**Issue by lixiongh-hou** [ximsfei/Android-skin-support#397]
请问作者，一定要继承SkinCompatActivity类才能遍历所有View吗，但是您的最新版本已经过时了,我不继承这个类没有效果，继承就有了

**Comment by ximsfei** [comment]
不需要继承SkinCompatActivity，先跑一下demo

**Comment by lixiongh-hou** [comment]
您好，我下载了你的项目看了，还是没找到哪里有不一样，是因为我是Kotlin原因吗
我在Application进行了初始化
class MyApp : Application() {

    override fun onCreate() {
        super.onCreate()
        Slog.DEBUG = true
        SkinCompatManager.withoutActivity(this)
                .addStrategy(CustomSDCardLoader())          // 自定义加载策略，指定SDCard路径
                .addInflater(SkinAppCompatViewInflater())   // 基础控件换肤初始化
                .addInflater( SkinMaterialViewInflater())    // material design
                .setSkinWindowBackgroundEnable(false)        // 关闭windowBackground换肤，默认打开[可选]
                .loadSkin()
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true)
    }
}

**Comment by lixiongh-hou** [comment]
找了问题了，我之前继承的是4.01版本，没有找到SkinAppCompatDelegateImpl这个类，我下载您的项目也没找到，所以没有重写getDelegate（）方法，在文档看到了，我升级到4.0.5就有了，重写就行了
