### ISSUE TITLE
该换肤库对Fragment的生命周期有影响吗？

### ISSUE THREAD

**Issue by lilyangle** [ximsfei/Android-skin-support#40]

**Comment by ximsfei** [comment]
没有影响 :-)

**Comment by lilyangle** [comment]
我在Activity中嵌套了Fragment,在Fragment中设置了对act中某一控件的监听，当项目运行时，触发该事件，回调fragment中的处理方法时，fragmenth中的控件对象为空，但是fragment对象存在，不清楚时怎么回事？

**Comment by ximsfei** [comment]
你可以把换肤框架去掉试试。应该也会这样的 :-)

**Comment by lilyangle** [comment]
谢谢，是代码的原因
