### ISSUE TITLE
AppCompatImageView 不支持

### ISSUE THREAD

**Issue by RealMoMo** [ximsfei/Android-skin-support#401]
AppCompatImageView src srcCompat 都不支持，只能改用ImageView么？

**Comment by ximsfei** [comment]
使用ImageView，最终也是通过AppCompatImageView实现换肤的，可以参考SkinCompatImageView

**Comment by RealMoMo** [comment]
support androidx

**Comment by fly263** [comment]
我使用的也是androidx，刚开始也不行，后来修改了skin-support-appcompat里面的SkinAppCompatViewInflater才能换肤
