### ISSUE TITLE
在Android11 上出现切换皮肤失败  

### ISSUE THREAD

**Issue by xiaoxing1992** [ximsfei/Android-skin-support#429]

**Comment by xiaoxing1992** [comment]
/**
     * 获取皮肤包包名.
     *
     * @param skinPkgPath sdcard中皮肤包路径.
     * @return
     */
    public String getSkinPackageName(String skinPkgPath) {
        PackageManager mPm = mAppContext.getPackageManager();
        PackageInfo info = mPm.getPackageArchiveInfo(skinPkgPath, PackageManager.GET_ACTIVITIES);
        return info.packageName;
    }

在Android11上 这个info获取为null  目前还没解决方案

**Comment by xiaoxing1992** [comment]
已解决  (方案：反射)

**Comment by forever1985** [comment]
> 已解决 (方案：反射)

想请问一下是怎么反射的呢，我这不成功
