### ISSUE TITLE
自定义控件的话，paint.setColor（）的问题

### ISSUE THREAD

**Issue by willsame** [ximsfei/Android-skin-support#43]
自定义控件时，遇到这种
Paint.setColor(mRoundColor);
mRoundColor是通过
typedArray.getColor(R.styleable.RoundProgressBar_textColor, getResources().getColor(R.color.c4c6072));获取的，之前你说过不支持 getResources().getColor(R.color.c4c6072)方式更换颜色，想问下这种情况怎么解决？

**Comment by ximsfei** [comment]
resid = typedArray.getResourceId(R.styleable.RoundProgressBar_textColor, INVALID_ID);
在使用的地方
Paint.setColor(SkinResources.getColor(resId));
在applySkin中
重绘

**Comment by willsame** [comment]
INVALID_ID 是 SkinCompatHelper 里面的INVALID_ID么，还在自己写的

**Comment by willsame** [comment]
@INVALID_ID 是 SkinCompatHelper 里面的INVALID_ID么，还在自己写的，applySkin()里面怎么重绘的？有点儿懵

**Comment by willsame** [comment]
@INVALID_ID 是 SkinCompatHelper 里面的INVALID_ID么，还是自己getResources().getColor()拿到的，applySkin()里面怎么重绘的？有点儿懵

**Comment by ximsfei** [comment]
SkinCompatHelper里的INVALID_ID，在applySkin中setBackground，setTextColor等等。在换肤的时候会回调applySkin方法

**Comment by wowo3129** [comment]
具体的颜色值是在R.styleable.RoundProgressBar_textColor 这里面写的吗？ 还是有其他地方设置待切换的颜色值，下面是我的R.styleable.WeekView 里面的值    <declare-styleable name="WeekView">
        
        <attr name="week_str" format="string" />
        
        <attr name="week_color" format="color" />
        
        <attr name="week_size" format="integer" />
    </declare-styleable>

**Comment by wowo3129** [comment]
<declare-styleable name="WeekView">
        
        <attr name="week_str" format="string" />
        
        <attr name="week_color" format="color" />
        
        <attr name="week_size" format="integer" />
    </declare-styleable>

**Comment by wowo3129** [comment]
`    <declare-styleable name="WeekView">
        
        <attr name="week_str" format="string" />
        
        <attr name="week_color" format="color" />
        
        <attr name="week_size" format="integer" />
    </declare-styleable>`
