### ISSUE TITLE
如何代码获取对应的颜色，SkinCompatResources.getInstance().getColor(R.color.status_bar_color)，空指针！！！

### ISSUE THREAD

**Issue by will12190** [ximsfei/Android-skin-support#432]
如何代码获取对应的颜色，SkinCompatResources.getInstance().getColor(R.color.status_bar_color)，空指针！！！，有时候我需要在代码中动态获取颜色进行设置，赐教，本来想加群的，QQ加入一直提示NaN,在线等

**Comment by will12190** [comment]
自己研究了下代码，解决了；分享给新来的朋友；
TypedValue typedValue = new TypedValue();
SkinCompatResources.getValue(this, R.color.colorPrimary, typedValue, true);
int resourceId = typedValue.resourceId;
setColor(resourceId); 就可以啦；我是在使用ImmersionBar 沉浸式式遇到的这个问题

**Comment by AlohaQwQ** [comment]
有用，感谢老兄
