### ISSUE TITLE
关于ConstraintLayout背景色问题

### ISSUE THREAD

**Issue by XF-zhjnc** [ximsfei/Android-skin-support#45]
我有几个界面用ConstraintLayout做根布局，在切换它们的android:background时，有的布局背景色偶尔会变偶尔不会，无规律，有的布局怎么都不变，我尝试过杀死应用再重启，都无法解决这个问题，请问这是什么问题？

**Comment by ximsfei** [comment]
ConstraintLayout暂时还没做换肤支持，可以自行扩展 :-)

**Comment by XF-zhjnc** [comment]
原来如此，好的谢谢作者，换肤框架很好用 👍

**Comment by ximsfei** [comment]
@XF-zhjnc ConstraintLayout已经支持啦，具体使用可以参考Demo
Application.java
`.addInflater(new SkinConstraintViewInflater())  // ConstraintLayout`
build.gradle
`compile 'skin.support:skin-support-constraint-layout:1.0.2`
:-)

**Comment by XF-zhjnc** [comment]
好的谢谢，辛苦了
