### ISSUE TITLE
为什么复写AppCompatActivity的getDelegate()方法？

### ISSUE THREAD

**Issue by XinYiWorld** [ximsfei/Android-skin-support#460]
SkinActivityLifecycle不是已经installLayoutFactory了吗，为什么还要在这里复写方法，请大神解答一下？

**Comment by luohaiah** [comment]
viewFactory只能install一次，AppCompatActivity自身已经install了，复写了就没异常了

**Comment by XinYiWorld** [comment]
谢谢大神，已经打日志看过了。appcompatactivity自身的installFactory会比lifecycle里的回调的快，所以这里要处理一下。
