### ISSUE TITLE
skin-support 和 skin-support-design 为什么不放到一块呢

### ISSUE THREAD

**Issue by sfsheng0322** [ximsfei/Android-skin-support#5]
skin-support // 基础控件支持
skin-support-design // Material Design 支持

**Comment by ximsfei** [comment]
@sfsheng0322 
skin-support 是对Android 基础控件的换肤支持.
skin-support 是对Android material design包中控件的支持.
有些应用中没用到material design相关控件，那么他们想要实现换肤功能，只需要引入skin-support包就够了，没必要引入skin-support-design. 这样可以减小APK体积.
而对于有Material Design需求的用户来说，可以额外的引入skin-support-design包来支持.
:)

**Comment by ximsfei** [comment]
@sfsheng0322 
如果将来Android出了比material design更好的设计，那也可以在只引用skin-support的基础上新增一个module来支持新的控件.

**Comment by sfsheng0322** [comment]
谢谢啦，还有一个请求哈，关于skin-night/skin-day的使用，能不能给出一点说明呀，再次感谢

**Comment by ximsfei** [comment]
@sfsheng0322 
可以看看我在[这里](https://github.com/ximsfei/Android-skin-support/issues/1)的回复
skin-night其实就是一个普通的app工程
例如
应用中窗口背景颜色为
colors.xml
<color name="background">#ffffff</color>

那么夜间模式你可以在skin-night工程中设置
colors.xml
<color name="background">#000000</color>
:)

**Comment by sfsheng0322** [comment]
了解了，非常感谢
