### ISSUE TITLE
换肤后退出应用，在进入会崩溃

### ISSUE THREAD

**Issue by HotBitmapGG** [ximsfei/Android-skin-support#50]
请问下遇到过这个问题吗，很奇怪，换肤后退出应用并把后台清理掉，在进入app就直接崩了，而且没有任何错误日志 @ximsfei

**Comment by ximsfei** [comment]
暂时还没遇到过，先排插一下接入有没有问题。还有没有错误日志，可能是应用一启动就崩溃了，Android Studio还没能打出日志。用adb logcat试试，看能不能找到有用信息。

**Comment by HotBitmapGG** [comment]
@ximsfei 谢谢，解决了，是我这项目引用了融云，因为融云初始化的时候在一个独立的进程，所以我的Application初始化的时候调用了两次，导致皮肤库初始化的时候崩溃了，解决办法就是根据不同的进程名称进行判断，对融云进行单独处理就可以了
