### ISSUE TITLE
SkinCompatEditText

### ISSUE THREAD

**Issue by willsame** [ximsfei/Android-skin-support#52]
光标颜色不能随着夜间模式改变，皮肤包里面配置了，textCursorDrawable设置了颜色，但是更换夜间模式后，颜色没有改变。

**Comment by ximsfei** [comment]
[https://github.com/ximsfei/Android-skin-support/blob/master/ChangeLog.md](url)更新日志中记录了所有常用的已支持的属性。未支持的属性可以自行扩展，欢迎提交pr。
