### ISSUE TITLE
希望SkinCompatProgressBarHelper 能支持indeterminateTint属性

### ISSUE THREAD

**Issue by weizai** [ximsfei/Android-skin-support#53]

**Comment by ximsfei** [comment]
@weizai 感谢你的支持，代码已提交，只需要更新build.gradle就可以了。不过研究了一下indeterminateTint这个属性，只在api21以上支持。如果在21以下有好的解决办法欢迎提交pr :-)
`compile 'skin.support:skin-support:1.2.8'`

**Comment by weizai** [comment]
好的

**Comment by weizai** [comment]
修改了下SkinCompatManager, 支持不必继承SkinCompatActivity便可换肤, 天朝的网实在DT，项目clone半天都没下来, 没法pr 这里直接传代码文件了
[SkinCompatManager.txt](https://github.com/ximsfei/Android-skin-support/files/1121260/SkinCompatManager.txt)

**Comment by ximsfei** [comment]
哈哈哈。厉害了，灰常感谢，代码已提交 :-)
`compile 'skin.support:skin-support:2.0.1'`

**Comment by weizai** [comment]
很高兴能采纳, 另外以下地方经测试不可去除, 否则会导致栈中的其他Activity换肤异常。可测试下XD~
            private SkinObserver getObserver(final Activity activity) {
                if (skinObserverMap == null) {
                    skinObserverMap = new WeakHashMap<>();
                }
                SkinObserver observer = skinObserverMap.get(activity);
                if (observer == null) {
                    observer = new SkinObserver() {
                        @Override
                        public void updateSkin(SkinObservable observable, Object o) {
                            for (WeakHashMap.Entry<Activity, SkinObserver> map : skinObserverMap.entrySet()) {
                                Activity tempActivity = map.getKey();
                                updateStatusBarColor(tempActivity);
                                updateWindowBackground(tempActivity);
                                getSkinDelegate((AppCompatActivity) tempActivity).applySkin();
                            }
                        }
                    };
                }
                skinObserverMap.put(activity, observer);
                return observer;
            }

**Comment by ximsfei** [comment]
关于这个问题，我已经改啦，将下面这段代码移到onDestroy方法即可。
```java
@Override
public void onActivityPaused(Activity activity) {
    SkinCompatManager.getInstance().deleteObserver(getObserver(activity));
}
```

```java
@Override
public void onActivityDestroyed(Activity activity) {
    SkinCompatManager.getInstance().deleteObserver(getObserver(activity));
    skinObserverMap.remove(activity);
    skinDeleMap.remove(activity);
}
```
