### ISSUE TITLE
跟沉浸式状态栏有冲突

### ISSUE THREAD

**Issue by duzechao** [ximsfei/Android-skin-support#54]
跟沉浸式状态栏有冲突，一换肤就沉浸式状态栏就失效了

**Comment by ximsfei** [comment]
Android 5.0以上，框架默认是开启了状态栏换肤的，可以选择关闭框架的状态栏换肤。
SkinCompatManager.java的`setSkinStatusBarColorEnable`方法可以设置。
希望能够解决你的问题 :-)
如果还有问题，欢迎继续交流

**Comment by kilo-swodh** [comment]
该方法是私有方法,封装好了的,没办法调用

**Comment by ximsfei** [comment]
啊。。。没注意，这算是个bug，我改了一下，已经提交啦。

**Comment by kilo-swodh** [comment]
好的,多谢修复

**Comment by kouxinhong** [comment]
android.support.design.widget.TabLayout 切换失败 我已经引入这个库了，重启程序久好了，帮忙一下，谢谢
又是会有这个错误
Unknown element under <manifest>: meta-data at /storage/emulated/0/Android/data/com.apkpure.aegon/cache/skins/apkpure.skin Binary XML file line #11
