### ISSUE TITLE
如何加载SDCard中的皮肤呢？

### ISSUE THREAD

**Issue by aloe20** [ximsfei/Android-skin-support#55]
从服务器中下载的皮肤存放在SDCard中，该如何加载呢？

**Comment by ximsfei** [comment]
https://github.com/ximsfei/Android-skin-support/issues/1
或者自己实现loadSkin方法。:-)

**Comment by aloe20** [comment]
发现直接将皮肤文件拷到cache目录下就行了

**Comment by ximsfei** [comment]
是的，放到指定目录就行了.

**Comment by ximsfei** [comment]
现在支持自定义加载策略啦，可参考
