### ISSUE TITLE
android.support.design.widget.TabLayout 切换失败 

### ISSUE THREAD

**Issue by kouxinhong** [ximsfei/Android-skin-support#56]
android.support.design.widget.TabLayout 切换失败 我已经引入这个库了，重启程序久好了，帮忙一下，谢谢
又是会有这个错误
Unknown element under : meta-data at /storage/emulated/0/Android/data/com.packeage/cache/skins/night.skin Binary XML file line #11

**Comment by ximsfei** [comment]
关于TabLayout切换失败的问题，我用demo试了一下没有问题。不知道是不是接入问题？可以参考demo看看
关于这个错误，Unknown element under 看看是不是你的xml11行有问题？:-)
如果还是有问题，尽量把问题相关信息描述的详细些，比方说模拟器还是真机，SDK版本号等等。因为demo里是好的，只是说换肤失败，可能我也无法定位。

**Comment by kouxinhong** [comment]
谢谢回复，手机为7.0,sdk的版本号为24，《小米真机，nexus真机（是刷机的）》都不行，我是这样写的
`<android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/primary_color"
        android:theme="@style/AppTheme.AppBarOverlay">

        <android.support.design.widget.TabLayout
            android:id="@+id/tab_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:tabIndicatorColor="@color/accent_color"
            app:tabMode="scrollable"/>

    </android.support.design.widget.AppBarLayout>`
给 android.support.design.widget.AppBarLayout 设置背景可以起作用，但是android.support.design.widget.TabLayout 在android.support.design.widget.AppBarLayout里面，理论上android.support.design.widget.TabLayout的 background应该覆盖android.support.design.widget.AppBarLayout 的背景的，不知道我理解的对不对，望你指导一下

**Comment by ximsfei** [comment]
你要切换的TabLayout的属性是tabIndicatorColor？

**Comment by kouxinhong** [comment]
两个都要的，现在tabIndicatorColor是可以的

**Comment by ximsfei** [comment]
以后遇到这样的情况可以看一下[更新日志](https://github.com/ximsfei/Android-skin-support/blob/master/ChangeLog.md)，里面记录了所有的已支持的属性。
TabLayout的background没做支持，为了提高换肤效率不是每个属性都做了支持。

**Comment by kouxinhong** [comment]
哦哦，谢谢🙏
