### ISSUE TITLE
图片使用SVG app:srcCompat 加载的好像没用

### ISSUE THREAD

**Issue by CodeToxicant** [ximsfei/Android-skin-support#58]

**Comment by ximsfei** [comment]
这是哪个控件的属性？看一下[更新日志](https://github.com/ximsfei/Android-skin-support/blob/master/ChangeLog.md)，里面有所有已支持的属性。 :-)

**Comment by CodeToxicant** [comment]
这个是ImageView的属性 就是跟src一样的东西 只不过是兼容svg图片用的

**Comment by ximsfei** [comment]
能给个具体的使用例子么? :-)

**Comment by ximsfei** [comment]
已经提交代码啦，但是不知道有没有解决你的问题: `compile 'skin.support:skin-support:2.0.4'`

demo中MainActivity中的[FloatingActionButton](https://github.com/ximsfei/Android-skin-support/blob/master/skin-app/src/main/res/layout/activity_main.xml)使用了`app:srcCompat`来换肤，用的是Android Studio 中创建的Vector Asset资源。

**Comment by CodeToxicant** [comment]
非常感谢 ImageView:
app:srcCompat 就是这个属性
