### ISSUE TITLE
请教一下自定义控件的问题

### ISSUE THREAD

**Issue by CodeToxicant** [ximsfei/Android-skin-support#59]
我自定义了一个BottomNavigationView extends SkinCompatLinearLayout
每个item中放了一个
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="0dp"
    android:layout_height="match_parent"
    android:layout_weight="1"
    android:gravity="center"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/iv_bottom_icon"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

    <TextView
        android:id="@+id/tv_bottom_title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textColor="@drawable/bottom_text_selector" />

</LinearLayout>`

`LayoutInflater inflater = LayoutInflater.from(this.getContext());
        LinearLayout childLayout = (LinearLayout) inflater.inflate(R.layout.item_bottom, this, false);`

里面使用selector设置了一个选中颜色和默认颜色
但是没有效果

**Comment by ximsfei** [comment]
把bottom_text_selector放到color目录下试试
实用的时候
```
<TextView
    android:id="@+id/tv_bottom_title"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:textColor="@color/bottom_text_selector" />
```
