### ISSUE TITLE
报错  生成app 直接就闪退 然后报如下的错 

### ISSUE THREAD

**Issue by liuwen370494581** [ximsfei/Android-skin-support#6]
Didn't find class "skin.support.design.R$styleable" on path: DexPathList[[zip file "/data/app/star.liuwen.com.endskin-1/base.apk"],nativeLibraryDirectories=[/data/app/star.liuwen.com.endskin-1/lib/arm64, /vendor/lib64, /system/lib64]]

我导入了app-skin 然后依赖了
    compile 'skin.support:skin-support:1.0.1'
    compile 'skin.support:skin-support-design:0.0.2'
然后生成app 点击就闪退了 求解

**Comment by ximsfei** [comment]
@liuwen370494581 
什么机型，Android版本好。[demo](https://github.com/ximsfei/Res/blob/master/skin-demo/app-debug.apk)能跑起来么？:)

**Comment by liuwen370494581** [comment]
现在可以了 发现依赖了compile 'skin.support:skin-support:1.0.1'
compile 'skin.support:skin-support-design:0.0.2'  之后
还需要系统的design包 
  compile 'com.android.support:design:25.1.1' 
这样生成app之后就没有闪退了

**Comment by ximsfei** [comment]
@liuwen370494581 
因为skin-support-design包是对material design包中控件换肤的扩展支持。
看来我需要更新到README中。感谢你提出的问题 :)

**Comment by MichealWangDan** [comment]
不兼容Android7.0吗？

**Comment by ximsfei** [comment]
@MichealWangDan 兼容的
