### ISSUE TITLE
RecyclerView.ItemDecoration 这个东西怎么搞 列表的分割线

### ISSUE THREAD

**Issue by CodeToxicant** [ximsfei/Android-skin-support#60]
这个东西怎么搞

**Comment by ximsfei** [comment]
以DividerItemDecoration为例，有一个setDrawable方法，在切换皮肤的时候去set对应的Drawable。
暂时想到以下三种方法来实现，没有这样的需求所以没验证过，你可以先试试，后续我会验证的：
1. 可以继承自SkinCompatActivity，在皮肤切换后会回掉updateSkin方法，在updateSkin方法中调用setDrawable方法，刷新RecyclerView。
2. 可以参考withoutActivity方法，`application.registerActivityLifecycleCallbacks`，注册Activity生命周期回掉，然后添加观察者，监听皮肤切换，调用setDrawable方法，刷新RecyclerView。
3. 以自定义View换肤的方式，自定义RecyclerView，在applySkin方法中去调用setDrawable方法，刷新RecyclerView方法。
^_^

**Comment by CodeToxicant** [comment]
看来只能直接写到adpater里面是最好的了

**Comment by ximsfei** [comment]
嗯。adapter里也是比较方便的。
