### ISSUE TITLE
allowBackup 相关问题

### ISSUE THREAD

**Issue by YummyLau** [ximsfei/Android-skin-support#61]
build项目的时候，使用	skin.support:skin-support:2.0.4有以下失败log：

Attribute application@allowBackup value=(false) from AndroidManifest.xml:67:9-36
	is also present at [skin.support:skin-support:2.0.4] AndroidManifest.xml:12:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:65:5-1065:19 to override.
请参考下，能否关闭skin-support的该属性

**Comment by YummyLau** [comment]
参考 https://developer.android.com/studio/build/manifest-merge.html#_2 官网的做法我替换了就好了。

**Comment by ximsfei** [comment]
哈哈，我刚在该代码。。看来不用改了

**Comment by YummyLau** [comment]
感觉作者很用心，我也挺喜欢这个库的。有个问题，minsdk为14，其实和11已经相差很近了，不选择11的原因是什么呢，毕竟可以兼容“老年化”的app。上述的问题主要是资源合并的冲突，lib包尽量保持干净不对主项目的资源进行“争夺/覆盖”就好了，不过这方面谷歌还是给了方案哈。

**Comment by ximsfei** [comment]
minsdk为14的原因是，刚开始做的时候粗略的想了下，4.0以下的手机应该已经没人用了。。。。^_^
关于上面那个问题，我打算把所有lib里的manifest都清空。看你已经有解决方案了，所以就不单独发版了，等有其他修改再发版，不然更新太频繁了。

**Comment by YummyLau** [comment]
嗯嗯。好~
