### ISSUE TITLE
能不能不另外开发皮肤工程, 直接使用项目内的主题

### ISSUE THREAD

**Issue by csshuai** [ximsfei/Android-skin-support#62]
有些主题只是修改了几个颜色, 再创建一个工程比较麻烦, 直接使用项目内的主题方便多了.

**Comment by ximsfei** [comment]
可以，不知道有没有什么好的实现方案，或者提交个pr呢？^_^

**Comment by ximsfei** [comment]
现在已经支持应用内换肤啦，[应用内换肤](https://github.com/ximsfei/Android-skin-support#%E5%BA%94%E7%94%A8%E5%86%85%E6%8D%A2%E8%82%A4) ^_^

**Comment by mybin** [comment]
这个功能不错，我也纠结了一小会， 差点自己去实现了。
