### ISSUE TITLE
不使用APK方式 ，采用zip方式的皮肤包，

### ISSUE THREAD

**Issue by herohd** [ximsfei/Android-skin-support#63]
要多个平台公用皮肤包，所以只能采用zip方式的情况下，怎么才能更加好的换肤，能提供下思路？

**Comment by ximsfei** [comment]
apk的方式可以实现多平台公用皮肤包：
例如：
平台1: 窗口背景为R.color.windowBackground 黑色
平台2: 窗口背景为R.color.windowBackground 白色
皮肤包: 窗口背景为R.color.windowBackground 红色
只需要将对应窗口背景的资源命名相同即可，这样多平台就可以公用皮肤包了

你说的zip方式是指，直接把xxx.png放到zip包中？
这种情况，你可以自己去重写[SkinCompatResources](https://github.com/ximsfei/Android-skin-support/blob/master/skin-support/src/main/java/skin/support/content/res/SkinCompatResources.java)类，业务层传入平台的资源id，在该类中转换成对应的资源文件路径？

建议用apk的方式实现。^_^

**Comment by herohd** [comment]
采用APK方式，那样IOS就又要另外制作皮肤包，PC也要另外制作，我说的多个平台指的是这些。

**Comment by Gengxiuxiu** [comment]
> 采用APK方式，那样IOS就又要另外制作皮肤包，PC也要另外制作，我说的多个平台指的是这些。所以只能用zip方式。

不知道跨平台换肤用zip实现，你实现没有，能不能参考一下？
