### ISSUE TITLE
能否加入AppCompatImageView AppCompatImageButton的支持

### ISSUE THREAD

**Issue by CodeToxicant** [ximsfei/Android-skin-support#66]
ImageView 可以支持 但是用到app:srcCompat在5.0以下的版本无法兼容，使用了AppCompatImageView,在使用切换皮肤就没效果了

**Comment by ximsfei** [comment]
你用的skin-support版本号是多少？

2.0.4版本，不需要在xml中写AppCompatImageView, 直接在xml中使用ImageView，是支持srcCompat属性的。[demo](https://github.com/ximsfei/Android-skin-support/blob/master/skin-app/src/main/res/layout/activity_main.xml)中的FloatingActionButton就是用srcCompat来换肤的。
^_^

**Comment by CodeToxicant** [comment]
我使用的ImageView  app:srcCompat在5.0以上的版本运行正常，在4.4版本运行就提示找不到svg的XML
vectorDrawables.useSupportLibrary = true
static {
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
    }
支持都加了 但是好像没用 只有改为AppCompatImageView才正常

**Comment by CodeToxicant** [comment]
我这边在测试一下，估计是我的问题。谢谢你

**Comment by ximsfei** [comment]
改为AppCompatImageView正常的话，有可能是换肤框架引起的。有具体的使用例子么，能不能给一个？
