### ISSUE TITLE
和友盟推送的冲突

### ISSUE THREAD

**Issue by MIGOfuns** [ximsfei/Android-skin-support#67]
在集成了友盟推送的sdk后，运行程序会报java.lang.NoClassDefFoundError: skin.support.utils.SkinPreference

**Comment by ximsfei** [comment]
有更多信息么？多进程？

**Comment by MIGOfuns** [comment]
不是多进程，只是工程引入了两个model，一个友盟推送，一个换肤框架，只引用其中任何一个都没有问题，只有两个同时引用会报错。目前的解决办法是把换肤框架直接拷贝到了工程里，只引用友盟一个model，暂时解决了冲突问题。

**Comment by ximsfei** [comment]
应该是appcompat-v7包版本冲突？

**Comment by MIGOfuns** [comment]
我没看出来是什么冲突，看日志，只是说class文件没有找到。版本号是appcompat-v7:25.3.1
