### ISSUE TITLE
5.0以下不支持svg吗？

### ISSUE THREAD

**Issue by kouxinhong** [ximsfei/Android-skin-support#68]
我这边测试了以下，4.3，4.2.2就奔溃了

**Comment by ximsfei** [comment]
给个例子，我试一下？

**Comment by CodeToxicant** [comment]
AppCompatImageView 5.0一下 要使用svg 就要把ImageView替换成这个

**Comment by ximsfei** [comment]
你说的svg是指哪种？
```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="24dp"
        android:height="24dp"
        android:viewportWidth="24.0"
        android:viewportHeight="24.0">
    <path
        android:fillColor="#FF000000"
        android:pathData="M17.65,6.35C16.2,4.9 14.21,4 12,4c-4.42,0 -7.99,3.58 -7.99,8s3.57,8 7.99,8c3.73,0 6.84,-2.55 7.73,-6h-2.08c-0.82,2.33 -3.04,4 -5.65,4 -3.31,0 -6,-2.69 -6,-6s2.69,-6 6,-6c1.66,0 3.14,0.69 4.22,1.78L13,11h7V4l-2.35,2.35z"/>
</vector>
```
是指这种吗？如果是这种，我试了一下没问题。如果不是能给个具体的例子吗？^_^

**Comment by Frankmao0701** [comment]
@ximsfei 您可以在demo里面 给toolbar 设置这个style
 style="@style/ToolBarWithNavigationBack"   

 <style name="ToolBarWithNavigationBack">
        <item name="navigationIcon">@drawable/abc_ic_ab_back_material</item>
    </style> 
demo 会直接崩溃，就是svg 的问题。
还有个问题像问下作者。就是我用这个库后发现应用中很多布局 padding 失效，布局混乱
padding失效的都是在控件里设置了background  .9png。没用库之前布局没事，用了后发现有问题。

**Comment by ximsfei** [comment]
@kouxinhong @WuShengXi @Frankmao0701 
框架最新版本现在已经支持svg换肤啦。

@Frankmao0701 
padding失效问题已经在`compile 'skin.support:skin-support:2.1.10'`中修复。
