### ISSUE TITLE
bugly总是会报这个异常，求分析下。

### ISSUE THREAD

**Issue by willsame** [ximsfei/Android-skin-support#69]
![qq 20170825092150](https://user-images.githubusercontent.com/19715001/29695837-a8cb2392-8977-11e7-8d11-85688ba67b6f.png)
![qq 20170825092233](https://user-images.githubusercontent.com/19715001/29695839-a8f3d684-8977-11e7-888a-25e71906a311.png)

**Comment by willsame** [comment]
![qq 20170825092855](https://user-images.githubusercontent.com/19715001/29695908-09681bba-8978-11e7-8e58-a4df3580c04e.png)

**Comment by ximsfei** [comment]
没想明白为啥，加了个换肤失败的异常处理，防止应用直接崩溃。
有更多信息，可以继续沟通。
