### ISSUE TITLE
增加功能--指定某些控件不换肤

### ISSUE THREAD

**Issue by foxleezh** [ximsfei/Android-skin-support#7]
从性能上讲，让控件不换肤最好的方式就是不受监听，这样可以减少内存和遍历查询时间

实现的思路：
在加入换肤监听的地方做判断，而判断依据最直接的方法就是解析xml
个人觉得可以参照android skin loader的做法，在xml中设置skin:enable=false这种类似的字段，在解析xml时读取出来

毕竟不设置皮肤的情况比较少见，在xml中设置一个值的情况不会太多

**Comment by ximsfei** [comment]
@foxleezh 
你好, 感谢你的支持, 新功能已经开发完成，本地验证通过。
使用方法可参考[换肤开关](https://github.com/ximsfei/Android-skin-support#%E7%9A%AE%E8%82%A4%E5%BC%80%E5%85%B3)
:)
