### ISSUE TITLE
是不是不支持style文件换肤呀

### ISSUE THREAD

**Issue by josephyuen** [ximsfei/Android-skin-support#71]
我这边用到了switchcompat，好像不管用，，，

**Comment by ximsfei** [comment]
1. 框架是支持style换肤的
2. 框架暂时还不支持switchcompat换肤，所以已支持的控件可以参见[更新日志](https://github.com/ximsfei/Android-skin-support/blob/master/ChangeLog.md)，不支持的可以参考自定义View换肤的方式去实现。
^_^
