### ISSUE TITLE
关于module换肤的支持

### ISSUE THREAD

**Issue by SuperKetchup** [ximsfei/Android-skin-support#73]
如果项目含有多个module项目 
要怎么处理skin包来支持module资源的换肤效果

**Comment by ximsfei** [comment]
不需要做任何处理，正常接入就好了。 ^_^
或者是不是遇到什么其他的问题？

**Comment by SuperKetchup** [comment]
没有换成功

**Comment by ximsfei** [comment]
有更多信息？

**Comment by SuperKetchup** [comment]
子module一个linearlayout的background没有换成功

**Comment by SuperKetchup** [comment]
本工程的可以 两个工程的图片用的同一个名称

**Comment by SuperKetchup** [comment]
是不是子module的R和主项目的R不一样的问题？

**Comment by ximsfei** [comment]
你说的module是指插件化么？

**Comment by SuperKetchup** [comment]
不是 只是一个独立的功能模块  为了复用抽离出来

**Comment by ximsfei** [comment]
用不同的名称能换吗？

**Comment by SuperKetchup** [comment]
也不行，我单独换了一套命名 没有成功

**Comment by ximsfei** [comment]
能发个demo出来么？我调一下看看
邮箱ximsfei@gmail.com

**Comment by SuperKetchup** [comment]
我具体定位了下  是在用intent跳activity的时候没有换成功的[https://github.com/SuperKetchup/SkinTest](url) 我post到GitHub上了劳烦看看

**Comment by ximsfei** [comment]
让[TestActivity](https://github.com/SuperKetchup/SkinTest/blob/master/dependencemodule/src/main/java/com/skin/test/dependencemodule/TestAcivity.java)继承自AppCompatActivity即可。
^_^

**Comment by SuperKetchup** [comment]
谢谢 这个issue 可以close了fix #24

**Comment by SuperKetchup** [comment]
closes #24

**Comment by XinYiWorld** [comment]
> 就是说两者的base activity要一致 是这个意思对吧？ 这个issue可以关闭了

为啥我用的同一个base activity，我在module里有res 和res-night两个资源文件夹，module里的activity却没有换肤成功？
