### ISSUE TITLE
色值不是在xml配置的换肤

### ISSUE THREAD

**Issue by baiguangyuan** [ximsfei/Android-skin-support#74]
类似MPAndroidChart这种，色值不是在xml配置。需要在applySkin()中判断当前皮肤手动设置的。
能否提供一个可以获取当前皮肤的方法。
<pre><code>@Override public void applySkin() {
        // 这个判断不对，是上一个的
        if ("night".equals(SkinPreference.getInstance().getSkinName())) {
            // set night colors;
        } else {
            // set Colors;
        }
        postInvalidate();
    }</code></pre>
目前只有SkinCompatResources.getInstance().isDefaultSkin() 判断是否默认,不适合多个皮肤
或者applySkin(String skinName)

**Comment by ximsfei** [comment]
这应该是一个bug.
已经修复啦 `compile 'skin.support:skin-support:2.1.3' `。可以用你的第一种方法实现。

原先在加载完皮肤后，先调用了`notifyUpdateSkin`，UI更新完了才写SharedPreferences.

```java
protected void onPostExecute(String skinName) {
    SkinLog.e("skinName = " + skinName);
    synchronized (mLock) {
        // skinName 为""时，恢复默认皮肤
        if (skinName != null) {
            notifyUpdateSkin();
            SkinPreference.getInstance().setSkinName(skinName).setSkinStrategy(mStrategy.getType()).commitEditor();
            if (mListener != null) mListener.onSuccess();
        } else {
            SkinPreference.getInstance().setSkinName("").setSkinStrategy(SKIN_LOADER_STRATEGY_NONE).commitEditor();
            if (mListener != null) mListener.onFailed("皮肤资源获取失败");
        }
        mLoading = false;
        mLock.notifyAll();
    }
}
```

思考了一下，添加applySkin(String skinName)的话，对于写代码来讲是比较好的解决方案。但是对于sdk来讲，接口稳定比较重要，看着只是增加了一个参数，其实改动较大。所以选择了只修复这个bug。

^_^

**Comment by ximsfei** [comment]
可能你说的两种方法都会存在问题，你是否需要将不同色值写死在应用包里？

我更推荐的话，还是将色值配置在xml中进行换肤.
具体操作:
1. 将色值配置在xml中，命名为chart_color;
2. 通过`SkinCompatResources.getInstance().getColor()`获取当前皮肤的色值;
3. 通过Java代码设置色值。

这样的话，如果想要更新换肤的色值，只需要更新皮肤包就可以了，而且如果要增加更多种色值的话，只需要在对应的皮肤包里加这个值就好了。

```java
int mMPAndroidChartColorResId = R.color.chart_color;
@Override
public void applySkin() {
    int color = SkinCompatResources.getInstance().getColor(mMPAndroidChartColorResId);
    mMPAndroidChart.setColor(color);
}
```
希望这种方法也能满足你的需求 ^_^

**Comment by baiguangyuan** [comment]
单个色值是按你说的那方法处理的，但是有的图表（像饼图）需要的是一系列的颜色，怕麻烦想硬编码来的。不管怎么说还是感谢你开源这个项目，节省不少时间。

**Comment by zzzlw** [comment]
@ximsfei 我觉得这 SkinCompatResources.getInstance().getColor（） 这个方法 应该在wiki 里写一下。
