### ISSUE TITLE
SkinCompatResources 类的getColorStateList方法无法加载放在drawable、mipmap目录的资源文件，麻烦添加支持。

### ISSUE THREAD

**Issue by ihoobin** [ximsfei/Android-skin-support#77]
SkinCompatResources 类的getColorStateList方法无法加载放在drawable、mipmap目录的资源文件，麻烦添加支持。以便使用

 public ColorStateList getColorStateList(int resId) {
        ColorStateList colorStateList = ContextCompat.getColorStateList(mAppContext, resId);
        if (isDefaultSkin) {
            return colorStateList;
        }

        int targetResId = getTargetResId(resId, "color");
        return targetResId == 0 ? colorStateList : mResources.getColorStateList(targetResId);
    }

=============================================
 public ColorStateList getColorStateList(int resId) {
        ColorStateList colorStateList = ContextCompat.getColorStateList(mAppContext, resId);
        if (isDefaultSkin) {
            return colorStateList;
        }

        int targetResId = 0;
        String resName = mAppContext.getResources().getResourceEntryName(resId);
        String typeName = mAppContext.getResources().getResourceTypeName(resId);
        if ("color".equals(typeName)) {
            targetResId = mResources.getIdentifier(resName, "color", mSkinPkgName);
        } else if ("drawable".equals(typeName)) {
            targetResId = mResources.getIdentifier(resName, "drawable", mSkinPkgName);
        } else if ("mipmap".equals(typeName)) {
            targetResId = mResources.getIdentifier(resName, "mipmap", mSkinPkgName);
        }

        if (targetResId == 0) {
            return colorStateList;
        } else {
            try {
                return mResources.getColorStateList(targetResId);
            } catch (Exception e) {
                return colorStateList;
            }
        }
    }
上面是我在你2.0.4的代码上修改的，你的新版本已经做了相关异常处理了。

**Comment by ximsfei** [comment]
哈哈，感谢你的意见，已经在最新代码上修复啦。^_^
