### ISSUE TITLE
按照系统源码自定义的AlertDialog 换肤问题

### ISSUE THREAD

**Issue by willsame** [ximsfei/Android-skin-support#79]
按照系统源码自定义的AlertDialog 布局背景色和字体没有换肤成功，ProgressBar控件倒是换成功了，想问下是什么原因，也参照了你说明的AlertDialog ，还是没有成功
![k0nwx9tlwqb 0c](https://user-images.githubusercontent.com/19715001/30023982-5cbf7c66-91a4-11e7-9965-ae89daf9c575.png)

**Comment by ximsfei** [comment]
发一下应用中照着[文档](https://github.com/ximsfei/Android-skin-support/blob/master/docs/AlertDialog.md)接入的那部分代码？

**Comment by coco86775005** [comment]
我用的自定义的dialog，切换背景颜色也出现了问题，切换皮肤后dialog的背景色不会立马切换，退出应用后再进来才切换过来

**Comment by ximsfei** [comment]
@coco86775005 我觉得提问的时候最好把问题描述清楚？因为demo里都是有例子的，我自己都测过，你们说不行，总得告诉我你们是怎么做的吧。^_^

**Comment by willsame** [comment]
@ximsfei  
![0bfj](https://user-images.githubusercontent.com/19715001/30157450-ee4057e4-93f4-11e7-9149-6db2fef32fe0.png)
![lbgu8](https://user-images.githubusercontent.com/19715001/30157452-ee593f48-93f4-11e7-9230-9068d75c731a.png)

**Comment by ximsfei** [comment]
你这个DownloadProgressDialog 是自定义的布局吧？

**Comment by willsame** [comment]
@ximsfei 是的，仿照系统的写的

**Comment by willsame** [comment]
@ximsfei 仿照的系统的ProgressDialog 写的。

**Comment by ximsfei** [comment]
你布局文件的背景设的啥。

**Comment by willsame** [comment]
@ximsfei   框出来的都是在皮肤包里面配置的颜色和drawable ProgressBar 生效了，字体和背景没有
![1504852199 1](https://user-images.githubusercontent.com/19715001/30198836-81eb42bc-94a2-11e7-8ca1-2099a946a356.jpg)

**Comment by ximsfei** [comment]
不应该会是这样，同一个布局里，要么都成功，要么都失败。
能不能发个demo给我看看？传到github上，或者发我邮箱 ximsfei@gmail.com

**Comment by willsame** [comment]
@ximsfei 已经发你邮件了。

**Comment by ximsfei** [comment]
![image](https://user-images.githubusercontent.com/9425734/30257663-39357bfa-96e6-11e7-9f3e-82298ce6e942.png)
![image](https://user-images.githubusercontent.com/9425734/30257678-4a9bdb8c-96e6-11e7-8cb2-e29d82eb8b4b.png)
![image](https://user-images.githubusercontent.com/9425734/30257686-564fcd3a-96e6-11e7-86fc-26b49cfa67b7.png)
@willsame 并没有设置背景呀。应该是业务层代码问题。好好排查一下。^_^

**Comment by willsame** [comment]
项目中，我是设置了的，这里发给你的是拿掉了背景颜色值。

在 2017-09-11 11:43:20，"Pengfeng Wang" <notifications@github.com> 写道：





@willsame 并没有设置背景呀。应该是业务层代码问题。好好排查一下。^_^

**Comment by ximsfei** [comment]
1. 按照你给我的代码，我加了背景，jia加载字体颜色
![image](https://user-images.githubusercontent.com/9425734/30259408-c56ef184-96f3-11e7-9441-b156264d2ee9.png)
![image](https://user-images.githubusercontent.com/9425734/30259412-ceff4410-96f3-11e7-9615-49662596f4ed.png)
其他没做任何修改，是可以换肤成功的。
2. 按照[文档](https://github.com/ximsfei/Android-skin-support/blob/master/docs/AlertDialog.md)的描述，你需要将android.app.AlertDialog替换成android.support.v7.app.AlertDialog？而你给我的代码用的还是android.app.AlertDialog？

好好排查一下吧。😢

**Comment by willsame** [comment]
不是的，项目中很早就换过来了，按照你的文档里写的修改的，反馈的就是github上面发的那个，进度条换过来了，其他的没有。

**Comment by ximsfei** [comment]
如果可以，能不能提供一个能跑的demo？只给我几个布局文件，我自己写demo的话，肯定是没问题了，毕竟我知道怎么写。无法确定你们实现的哪里出了问题。

**Comment by willsame** [comment]
@ximsfei 通过代码控制方式解决了，demo我现在不好抽取，不知道是不是
![1505289804 1](https://user-images.githubusercontent.com/19715001/30366409-7fcf2ad0-989d-11e7-8069-1e57b312d8c8.jpg)
hongyangAndroid/AndroidAutoLayout的兼容问题，之前用贵库的支持的SkinHookAutoLayoutViewInflater ，渐变色总是换不过来，然后自己重写了一下，逻辑跟楼主是一样的

**Comment by ximsfei** [comment]
可以可以，解决了就好
