### ISSUE TITLE
能否弄个适用于API22版本的库？目前库版本太高，低版本无法兼容。

### ISSUE THREAD

**Issue by chenyongliu** [ximsfei/Android-skin-support#8]

**Comment by ximsfei** [comment]
@chenyongliu 
请问适配API22的库是什么意思呢？
是指这样引用么？
compile 'com.android.support:appcompat-v7:22.0.1'

如果急着解决问题
试试25的库，官方应该是兼容22的
compile 'com.android.support:appcompat-v7:25.1.0'

:)

**Comment by chenyongliu** [comment]
嗯，搞定了。感谢。另外问一下，Fragment如何使用换肤。

**Comment by ximsfei** [comment]
@chenyongliu 
感谢你的支持 :)
https://github.com/ximsfei/Android-skin-support/tree/master/skin-app
https://github.com/ximsfei/Skin-Demo
这两个demo里都有Fragment换肤。基本上没有什么特殊的处理；
如果在某些特殊情况下Fragment中无法实现换肤，希望能过告诉我。
