### ISSUE TITLE
滚动条不能修改

### ISSUE THREAD

**Issue by wsty** [ximsfei/Android-skin-support#80]
更换scrollbarThumbVertical指向的drawable无效

**Comment by ximsfei** [comment]
所有已支持的属性可以查看[更新日志](https://github.com/ximsfei/Android-skin-support/blob/master/docs/ChangeLog.md)，暂未支持的，可以参照自定义View，自行实现。^_^

**Comment by wsty** [comment]
这样的话所有用到滚动条的控件都得自定义是吗

**Comment by ximsfei** [comment]
是的。

**Comment by wsty** [comment]
谢谢
