### ISSUE TITLE
应用内换肤是如何实现的

### ISSUE THREAD

**Issue by liuyuttkx** [ximsfei/Android-skin-support#83]
1.请问应用内换肤具体是如何实现的?
2.创建res-night资源目录是如何实现的?

**Comment by ximsfei** [comment]
```
sourceSets {
    main {
        res.srcDirs = ['src/main/res', 'src/main/res-night']
    }
}
```
build.gradle 中可以指定res-night目录
加载应用内皮肤：
```
// night为资源后缀(_night) , 加载策略选择 SkinCompatManager.SKIN_LOADER_STRATEGY_BUILD_IN
SkinCompatManager.getInstance().loadSkin("night", SkinCompatManager.SKIN_LOADER_STRATEGY_BUILD_IN);
```

**Comment by jianfeng318** [comment]
@ximsfei  正需要这个.. 赞

**Comment by liuyuttkx** [comment]
非常感谢, 我马上试试.

**Comment by ximsfei** [comment]
哈哈，恢复好快。。

**Comment by liuyuttkx** [comment]
我们是在线看楼主的回复. 马上就要用到贵库了

**Comment by jianfeng318** [comment]
@ximsfei  lz的库非常不错,建议建立一个QQ或者微信群,这样解决问题比较方便,哈哈

**Comment by liuyuttkx** [comment]
google了一圈, 没有人做过这种.创建资源文件夹的

**Comment by ximsfei** [comment]
可以可以。

**Comment by liuyuttkx** [comment]
楼主, 请问: 一个项目中多个model, 每个model中都拥有自己的资源文件. 此时需要应用内换肤, 是需要将每个model中都创建一个res-x的文件夹来放对应的资源文件吗?

**Comment by ximsfei** [comment]
可以统一放到一起，也可以分开放

**Comment by liuyuttkx** [comment]
分开放, 只需要在model中创建对应的资源文件夹,并放入对应的资源文件就可以了吗?

资源文件最后会涉及到资源文件的合并. 最终会以App层的为准.  为了修改一些第三方库的资源文件, 我在App层的model中创建了相同的资源文件, 以达到覆盖替换的目的.  同时, 大部分的资源文件是放在公共的model中.

**Comment by ximsfei** [comment]
可以

**Comment by jianfeng318** [comment]
@ximsfei  楼主,麻烦请教下,我的app层module同时依赖了common层的module,和一个其他的第三方的module,有很多自定义的控件都放在了common层,而我的换肤框架也依赖在了common层,我的做法是抽出了一个公共的resource层作为一个顶层单独module,其他所有的module都依赖于它,那么请教楼主这种做法可以吗?涉及到主app层module的一些style下的theme能够切换吗?我现在切换的时候会有一些奇怪的现象,比如我切换到夜间模式,但是背景还是日间模式,但是某一些item变成了夜间模式的颜色..

**Comment by liuyuttkx** [comment]
您好, 请问: Style可以在换肤时, 进行替换吗? 如果可以, 如何实现?
是在新创建的资源文件res-night中创建style.xml.然后将需要替换的样式名后加后缀吗?如下:

    <style name="AppTheme_night" parent="Theme.AppCompat.Light.NoActionBar">

    
    <style name="MainActivityTheme_night" parent="AppTheme_night">

**Comment by ximsfei** [comment]
@jianfeng318 先看看README文件，第三方view控件是需要做修改的，可以看看更新日志，哪里列出了所以已经支持的属性。

**Comment by ximsfei** [comment]
@liuyuttkx 暂时不支持style换肤。

**Comment by liuyuttkx** [comment]
好的, 非常感谢

**Comment by jianfeng318** [comment]
@ximsfei  感谢楼主回复,自定义view我已经按照楼主的适配做了,debug跟了一下也生效了,我发现不是因为这个原因,可能是因为我用了drawable-v21做水波纹效果导致的,不知道楼主实验过没有ripple在drawable-v21下切换背景好像不生效.我也做了一套对应res-night下的drawable-v21,并将ripple的xml后缀名改成了_night结尾,麻烦楼主帮忙看看,或者有这么用过的小伙伴帮忙解答,谢谢

**Comment by huangchaoqingcheng** [comment]
为什么我加了
sourceSets {
    main {
        res.srcDirs = ['src/main/res', 'src/main/res-night']
    }
}
这段后  rebuild了 res-night还是没有出现呢

**Comment by huangchaoqingcheng** [comment]
可以了   原来还要手动新建一下文件夹
