### ISSUE TITLE
贵框架是不是不支持代码中动态设置的资源？

### ISSUE THREAD

**Issue by Leongeneral** [ximsfei/Android-skin-support#84]
我在代码 toolbar.setOverflowIcon(getResources().getDrawable(R.drawable.ic_more_option));中设置的一个图标，切换皮肤，这个图标没有换成ic_more_option_night

**Comment by ximsfei** [comment]
是的，不支持，可以看一下更新日志

2017-09-14 16:52 GMT+08:00 General <notifications@github.com>:

**Comment by pkuoliver** [comment]
有没有支持计划呢？

**Comment by ximsfei** [comment]
支持`setBackgroundResource(R.drawable.background);`无法支持`setBackgroundDrawable(getResources().getDrawable(R.drawable.background));`
