### ISSUE TITLE
大佬好，出现在依赖包为23时出现皮肤资源丢失问题

### ISSUE THREAD

**Issue by TO-21** [ximsfei/Android-skin-support#85]
问题如图
![qq 20170918095058](https://user-images.githubusercontent.com/20886452/30527066-ed059e38-9c56-11e7-9982-cabaa9b8e987.jpg)

**Comment by ximsfei** [comment]
用25试试？

**Comment by TO-21** [comment]
25的环境下没有不会有问题

**Comment by ximsfei** [comment]
用25不行？因为框架是基于25做的，你们必须用23的话可以把代码clone下来，然后build.gradle中的25改成23，应该就好了。

**Comment by TO-21** [comment]
好的，谢谢大佬，我们学校提供的一些串口代码是只能在23运行的
