### ISSUE TITLE
有些自定义控件，在第一次设置换肤的时候，自定义控件的属性没了，再一次切换的时候，又会出现

### ISSUE THREAD

**Issue by GongZiZhang** [ximsfei/Android-skin-support#87]

**Comment by GongZiZhang** [comment]
比如，我有一个可以设置调整textview上下左右图片大小的自定义控件TextViewPlus，切换完皮肤，然后退出应用，再进来时,TextViewPlus设置的图片全不显示了。但是再点一下换肤，图片又显示出来了

**Comment by ximsfei** [comment]
框架不会对自定义的view做处理，好好排查一下

**Comment by GongZiZhang** [comment]
可如果是不继承SkinCompatTextView，换肤是不会出现这个问题的

**Comment by ximsfei** [comment]
继承自SkinCompatTextView说明这个控件是支持换肤的，你那几个上下左右的图片在皮肤包里有吗

**Comment by GongZiZhang** [comment]
我是在应用内换肤的，放了那几张图片，也没效果，而且我用两个手机测试，4.3的三星手机是没问题的，5.1的魅族mx4就会出现这个问题

**Comment by ximsfei** [comment]
理论上是没问题的，在这两个类里打断点看看: `SkinCompatTextHelper` `SkinCompatTextHelperV17`

**Comment by GongZiZhang** [comment]
类里applyCompoundDrawablesResource方法有个checkResourceId（）获取图片id的方法，好像就是这个方法获取到的id全是0；
这种情况只在换完肤退出第一次进来的时候才会出现，进来后，再点一次换肢，id又不是0了

**Comment by ximsfei** [comment]
你用的系统资源吗

**Comment by GongZiZhang** [comment]
是的，mipmap文件夹下的本地图片

**Comment by GongZiZhang** [comment]
需要我把自定义控件发你测试下吗？

**Comment by ximsfei** [comment]
最好是有问题的demo。如果我自己机械，可能就没问题了。。。

**Comment by GongZiZhang** [comment]
那我先用你的demo试下

**Comment by GongZiZhang** [comment]
你的官方demo也是有问题的，进一步进来不会有图片，点击切换皮肤后，才会出现图片。我在想，是不是应用退出后，再进来的时候，有哪方面数据是没有重新刷新的

**Comment by ximsfei** [comment]
fork. 然后提交代码。我拉下来试试

**Comment by GongZiZhang** [comment]
代码拉取有些慢…………

**Comment by ximsfei** [comment]
加QQ群吧，看Readme。直接把代码发给我。
