### ISSUE TITLE
关于混淆后使用SVG的问题

### ISSUE THREAD

**Issue by hushiguang** [ximsfei/Android-skin-support#88]
我现在混淆后
使用插件换肤和SD卡都木有事
但是，使用应用内换肤svg 正常的是`svg_home.xml`,夜间的是`svg_home_night.xml`
我在`build.gradle`中配置了
`` vectorDrawables.useSupportLibrary = true
   sourceSets {
        main {
            res.srcDirs = ['src/main/res', 'src/main/res-night']
        }
    }
``
然后抛出异常
` android.content.res.Resources$NotFoundException: File res/drawable/svg_home_night.xml from drawable resource ID #0x7f020064`
但是我在不混淆的情况下是没有问题的。而且好像只有应用内换肤，会出现异常。
布局文件
` <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="5dp"
        android:src="@drawable/svg_home"/>`
我也尝试了
` <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="5dp"
        app:srcCompat="@drawable/svg_home"/>`
但是都是同样的问题。
跪求大佬给个思路

**Comment by ximsfei** [comment]
需要换肤的资源不能混淆，框架使用过资源名找的。 ^_^

**Comment by hushiguang** [comment]
了解。目前先把这个资源混淆去掉，暂时木有找到好的keep方案。
