### ISSUE TITLE
关于EditText  光标颜色的更改的问题  

### ISSUE THREAD

**Issue by josephyuen** [ximsfei/Android-skin-support#89]
我在 SkincompatEditText中 按照  stackoverflow 上面大神的**方法二** ,附上链接:  [](https://stackoverflow.com/a/32474978/8552156)  .   针对Editext 我在 6.0 及以下的手机上面测试没有问题,但是在7.0的华为mate9手机上面失败了!   不知道大佬有没有什么好的建议,感谢!

**Comment by josephyuen** [comment]
https://stackoverflow.com/a/32474978/8552156

**Comment by ximsfei** [comment]
也许[Android-theme-support](https://github.com/ximsfei/Android-theme-support/blob/master/android-support/theme-support/src/main/java/skin/support/widget/SkinCompatTextHelper.java)中的`applyTextCursorDrawableResource`对你有用

**Comment by ximsfei** [comment]
因为通过反射来做的，所以是不是需要看看，华为的rom，相关的字段改名了。

**Comment by josephyuen** [comment]
好的,谢谢

**Comment by ximsfei** [comment]
华为重写了Editor类。
所以把这句`Class<?> clazz = editor.getClass();`改成`Class<?> clazz = Class.forName("android.widget.Editor");`应该就好了
