### ISSUE TITLE
内存消耗严重

### ISSUE THREAD

**Issue by youlookwhat** [ximsfei/Android-skin-support#9]
1.植入换肤模块后，刷新图片列表(RecyclerView)，GC基本失效，内存基本只升不降，去掉后恢复正常，
2.控制台一直打log，影响项目调试，希望关掉多余日志。

**Comment by ximsfei** [comment]
正在努力解决问题中.
感谢你发现这个问题，并反馈给我.
:)

**Comment by ximsfei** [comment]
@youlookwhat 
很高兴你反馈了这个问题，经过不懈努力，该bug已在1.0.2版本上修复。本地验证没有问题，请更新一下版本号，试一下是否解决了你的问题。如果还没有解决，烦请再反馈给我，我们一起连调一下。:)

**Comment by GitHubAFeng** [comment]
@youlookwhat
好巧，刚刚从你那串门过来

**Comment by youlookwhat** [comment]
@GitHubAFeng 哈哈  很巧 看起来你活跃度挺高~
@ximsfei 这段时间还没时间测，等之后测了再反馈哦
