### ISSUE TITLE
请问贵框架支持自定义颜色换肤吗？

### ISSUE THREAD

**Issue by JansonChenQ** [ximsfei/Android-skin-support#90]
可以手动选择颜色值，改变背景色吗？

**Comment by ximsfei** [comment]
没看懂，详细些。~_~

**Comment by JansonChenQ** [comment]
就是您最佳换肤实践实例APP中的自选颜色换肤功能，看您好像没有实现。

**Comment by ximsfei** [comment]
可以取自定义
所有的皮肤资源都是通过SkinCompatResources类来获取的，你可以在这里判断相应的资源是否需要使用手动选择的颜色

**Comment by JansonChenQ** [comment]
好的谢谢！我再研究一下。

**Comment by fengminchao** [comment]
@JansonChenQ 你的意思应该是像网易云音乐那样用户输入ARGB色值来改变颜色吧？那种应该是用矢量图来做，在代码中动态更改主题颜色，可以在这个框架基础上扩展这个功能。

**Comment by JansonChenQ** [comment]
@fengminchao 我改一下，发现不太好扩展啊，
