### ISSUE TITLE
请问怎么支持悬浮窗换肤，windowsManager添加的view

### ISSUE THREAD

**Issue by google2720** [ximsfei/Android-skin-support#92]

**Comment by ximsfei** [comment]
我在[demo](https://github.com/ximsfei/Android-skin-support/tree/master/demo/skin-app/src/main/java/com/ximsfei/skindemo/window)里加了一下WindowManager添加View的换肤实现，你可以参考一下，看看是不是你需要的。同时需要使用最新的版本[2.1.8](https://github.com/ximsfei/Android-skin-support/blob/master/docs/ChangeLog.md#skin-support-基础控件-支持)，使用Application的LayoutInfalter.inflate来创建View。^_^

**Comment by google2720** [comment]
谢谢，还有一个问题 
我使用贵框架是用在Launcher上面，而且是使系统应用，现在的情况下，换肤后必须要finish该activity才能生效，不知道 为什么

**Comment by ximsfei** [comment]
啥意思？

**Comment by google2720** [comment]
就是换完肤，不能立即生效，要重启Activity

**Comment by ximsfei** [comment]
那不会，可能是接入问题，可以加群描述一下
