### ISSUE TITLE
请问动态添加的View怎么支持换肤？

### ISSUE THREAD

**Issue by google2720** [ximsfei/Android-skin-support#93]
<LinearLayout
        android:layout_width="match_parent"
        android:id="@+id/apps_view"
        android:layout_height="match_parent"
        android:orientation="vertical">

      <Button
            android:text="哈哈哈"
            android:layout_width="match_parent"
            android:background="@drawable/card_common_bg"
            android:layout_height="match_parent"/>

    </LinearLayout>
这样是可以的。

然后代码中动态添加的不行
       allAppsView = (LinearLayout) findViewById(R.id.apps_view);
        Button button = new Button(this);
        button.setText("哈哈哈");
        button.setBackgroundResource(R.drawable.card_common_bg);
        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(PagedView.LayoutParams.MATCH_PARENT,PagedView.LayoutParams.MATCH_PARENT);
        allAppsView.addView(button, params);

**Comment by ximsfei** [comment]
可以看一下[FAQ](https://github.com/ximsfei/Android-skin-support/blob/master/docs/FAQ.md#代码内实例化的view对象不能更新皮肤)
