### ISSUE TITLE
RadioButton换肤时textColor没成功

### ISSUE THREAD

**Issue by KarasJoker** [ximsfei/Android-skin-support#94]
android:textColor="@drawable/tab_text_colour_selector"

<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/color_main_radio_text_true" android:state_checked="true"/>
    <item android:color="@color/color_main_radio_text_false" android:state_checked="false"/>
</selector>

<color name="color_main_radio_text_true">#f2473d</color>
    <color name="color_main_radio_text_false">#FF888888</color>

tab_text_colour_selector放在drawable文件下了，皮肤包和主工程都依赖v7:25.1.0切换不成功，请问是怎么回事，起切换drawable是没问题。还望大神指点。另外问一下，更换尺寸怎么搞，没太搞出来

**Comment by ximsfei** [comment]
[demo](https://github.com/ximsfei/Android-skin-support/blob/master/demo/skin-app/src/main/res/layout/fragment.xml)中有使用的例子。可以参考一下
