### ISSUE TITLE
状态栏换肤

### ISSUE THREAD

**Issue by futianyi1994** [ximsfei/Android-skin-support#95]
在Application中设置状态栏换肤后，在默认启动Activity页面即使代码设置状态栏为其他颜色也无效，其他页面正常是什么原因？设置状态栏换肤后是在什么时候换肤的

**Comment by ximsfei** [comment]
在Activity的super.onCreate方法中，执行换肤的操作。理论上所有页面都不受影响，现排查一下，不行搞个demo。

**Comment by donnyzhou** [comment]
我也遇到状态栏换肤的问题。设置带actionbar的主题后状态栏换肤不成功，其他控件都正常。怎么解决？（无actionbar则无问题）

**Comment by ximsfei** [comment]
@donnyzhou @futianyi1994 
可以看一下这个类[SkinActivityLifecycle.java](https://github.com/ximsfei/Android-skin-support/blob/master/android-support/skin-support/src/main/java/skin/support/app/SkinActivityLifecycle.java) `updateStatusBarColor`方法
```
private void updateStatusBarColor(Activity activity) {
    if (SkinCompatManager.getInstance().isSkinStatusBarColorEnable()
            && Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
        int statusBarColorResId = SkinCompatThemeUtils.getStatusBarColorResId(activity);
        int colorPrimaryDarkResId = SkinCompatThemeUtils.getColorPrimaryDarkResId(activity);
        if (checkResourceId(statusBarColorResId) != INVALID_ID) {
            activity.getWindow().setStatusBarColor(SkinCompatResources.getInstance().getColor(statusBarColorResId));
        } else if (checkResourceId(colorPrimaryDarkResId) != INVALID_ID) {
            activity.getWindow().setStatusBarColor(SkinCompatResources.getInstance().getColor(colorPrimaryDarkResId));
        }
    }
}
```
优先使用`android.R.attr.statusBarColor`，再使用`R.attr.colorPrimaryDark`进行状态栏换肤，看看主题里面，这两个值是否是对的。

**Comment by futianyi1994** [comment]
感谢作者啊，另外自定义的控件要怎么实现换肤呢继承已有的控件不起作用啊 

发送自 Windows 10 版邮件应用

发件人: Pengfeng Wang
发送时间: 2017年11月7日 下午 10:19
收件人: ximsfei/Android-skin-support
抄送: 傅天一; Mention
主题: Re: [ximsfei/Android-skin-support] 状态栏换肤 (#95)

@donnyzhou @futianyi1994
可以看一下这个类SkinActivityLifecycle.java updateStatusBarColor方法
private void updateStatusBarColor(Activity activity) {
    if (SkinCompatManager.getInstance().isSkinStatusBarColorEnable()
            && Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
        int statusBarColorResId = SkinCompatThemeUtils.getStatusBarColorResId(activity);
        int colorPrimaryDarkResId = SkinCompatThemeUtils.getColorPrimaryDarkResId(activity);
        if (checkResourceId(statusBarColorResId) != INVALID_ID) {
            activity.getWindow().setStatusBarColor(SkinCompatResources.getInstance().getColor(statusBarColorResId));
        } else if (checkResourceId(colorPrimaryDarkResId) != INVALID_ID) {
            activity.getWindow().setStatusBarColor(SkinCompatResources.getInstance().getColor(colorPrimaryDarkResId));
        }
    }
}
优先使用android.R.attr.statusBarColor，再使用R.attr.colorPrimaryDark进行状态栏换肤，看看主题里面，这两个值是否是对的。

**Comment by ximsfei** [comment]
@futianyi1994 
[这里](https://github.com/ximsfei/Android-skin-support#custom-view-skin-support)有自定义View的例子。

**Comment by donnyzhou** [comment]
@ximsfei 感谢！这个问题已经解决。
用下面这个主题从android.R.attr.statusBarColor里拿不到resId。
android:theme="@android:style/Theme.Holo.Light.DarkActionBar
改成下面这个主题后就OK了
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
