### ISSUE TITLE
为什么换肤界面上还是白色没有换成黑色呢？

### ISSUE THREAD

**Issue by PeterXiaosa** [ximsfei/Android-skin-support#98]
我导入了4个依赖'skin.support:skin-support:2.1.9' 'skin.support:skin-support-design:1.2.5'  'skin.support:skin-support-cardview:1.2.0' 'skin.support:skin-support-constraint-layout:1.0.2' 
然后在application中的oncreate()copy过去了，可是类CustomSDCardLoader，SkinHookAutoLayoutViewInflater，SkinCircleImageViewInflater，SkinFlycoTabLayoutInflater提示找不到类，请问能帮助一下吗，我是小白...

**Comment by PeterXiaosa** [comment]
还想问下应用内换肤的皮肤的资源文件是放在哪里呀？

**Comment by ximsfei** [comment]
`CustomSDCardLoader`是demo里的类，`SkinHookAutoLayoutViewInflater``SkinCircleImageViewInflater``SkinFlycoTabLayoutInflater`这三个是其他包里的，删掉就好，不影响。
应用内换肤随便放哪儿都行。
