### ISSUE TITLE
作者 觉得这个换肤库 怎么样？https://github.com/iceAnson/Android-Skin 

### ISSUE THREAD

**Issue by finddreams** [ximsfei/Android-skin-support#99]

**Comment by ximsfei** [comment]
｡◕‿◕｡

**Comment by pkuoliver** [comment]
大致的看了一下，Android-skin-support要比Android-Skin功能更强大，使用调用简单。
Android-Skin的接口貌似更丰富一些（单从文档对比，Android-Skin没实际用过）。当然接口多了可能在完成更个性化的需求的时候会造成业务入侵，这是一个仁者见仁的事情。

在使用Android-skin-support的过程中，遇到一些坑，从使用者的角度来看，是文档内容有些地方没有提到。如果可以，我从使用者的角度提供一部分文档。来丰富一下。

**Comment by ximsfei** [comment]
@pkuoliver 可以可以，欢迎pr。｡◕‿◕｡
